package com.etong.pt.data.customer;

import com.etong.pt.utility.PageLimit;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class PtCustomerExample extends PageLimit implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated Sat May 23 10:55:57 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated Sat May 23 10:55:57 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated Sat May 23 10:55:57 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated Sat May 23 10:55:57 CST 2015
     */
    public PtCustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated Sat May 23 10:55:57 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated Sat May 23 10:55:57 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated Sat May 23 10:55:57 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated Sat May 23 10:55:57 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated Sat May 23 10:55:57 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated Sat May 23 10:55:57 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated Sat May 23 10:55:57 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated Sat May 23 10:55:57 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated Sat May 23 10:55:57 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated Sat May 23 10:55:57 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated Sat May 23 10:55:57 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andF_ciidIsNull() {
            addCriterion("f_ciid is null");
            return (Criteria) this;
        }

        public Criteria andF_ciidIsNotNull() {
            addCriterion("f_ciid is not null");
            return (Criteria) this;
        }

        public Criteria andF_ciidEqualTo(Long value) {
            addCriterion("f_ciid =", value, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidNotEqualTo(Long value) {
            addCriterion("f_ciid <>", value, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidGreaterThan(Long value) {
            addCriterion("f_ciid >", value, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidGreaterThanOrEqualTo(Long value) {
            addCriterion("f_ciid >=", value, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidLessThan(Long value) {
            addCriterion("f_ciid <", value, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidLessThanOrEqualTo(Long value) {
            addCriterion("f_ciid <=", value, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidIn(List<Long> values) {
            addCriterion("f_ciid in", values, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidNotIn(List<Long> values) {
            addCriterion("f_ciid not in", values, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidBetween(Long value1, Long value2) {
            addCriterion("f_ciid between", value1, value2, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidNotBetween(Long value1, Long value2) {
            addCriterion("f_ciid not between", value1, value2, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_nameIsNull() {
            addCriterion("f_name is null");
            return (Criteria) this;
        }

        public Criteria andF_nameIsNotNull() {
            addCriterion("f_name is not null");
            return (Criteria) this;
        }

        public Criteria andF_nameEqualTo(String value) {
            addCriterion("f_name =", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameNotEqualTo(String value) {
            addCriterion("f_name <>", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameGreaterThan(String value) {
            addCriterion("f_name >", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameGreaterThanOrEqualTo(String value) {
            addCriterion("f_name >=", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameLessThan(String value) {
            addCriterion("f_name <", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameLessThanOrEqualTo(String value) {
            addCriterion("f_name <=", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameLike(String value) {
            addCriterion("f_name like", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameNotLike(String value) {
            addCriterion("f_name not like", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameIn(List<String> values) {
            addCriterion("f_name in", values, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameNotIn(List<String> values) {
            addCriterion("f_name not in", values, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameBetween(String value1, String value2) {
            addCriterion("f_name between", value1, value2, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameNotBetween(String value1, String value2) {
            addCriterion("f_name not between", value1, value2, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_sexIsNull() {
            addCriterion("f_sex is null");
            return (Criteria) this;
        }

        public Criteria andF_sexIsNotNull() {
            addCriterion("f_sex is not null");
            return (Criteria) this;
        }

        public Criteria andF_sexEqualTo(Byte value) {
            addCriterion("f_sex =", value, "f_sex");
            return (Criteria) this;
        }

        public Criteria andF_sexNotEqualTo(Byte value) {
            addCriterion("f_sex <>", value, "f_sex");
            return (Criteria) this;
        }

        public Criteria andF_sexGreaterThan(Byte value) {
            addCriterion("f_sex >", value, "f_sex");
            return (Criteria) this;
        }

        public Criteria andF_sexGreaterThanOrEqualTo(Byte value) {
            addCriterion("f_sex >=", value, "f_sex");
            return (Criteria) this;
        }

        public Criteria andF_sexLessThan(Byte value) {
            addCriterion("f_sex <", value, "f_sex");
            return (Criteria) this;
        }

        public Criteria andF_sexLessThanOrEqualTo(Byte value) {
            addCriterion("f_sex <=", value, "f_sex");
            return (Criteria) this;
        }

        public Criteria andF_sexIn(List<Byte> values) {
            addCriterion("f_sex in", values, "f_sex");
            return (Criteria) this;
        }

        public Criteria andF_sexNotIn(List<Byte> values) {
            addCriterion("f_sex not in", values, "f_sex");
            return (Criteria) this;
        }

        public Criteria andF_sexBetween(Byte value1, Byte value2) {
            addCriterion("f_sex between", value1, value2, "f_sex");
            return (Criteria) this;
        }

        public Criteria andF_sexNotBetween(Byte value1, Byte value2) {
            addCriterion("f_sex not between", value1, value2, "f_sex");
            return (Criteria) this;
        }

        public Criteria andF_marriageIsNull() {
            addCriterion("f_marriage is null");
            return (Criteria) this;
        }

        public Criteria andF_marriageIsNotNull() {
            addCriterion("f_marriage is not null");
            return (Criteria) this;
        }

        public Criteria andF_marriageEqualTo(Byte value) {
            addCriterion("f_marriage =", value, "f_marriage");
            return (Criteria) this;
        }

        public Criteria andF_marriageNotEqualTo(Byte value) {
            addCriterion("f_marriage <>", value, "f_marriage");
            return (Criteria) this;
        }

        public Criteria andF_marriageGreaterThan(Byte value) {
            addCriterion("f_marriage >", value, "f_marriage");
            return (Criteria) this;
        }

        public Criteria andF_marriageGreaterThanOrEqualTo(Byte value) {
            addCriterion("f_marriage >=", value, "f_marriage");
            return (Criteria) this;
        }

        public Criteria andF_marriageLessThan(Byte value) {
            addCriterion("f_marriage <", value, "f_marriage");
            return (Criteria) this;
        }

        public Criteria andF_marriageLessThanOrEqualTo(Byte value) {
            addCriterion("f_marriage <=", value, "f_marriage");
            return (Criteria) this;
        }

        public Criteria andF_marriageIn(List<Byte> values) {
            addCriterion("f_marriage in", values, "f_marriage");
            return (Criteria) this;
        }

        public Criteria andF_marriageNotIn(List<Byte> values) {
            addCriterion("f_marriage not in", values, "f_marriage");
            return (Criteria) this;
        }

        public Criteria andF_marriageBetween(Byte value1, Byte value2) {
            addCriterion("f_marriage between", value1, value2, "f_marriage");
            return (Criteria) this;
        }

        public Criteria andF_marriageNotBetween(Byte value1, Byte value2) {
            addCriterion("f_marriage not between", value1, value2, "f_marriage");
            return (Criteria) this;
        }

        public Criteria andF_phoneIsNull() {
            addCriterion("f_phone is null");
            return (Criteria) this;
        }

        public Criteria andF_phoneIsNotNull() {
            addCriterion("f_phone is not null");
            return (Criteria) this;
        }

        public Criteria andF_phoneEqualTo(String value) {
            addCriterion("f_phone =", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotEqualTo(String value) {
            addCriterion("f_phone <>", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneGreaterThan(String value) {
            addCriterion("f_phone >", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneGreaterThanOrEqualTo(String value) {
            addCriterion("f_phone >=", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneLessThan(String value) {
            addCriterion("f_phone <", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneLessThanOrEqualTo(String value) {
            addCriterion("f_phone <=", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneLike(String value) {
            addCriterion("f_phone like", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotLike(String value) {
            addCriterion("f_phone not like", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneIn(List<String> values) {
            addCriterion("f_phone in", values, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotIn(List<String> values) {
            addCriterion("f_phone not in", values, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneBetween(String value1, String value2) {
            addCriterion("f_phone between", value1, value2, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotBetween(String value1, String value2) {
            addCriterion("f_phone not between", value1, value2, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_idcardIsNull() {
            addCriterion("f_idcard is null");
            return (Criteria) this;
        }

        public Criteria andF_idcardIsNotNull() {
            addCriterion("f_idcard is not null");
            return (Criteria) this;
        }

        public Criteria andF_idcardEqualTo(String value) {
            addCriterion("f_idcard =", value, "f_idcard");
            return (Criteria) this;
        }

        public Criteria andF_idcardNotEqualTo(String value) {
            addCriterion("f_idcard <>", value, "f_idcard");
            return (Criteria) this;
        }

        public Criteria andF_idcardGreaterThan(String value) {
            addCriterion("f_idcard >", value, "f_idcard");
            return (Criteria) this;
        }

        public Criteria andF_idcardGreaterThanOrEqualTo(String value) {
            addCriterion("f_idcard >=", value, "f_idcard");
            return (Criteria) this;
        }

        public Criteria andF_idcardLessThan(String value) {
            addCriterion("f_idcard <", value, "f_idcard");
            return (Criteria) this;
        }

        public Criteria andF_idcardLessThanOrEqualTo(String value) {
            addCriterion("f_idcard <=", value, "f_idcard");
            return (Criteria) this;
        }

        public Criteria andF_idcardLike(String value) {
            addCriterion("f_idcard like", value, "f_idcard");
            return (Criteria) this;
        }

        public Criteria andF_idcardNotLike(String value) {
            addCriterion("f_idcard not like", value, "f_idcard");
            return (Criteria) this;
        }

        public Criteria andF_idcardIn(List<String> values) {
            addCriterion("f_idcard in", values, "f_idcard");
            return (Criteria) this;
        }

        public Criteria andF_idcardNotIn(List<String> values) {
            addCriterion("f_idcard not in", values, "f_idcard");
            return (Criteria) this;
        }

        public Criteria andF_idcardBetween(String value1, String value2) {
            addCriterion("f_idcard between", value1, value2, "f_idcard");
            return (Criteria) this;
        }

        public Criteria andF_idcardNotBetween(String value1, String value2) {
            addCriterion("f_idcard not between", value1, value2, "f_idcard");
            return (Criteria) this;
        }

        public Criteria andF_addressIsNull() {
            addCriterion("f_address is null");
            return (Criteria) this;
        }

        public Criteria andF_addressIsNotNull() {
            addCriterion("f_address is not null");
            return (Criteria) this;
        }

        public Criteria andF_addressEqualTo(String value) {
            addCriterion("f_address =", value, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressNotEqualTo(String value) {
            addCriterion("f_address <>", value, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressGreaterThan(String value) {
            addCriterion("f_address >", value, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressGreaterThanOrEqualTo(String value) {
            addCriterion("f_address >=", value, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressLessThan(String value) {
            addCriterion("f_address <", value, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressLessThanOrEqualTo(String value) {
            addCriterion("f_address <=", value, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressLike(String value) {
            addCriterion("f_address like", value, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressNotLike(String value) {
            addCriterion("f_address not like", value, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressIn(List<String> values) {
            addCriterion("f_address in", values, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressNotIn(List<String> values) {
            addCriterion("f_address not in", values, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressBetween(String value1, String value2) {
            addCriterion("f_address between", value1, value2, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressNotBetween(String value1, String value2) {
            addCriterion("f_address not between", value1, value2, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_houseIsNull() {
            addCriterion("f_house is null");
            return (Criteria) this;
        }

        public Criteria andF_houseIsNotNull() {
            addCriterion("f_house is not null");
            return (Criteria) this;
        }

        public Criteria andF_houseEqualTo(String value) {
            addCriterion("f_house =", value, "f_house");
            return (Criteria) this;
        }

        public Criteria andF_houseNotEqualTo(String value) {
            addCriterion("f_house <>", value, "f_house");
            return (Criteria) this;
        }

        public Criteria andF_houseGreaterThan(String value) {
            addCriterion("f_house >", value, "f_house");
            return (Criteria) this;
        }

        public Criteria andF_houseGreaterThanOrEqualTo(String value) {
            addCriterion("f_house >=", value, "f_house");
            return (Criteria) this;
        }

        public Criteria andF_houseLessThan(String value) {
            addCriterion("f_house <", value, "f_house");
            return (Criteria) this;
        }

        public Criteria andF_houseLessThanOrEqualTo(String value) {
            addCriterion("f_house <=", value, "f_house");
            return (Criteria) this;
        }

        public Criteria andF_houseLike(String value) {
            addCriterion("f_house like", value, "f_house");
            return (Criteria) this;
        }

        public Criteria andF_houseNotLike(String value) {
            addCriterion("f_house not like", value, "f_house");
            return (Criteria) this;
        }

        public Criteria andF_houseIn(List<String> values) {
            addCriterion("f_house in", values, "f_house");
            return (Criteria) this;
        }

        public Criteria andF_houseNotIn(List<String> values) {
            addCriterion("f_house not in", values, "f_house");
            return (Criteria) this;
        }

        public Criteria andF_houseBetween(String value1, String value2) {
            addCriterion("f_house between", value1, value2, "f_house");
            return (Criteria) this;
        }

        public Criteria andF_houseNotBetween(String value1, String value2) {
            addCriterion("f_house not between", value1, value2, "f_house");
            return (Criteria) this;
        }

        public Criteria andF_companyIsNull() {
            addCriterion("f_company is null");
            return (Criteria) this;
        }

        public Criteria andF_companyIsNotNull() {
            addCriterion("f_company is not null");
            return (Criteria) this;
        }

        public Criteria andF_companyEqualTo(String value) {
            addCriterion("f_company =", value, "f_company");
            return (Criteria) this;
        }

        public Criteria andF_companyNotEqualTo(String value) {
            addCriterion("f_company <>", value, "f_company");
            return (Criteria) this;
        }

        public Criteria andF_companyGreaterThan(String value) {
            addCriterion("f_company >", value, "f_company");
            return (Criteria) this;
        }

        public Criteria andF_companyGreaterThanOrEqualTo(String value) {
            addCriterion("f_company >=", value, "f_company");
            return (Criteria) this;
        }

        public Criteria andF_companyLessThan(String value) {
            addCriterion("f_company <", value, "f_company");
            return (Criteria) this;
        }

        public Criteria andF_companyLessThanOrEqualTo(String value) {
            addCriterion("f_company <=", value, "f_company");
            return (Criteria) this;
        }

        public Criteria andF_companyLike(String value) {
            addCriterion("f_company like", value, "f_company");
            return (Criteria) this;
        }

        public Criteria andF_companyNotLike(String value) {
            addCriterion("f_company not like", value, "f_company");
            return (Criteria) this;
        }

        public Criteria andF_companyIn(List<String> values) {
            addCriterion("f_company in", values, "f_company");
            return (Criteria) this;
        }

        public Criteria andF_companyNotIn(List<String> values) {
            addCriterion("f_company not in", values, "f_company");
            return (Criteria) this;
        }

        public Criteria andF_companyBetween(String value1, String value2) {
            addCriterion("f_company between", value1, value2, "f_company");
            return (Criteria) this;
        }

        public Criteria andF_companyNotBetween(String value1, String value2) {
            addCriterion("f_company not between", value1, value2, "f_company");
            return (Criteria) this;
        }

        public Criteria andF_positionIsNull() {
            addCriterion("f_position is null");
            return (Criteria) this;
        }

        public Criteria andF_positionIsNotNull() {
            addCriterion("f_position is not null");
            return (Criteria) this;
        }

        public Criteria andF_positionEqualTo(String value) {
            addCriterion("f_position =", value, "f_position");
            return (Criteria) this;
        }

        public Criteria andF_positionNotEqualTo(String value) {
            addCriterion("f_position <>", value, "f_position");
            return (Criteria) this;
        }

        public Criteria andF_positionGreaterThan(String value) {
            addCriterion("f_position >", value, "f_position");
            return (Criteria) this;
        }

        public Criteria andF_positionGreaterThanOrEqualTo(String value) {
            addCriterion("f_position >=", value, "f_position");
            return (Criteria) this;
        }

        public Criteria andF_positionLessThan(String value) {
            addCriterion("f_position <", value, "f_position");
            return (Criteria) this;
        }

        public Criteria andF_positionLessThanOrEqualTo(String value) {
            addCriterion("f_position <=", value, "f_position");
            return (Criteria) this;
        }

        public Criteria andF_positionLike(String value) {
            addCriterion("f_position like", value, "f_position");
            return (Criteria) this;
        }

        public Criteria andF_positionNotLike(String value) {
            addCriterion("f_position not like", value, "f_position");
            return (Criteria) this;
        }

        public Criteria andF_positionIn(List<String> values) {
            addCriterion("f_position in", values, "f_position");
            return (Criteria) this;
        }

        public Criteria andF_positionNotIn(List<String> values) {
            addCriterion("f_position not in", values, "f_position");
            return (Criteria) this;
        }

        public Criteria andF_positionBetween(String value1, String value2) {
            addCriterion("f_position between", value1, value2, "f_position");
            return (Criteria) this;
        }

        public Criteria andF_positionNotBetween(String value1, String value2) {
            addCriterion("f_position not between", value1, value2, "f_position");
            return (Criteria) this;
        }

        public Criteria andF_cardtypeIsNull() {
            addCriterion("f_cardtype is null");
            return (Criteria) this;
        }

        public Criteria andF_cardtypeIsNotNull() {
            addCriterion("f_cardtype is not null");
            return (Criteria) this;
        }

        public Criteria andF_cardtypeEqualTo(String value) {
            addCriterion("f_cardtype =", value, "f_cardtype");
            return (Criteria) this;
        }

        public Criteria andF_cardtypeNotEqualTo(String value) {
            addCriterion("f_cardtype <>", value, "f_cardtype");
            return (Criteria) this;
        }

        public Criteria andF_cardtypeGreaterThan(String value) {
            addCriterion("f_cardtype >", value, "f_cardtype");
            return (Criteria) this;
        }

        public Criteria andF_cardtypeGreaterThanOrEqualTo(String value) {
            addCriterion("f_cardtype >=", value, "f_cardtype");
            return (Criteria) this;
        }

        public Criteria andF_cardtypeLessThan(String value) {
            addCriterion("f_cardtype <", value, "f_cardtype");
            return (Criteria) this;
        }

        public Criteria andF_cardtypeLessThanOrEqualTo(String value) {
            addCriterion("f_cardtype <=", value, "f_cardtype");
            return (Criteria) this;
        }

        public Criteria andF_cardtypeLike(String value) {
            addCriterion("f_cardtype like", value, "f_cardtype");
            return (Criteria) this;
        }

        public Criteria andF_cardtypeNotLike(String value) {
            addCriterion("f_cardtype not like", value, "f_cardtype");
            return (Criteria) this;
        }

        public Criteria andF_cardtypeIn(List<String> values) {
            addCriterion("f_cardtype in", values, "f_cardtype");
            return (Criteria) this;
        }

        public Criteria andF_cardtypeNotIn(List<String> values) {
            addCriterion("f_cardtype not in", values, "f_cardtype");
            return (Criteria) this;
        }

        public Criteria andF_cardtypeBetween(String value1, String value2) {
            addCriterion("f_cardtype between", value1, value2, "f_cardtype");
            return (Criteria) this;
        }

        public Criteria andF_cardtypeNotBetween(String value1, String value2) {
            addCriterion("f_cardtype not between", value1, value2, "f_cardtype");
            return (Criteria) this;
        }

        public Criteria andF_residenceIsNull() {
            addCriterion("f_residence is null");
            return (Criteria) this;
        }

        public Criteria andF_residenceIsNotNull() {
            addCriterion("f_residence is not null");
            return (Criteria) this;
        }

        public Criteria andF_residenceEqualTo(String value) {
            addCriterion("f_residence =", value, "f_residence");
            return (Criteria) this;
        }

        public Criteria andF_residenceNotEqualTo(String value) {
            addCriterion("f_residence <>", value, "f_residence");
            return (Criteria) this;
        }

        public Criteria andF_residenceGreaterThan(String value) {
            addCriterion("f_residence >", value, "f_residence");
            return (Criteria) this;
        }

        public Criteria andF_residenceGreaterThanOrEqualTo(String value) {
            addCriterion("f_residence >=", value, "f_residence");
            return (Criteria) this;
        }

        public Criteria andF_residenceLessThan(String value) {
            addCriterion("f_residence <", value, "f_residence");
            return (Criteria) this;
        }

        public Criteria andF_residenceLessThanOrEqualTo(String value) {
            addCriterion("f_residence <=", value, "f_residence");
            return (Criteria) this;
        }

        public Criteria andF_residenceLike(String value) {
            addCriterion("f_residence like", value, "f_residence");
            return (Criteria) this;
        }

        public Criteria andF_residenceNotLike(String value) {
            addCriterion("f_residence not like", value, "f_residence");
            return (Criteria) this;
        }

        public Criteria andF_residenceIn(List<String> values) {
            addCriterion("f_residence in", values, "f_residence");
            return (Criteria) this;
        }

        public Criteria andF_residenceNotIn(List<String> values) {
            addCriterion("f_residence not in", values, "f_residence");
            return (Criteria) this;
        }

        public Criteria andF_residenceBetween(String value1, String value2) {
            addCriterion("f_residence between", value1, value2, "f_residence");
            return (Criteria) this;
        }

        public Criteria andF_residenceNotBetween(String value1, String value2) {
            addCriterion("f_residence not between", value1, value2, "f_residence");
            return (Criteria) this;
        }

        public Criteria andF_educationIsNull() {
            addCriterion("f_education is null");
            return (Criteria) this;
        }

        public Criteria andF_educationIsNotNull() {
            addCriterion("f_education is not null");
            return (Criteria) this;
        }

        public Criteria andF_educationEqualTo(String value) {
            addCriterion("f_education =", value, "f_education");
            return (Criteria) this;
        }

        public Criteria andF_educationNotEqualTo(String value) {
            addCriterion("f_education <>", value, "f_education");
            return (Criteria) this;
        }

        public Criteria andF_educationGreaterThan(String value) {
            addCriterion("f_education >", value, "f_education");
            return (Criteria) this;
        }

        public Criteria andF_educationGreaterThanOrEqualTo(String value) {
            addCriterion("f_education >=", value, "f_education");
            return (Criteria) this;
        }

        public Criteria andF_educationLessThan(String value) {
            addCriterion("f_education <", value, "f_education");
            return (Criteria) this;
        }

        public Criteria andF_educationLessThanOrEqualTo(String value) {
            addCriterion("f_education <=", value, "f_education");
            return (Criteria) this;
        }

        public Criteria andF_educationLike(String value) {
            addCriterion("f_education like", value, "f_education");
            return (Criteria) this;
        }

        public Criteria andF_educationNotLike(String value) {
            addCriterion("f_education not like", value, "f_education");
            return (Criteria) this;
        }

        public Criteria andF_educationIn(List<String> values) {
            addCriterion("f_education in", values, "f_education");
            return (Criteria) this;
        }

        public Criteria andF_educationNotIn(List<String> values) {
            addCriterion("f_education not in", values, "f_education");
            return (Criteria) this;
        }

        public Criteria andF_educationBetween(String value1, String value2) {
            addCriterion("f_education between", value1, value2, "f_education");
            return (Criteria) this;
        }

        public Criteria andF_educationNotBetween(String value1, String value2) {
            addCriterion("f_education not between", value1, value2, "f_education");
            return (Criteria) this;
        }

        public Criteria andF_homephoneIsNull() {
            addCriterion("f_homephone is null");
            return (Criteria) this;
        }

        public Criteria andF_homephoneIsNotNull() {
            addCriterion("f_homephone is not null");
            return (Criteria) this;
        }

        public Criteria andF_homephoneEqualTo(String value) {
            addCriterion("f_homephone =", value, "f_homephone");
            return (Criteria) this;
        }

        public Criteria andF_homephoneNotEqualTo(String value) {
            addCriterion("f_homephone <>", value, "f_homephone");
            return (Criteria) this;
        }

        public Criteria andF_homephoneGreaterThan(String value) {
            addCriterion("f_homephone >", value, "f_homephone");
            return (Criteria) this;
        }

        public Criteria andF_homephoneGreaterThanOrEqualTo(String value) {
            addCriterion("f_homephone >=", value, "f_homephone");
            return (Criteria) this;
        }

        public Criteria andF_homephoneLessThan(String value) {
            addCriterion("f_homephone <", value, "f_homephone");
            return (Criteria) this;
        }

        public Criteria andF_homephoneLessThanOrEqualTo(String value) {
            addCriterion("f_homephone <=", value, "f_homephone");
            return (Criteria) this;
        }

        public Criteria andF_homephoneLike(String value) {
            addCriterion("f_homephone like", value, "f_homephone");
            return (Criteria) this;
        }

        public Criteria andF_homephoneNotLike(String value) {
            addCriterion("f_homephone not like", value, "f_homephone");
            return (Criteria) this;
        }

        public Criteria andF_homephoneIn(List<String> values) {
            addCriterion("f_homephone in", values, "f_homephone");
            return (Criteria) this;
        }

        public Criteria andF_homephoneNotIn(List<String> values) {
            addCriterion("f_homephone not in", values, "f_homephone");
            return (Criteria) this;
        }

        public Criteria andF_homephoneBetween(String value1, String value2) {
            addCriterion("f_homephone between", value1, value2, "f_homephone");
            return (Criteria) this;
        }

        public Criteria andF_homephoneNotBetween(String value1, String value2) {
            addCriterion("f_homephone not between", value1, value2, "f_homephone");
            return (Criteria) this;
        }

        public Criteria andF_technicaltitleIsNull() {
            addCriterion("f_technicaltitle is null");
            return (Criteria) this;
        }

        public Criteria andF_technicaltitleIsNotNull() {
            addCriterion("f_technicaltitle is not null");
            return (Criteria) this;
        }

        public Criteria andF_technicaltitleEqualTo(String value) {
            addCriterion("f_technicaltitle =", value, "f_technicaltitle");
            return (Criteria) this;
        }

        public Criteria andF_technicaltitleNotEqualTo(String value) {
            addCriterion("f_technicaltitle <>", value, "f_technicaltitle");
            return (Criteria) this;
        }

        public Criteria andF_technicaltitleGreaterThan(String value) {
            addCriterion("f_technicaltitle >", value, "f_technicaltitle");
            return (Criteria) this;
        }

        public Criteria andF_technicaltitleGreaterThanOrEqualTo(String value) {
            addCriterion("f_technicaltitle >=", value, "f_technicaltitle");
            return (Criteria) this;
        }

        public Criteria andF_technicaltitleLessThan(String value) {
            addCriterion("f_technicaltitle <", value, "f_technicaltitle");
            return (Criteria) this;
        }

        public Criteria andF_technicaltitleLessThanOrEqualTo(String value) {
            addCriterion("f_technicaltitle <=", value, "f_technicaltitle");
            return (Criteria) this;
        }

        public Criteria andF_technicaltitleLike(String value) {
            addCriterion("f_technicaltitle like", value, "f_technicaltitle");
            return (Criteria) this;
        }

        public Criteria andF_technicaltitleNotLike(String value) {
            addCriterion("f_technicaltitle not like", value, "f_technicaltitle");
            return (Criteria) this;
        }

        public Criteria andF_technicaltitleIn(List<String> values) {
            addCriterion("f_technicaltitle in", values, "f_technicaltitle");
            return (Criteria) this;
        }

        public Criteria andF_technicaltitleNotIn(List<String> values) {
            addCriterion("f_technicaltitle not in", values, "f_technicaltitle");
            return (Criteria) this;
        }

        public Criteria andF_technicaltitleBetween(String value1, String value2) {
            addCriterion("f_technicaltitle between", value1, value2, "f_technicaltitle");
            return (Criteria) this;
        }

        public Criteria andF_technicaltitleNotBetween(String value1, String value2) {
            addCriterion("f_technicaltitle not between", value1, value2, "f_technicaltitle");
            return (Criteria) this;
        }

        public Criteria andF_emailIsNull() {
            addCriterion("f_email is null");
            return (Criteria) this;
        }

        public Criteria andF_emailIsNotNull() {
            addCriterion("f_email is not null");
            return (Criteria) this;
        }

        public Criteria andF_emailEqualTo(String value) {
            addCriterion("f_email =", value, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailNotEqualTo(String value) {
            addCriterion("f_email <>", value, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailGreaterThan(String value) {
            addCriterion("f_email >", value, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailGreaterThanOrEqualTo(String value) {
            addCriterion("f_email >=", value, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailLessThan(String value) {
            addCriterion("f_email <", value, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailLessThanOrEqualTo(String value) {
            addCriterion("f_email <=", value, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailLike(String value) {
            addCriterion("f_email like", value, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailNotLike(String value) {
            addCriterion("f_email not like", value, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailIn(List<String> values) {
            addCriterion("f_email in", values, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailNotIn(List<String> values) {
            addCriterion("f_email not in", values, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailBetween(String value1, String value2) {
            addCriterion("f_email between", value1, value2, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailNotBetween(String value1, String value2) {
            addCriterion("f_email not between", value1, value2, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_unitaddressIsNull() {
            addCriterion("f_unitaddress is null");
            return (Criteria) this;
        }

        public Criteria andF_unitaddressIsNotNull() {
            addCriterion("f_unitaddress is not null");
            return (Criteria) this;
        }

        public Criteria andF_unitaddressEqualTo(String value) {
            addCriterion("f_unitaddress =", value, "f_unitaddress");
            return (Criteria) this;
        }

        public Criteria andF_unitaddressNotEqualTo(String value) {
            addCriterion("f_unitaddress <>", value, "f_unitaddress");
            return (Criteria) this;
        }

        public Criteria andF_unitaddressGreaterThan(String value) {
            addCriterion("f_unitaddress >", value, "f_unitaddress");
            return (Criteria) this;
        }

        public Criteria andF_unitaddressGreaterThanOrEqualTo(String value) {
            addCriterion("f_unitaddress >=", value, "f_unitaddress");
            return (Criteria) this;
        }

        public Criteria andF_unitaddressLessThan(String value) {
            addCriterion("f_unitaddress <", value, "f_unitaddress");
            return (Criteria) this;
        }

        public Criteria andF_unitaddressLessThanOrEqualTo(String value) {
            addCriterion("f_unitaddress <=", value, "f_unitaddress");
            return (Criteria) this;
        }

        public Criteria andF_unitaddressLike(String value) {
            addCriterion("f_unitaddress like", value, "f_unitaddress");
            return (Criteria) this;
        }

        public Criteria andF_unitaddressNotLike(String value) {
            addCriterion("f_unitaddress not like", value, "f_unitaddress");
            return (Criteria) this;
        }

        public Criteria andF_unitaddressIn(List<String> values) {
            addCriterion("f_unitaddress in", values, "f_unitaddress");
            return (Criteria) this;
        }

        public Criteria andF_unitaddressNotIn(List<String> values) {
            addCriterion("f_unitaddress not in", values, "f_unitaddress");
            return (Criteria) this;
        }

        public Criteria andF_unitaddressBetween(String value1, String value2) {
            addCriterion("f_unitaddress between", value1, value2, "f_unitaddress");
            return (Criteria) this;
        }

        public Criteria andF_unitaddressNotBetween(String value1, String value2) {
            addCriterion("f_unitaddress not between", value1, value2, "f_unitaddress");
            return (Criteria) this;
        }

        public Criteria andF_workinglifeIsNull() {
            addCriterion("f_workinglife is null");
            return (Criteria) this;
        }

        public Criteria andF_workinglifeIsNotNull() {
            addCriterion("f_workinglife is not null");
            return (Criteria) this;
        }

        public Criteria andF_workinglifeEqualTo(Integer value) {
            addCriterion("f_workinglife =", value, "f_workinglife");
            return (Criteria) this;
        }

        public Criteria andF_workinglifeNotEqualTo(Integer value) {
            addCriterion("f_workinglife <>", value, "f_workinglife");
            return (Criteria) this;
        }

        public Criteria andF_workinglifeGreaterThan(Integer value) {
            addCriterion("f_workinglife >", value, "f_workinglife");
            return (Criteria) this;
        }

        public Criteria andF_workinglifeGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_workinglife >=", value, "f_workinglife");
            return (Criteria) this;
        }

        public Criteria andF_workinglifeLessThan(Integer value) {
            addCriterion("f_workinglife <", value, "f_workinglife");
            return (Criteria) this;
        }

        public Criteria andF_workinglifeLessThanOrEqualTo(Integer value) {
            addCriterion("f_workinglife <=", value, "f_workinglife");
            return (Criteria) this;
        }

        public Criteria andF_workinglifeIn(List<Integer> values) {
            addCriterion("f_workinglife in", values, "f_workinglife");
            return (Criteria) this;
        }

        public Criteria andF_workinglifeNotIn(List<Integer> values) {
            addCriterion("f_workinglife not in", values, "f_workinglife");
            return (Criteria) this;
        }

        public Criteria andF_workinglifeBetween(Integer value1, Integer value2) {
            addCriterion("f_workinglife between", value1, value2, "f_workinglife");
            return (Criteria) this;
        }

        public Criteria andF_workinglifeNotBetween(Integer value1, Integer value2) {
            addCriterion("f_workinglife not between", value1, value2, "f_workinglife");
            return (Criteria) this;
        }

        public Criteria andF_unitpropertiesIsNull() {
            addCriterion("f_unitproperties is null");
            return (Criteria) this;
        }

        public Criteria andF_unitpropertiesIsNotNull() {
            addCriterion("f_unitproperties is not null");
            return (Criteria) this;
        }

        public Criteria andF_unitpropertiesEqualTo(String value) {
            addCriterion("f_unitproperties =", value, "f_unitproperties");
            return (Criteria) this;
        }

        public Criteria andF_unitpropertiesNotEqualTo(String value) {
            addCriterion("f_unitproperties <>", value, "f_unitproperties");
            return (Criteria) this;
        }

        public Criteria andF_unitpropertiesGreaterThan(String value) {
            addCriterion("f_unitproperties >", value, "f_unitproperties");
            return (Criteria) this;
        }

        public Criteria andF_unitpropertiesGreaterThanOrEqualTo(String value) {
            addCriterion("f_unitproperties >=", value, "f_unitproperties");
            return (Criteria) this;
        }

        public Criteria andF_unitpropertiesLessThan(String value) {
            addCriterion("f_unitproperties <", value, "f_unitproperties");
            return (Criteria) this;
        }

        public Criteria andF_unitpropertiesLessThanOrEqualTo(String value) {
            addCriterion("f_unitproperties <=", value, "f_unitproperties");
            return (Criteria) this;
        }

        public Criteria andF_unitpropertiesLike(String value) {
            addCriterion("f_unitproperties like", value, "f_unitproperties");
            return (Criteria) this;
        }

        public Criteria andF_unitpropertiesNotLike(String value) {
            addCriterion("f_unitproperties not like", value, "f_unitproperties");
            return (Criteria) this;
        }

        public Criteria andF_unitpropertiesIn(List<String> values) {
            addCriterion("f_unitproperties in", values, "f_unitproperties");
            return (Criteria) this;
        }

        public Criteria andF_unitpropertiesNotIn(List<String> values) {
            addCriterion("f_unitproperties not in", values, "f_unitproperties");
            return (Criteria) this;
        }

        public Criteria andF_unitpropertiesBetween(String value1, String value2) {
            addCriterion("f_unitproperties between", value1, value2, "f_unitproperties");
            return (Criteria) this;
        }

        public Criteria andF_unitpropertiesNotBetween(String value1, String value2) {
            addCriterion("f_unitproperties not between", value1, value2, "f_unitproperties");
            return (Criteria) this;
        }

        public Criteria andF_systemIsNull() {
            addCriterion("f_system is null");
            return (Criteria) this;
        }

        public Criteria andF_systemIsNotNull() {
            addCriterion("f_system is not null");
            return (Criteria) this;
        }

        public Criteria andF_systemEqualTo(String value) {
            addCriterion("f_system =", value, "f_system");
            return (Criteria) this;
        }

        public Criteria andF_systemNotEqualTo(String value) {
            addCriterion("f_system <>", value, "f_system");
            return (Criteria) this;
        }

        public Criteria andF_systemGreaterThan(String value) {
            addCriterion("f_system >", value, "f_system");
            return (Criteria) this;
        }

        public Criteria andF_systemGreaterThanOrEqualTo(String value) {
            addCriterion("f_system >=", value, "f_system");
            return (Criteria) this;
        }

        public Criteria andF_systemLessThan(String value) {
            addCriterion("f_system <", value, "f_system");
            return (Criteria) this;
        }

        public Criteria andF_systemLessThanOrEqualTo(String value) {
            addCriterion("f_system <=", value, "f_system");
            return (Criteria) this;
        }

        public Criteria andF_systemLike(String value) {
            addCriterion("f_system like", value, "f_system");
            return (Criteria) this;
        }

        public Criteria andF_systemNotLike(String value) {
            addCriterion("f_system not like", value, "f_system");
            return (Criteria) this;
        }

        public Criteria andF_systemIn(List<String> values) {
            addCriterion("f_system in", values, "f_system");
            return (Criteria) this;
        }

        public Criteria andF_systemNotIn(List<String> values) {
            addCriterion("f_system not in", values, "f_system");
            return (Criteria) this;
        }

        public Criteria andF_systemBetween(String value1, String value2) {
            addCriterion("f_system between", value1, value2, "f_system");
            return (Criteria) this;
        }

        public Criteria andF_systemNotBetween(String value1, String value2) {
            addCriterion("f_system not between", value1, value2, "f_system");
            return (Criteria) this;
        }

        public Criteria andF_sourceIsNull() {
            addCriterion("f_source is null");
            return (Criteria) this;
        }

        public Criteria andF_sourceIsNotNull() {
            addCriterion("f_source is not null");
            return (Criteria) this;
        }

        public Criteria andF_sourceEqualTo(String value) {
            addCriterion("f_source =", value, "f_source");
            return (Criteria) this;
        }

        public Criteria andF_sourceNotEqualTo(String value) {
            addCriterion("f_source <>", value, "f_source");
            return (Criteria) this;
        }

        public Criteria andF_sourceGreaterThan(String value) {
            addCriterion("f_source >", value, "f_source");
            return (Criteria) this;
        }

        public Criteria andF_sourceGreaterThanOrEqualTo(String value) {
            addCriterion("f_source >=", value, "f_source");
            return (Criteria) this;
        }

        public Criteria andF_sourceLessThan(String value) {
            addCriterion("f_source <", value, "f_source");
            return (Criteria) this;
        }

        public Criteria andF_sourceLessThanOrEqualTo(String value) {
            addCriterion("f_source <=", value, "f_source");
            return (Criteria) this;
        }

        public Criteria andF_sourceLike(String value) {
            addCriterion("f_source like", value, "f_source");
            return (Criteria) this;
        }

        public Criteria andF_sourceNotLike(String value) {
            addCriterion("f_source not like", value, "f_source");
            return (Criteria) this;
        }

        public Criteria andF_sourceIn(List<String> values) {
            addCriterion("f_source in", values, "f_source");
            return (Criteria) this;
        }

        public Criteria andF_sourceNotIn(List<String> values) {
            addCriterion("f_source not in", values, "f_source");
            return (Criteria) this;
        }

        public Criteria andF_sourceBetween(String value1, String value2) {
            addCriterion("f_source between", value1, value2, "f_source");
            return (Criteria) this;
        }

        public Criteria andF_sourceNotBetween(String value1, String value2) {
            addCriterion("f_source not between", value1, value2, "f_source");
            return (Criteria) this;
        }

        public Criteria andF_statusIsNull() {
            addCriterion("f_status is null");
            return (Criteria) this;
        }

        public Criteria andF_statusIsNotNull() {
            addCriterion("f_status is not null");
            return (Criteria) this;
        }

        public Criteria andF_statusEqualTo(Integer value) {
            addCriterion("f_status =", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotEqualTo(Integer value) {
            addCriterion("f_status <>", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusGreaterThan(Integer value) {
            addCriterion("f_status >", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_status >=", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusLessThan(Integer value) {
            addCriterion("f_status <", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusLessThanOrEqualTo(Integer value) {
            addCriterion("f_status <=", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusIn(List<Integer> values) {
            addCriterion("f_status in", values, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotIn(List<Integer> values) {
            addCriterion("f_status not in", values, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusBetween(Integer value1, Integer value2) {
            addCriterion("f_status between", value1, value2, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotBetween(Integer value1, Integer value2) {
            addCriterion("f_status not between", value1, value2, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_descIsNull() {
            addCriterion("f_desc is null");
            return (Criteria) this;
        }

        public Criteria andF_descIsNotNull() {
            addCriterion("f_desc is not null");
            return (Criteria) this;
        }

        public Criteria andF_descEqualTo(String value) {
            addCriterion("f_desc =", value, "f_desc");
            return (Criteria) this;
        }

        public Criteria andF_descNotEqualTo(String value) {
            addCriterion("f_desc <>", value, "f_desc");
            return (Criteria) this;
        }

        public Criteria andF_descGreaterThan(String value) {
            addCriterion("f_desc >", value, "f_desc");
            return (Criteria) this;
        }

        public Criteria andF_descGreaterThanOrEqualTo(String value) {
            addCriterion("f_desc >=", value, "f_desc");
            return (Criteria) this;
        }

        public Criteria andF_descLessThan(String value) {
            addCriterion("f_desc <", value, "f_desc");
            return (Criteria) this;
        }

        public Criteria andF_descLessThanOrEqualTo(String value) {
            addCriterion("f_desc <=", value, "f_desc");
            return (Criteria) this;
        }

        public Criteria andF_descLike(String value) {
            addCriterion("f_desc like", value, "f_desc");
            return (Criteria) this;
        }

        public Criteria andF_descNotLike(String value) {
            addCriterion("f_desc not like", value, "f_desc");
            return (Criteria) this;
        }

        public Criteria andF_descIn(List<String> values) {
            addCriterion("f_desc in", values, "f_desc");
            return (Criteria) this;
        }

        public Criteria andF_descNotIn(List<String> values) {
            addCriterion("f_desc not in", values, "f_desc");
            return (Criteria) this;
        }

        public Criteria andF_descBetween(String value1, String value2) {
            addCriterion("f_desc between", value1, value2, "f_desc");
            return (Criteria) this;
        }

        public Criteria andF_descNotBetween(String value1, String value2) {
            addCriterion("f_desc not between", value1, value2, "f_desc");
            return (Criteria) this;
        }

        public Criteria andF_genreIsNull() {
            addCriterion("f_genre is null");
            return (Criteria) this;
        }

        public Criteria andF_genreIsNotNull() {
            addCriterion("f_genre is not null");
            return (Criteria) this;
        }

        public Criteria andF_genreEqualTo(String value) {
            addCriterion("f_genre =", value, "f_genre");
            return (Criteria) this;
        }

        public Criteria andF_genreNotEqualTo(String value) {
            addCriterion("f_genre <>", value, "f_genre");
            return (Criteria) this;
        }

        public Criteria andF_genreGreaterThan(String value) {
            addCriterion("f_genre >", value, "f_genre");
            return (Criteria) this;
        }

        public Criteria andF_genreGreaterThanOrEqualTo(String value) {
            addCriterion("f_genre >=", value, "f_genre");
            return (Criteria) this;
        }

        public Criteria andF_genreLessThan(String value) {
            addCriterion("f_genre <", value, "f_genre");
            return (Criteria) this;
        }

        public Criteria andF_genreLessThanOrEqualTo(String value) {
            addCriterion("f_genre <=", value, "f_genre");
            return (Criteria) this;
        }

        public Criteria andF_genreLike(String value) {
            addCriterion("f_genre like", value, "f_genre");
            return (Criteria) this;
        }

        public Criteria andF_genreNotLike(String value) {
            addCriterion("f_genre not like", value, "f_genre");
            return (Criteria) this;
        }

        public Criteria andF_genreIn(List<String> values) {
            addCriterion("f_genre in", values, "f_genre");
            return (Criteria) this;
        }

        public Criteria andF_genreNotIn(List<String> values) {
            addCriterion("f_genre not in", values, "f_genre");
            return (Criteria) this;
        }

        public Criteria andF_genreBetween(String value1, String value2) {
            addCriterion("f_genre between", value1, value2, "f_genre");
            return (Criteria) this;
        }

        public Criteria andF_genreNotBetween(String value1, String value2) {
            addCriterion("f_genre not between", value1, value2, "f_genre");
            return (Criteria) this;
        }

        public Criteria andF_createidIsNull() {
            addCriterion("f_createid is null");
            return (Criteria) this;
        }

        public Criteria andF_createidIsNotNull() {
            addCriterion("f_createid is not null");
            return (Criteria) this;
        }

        public Criteria andF_createidEqualTo(String value) {
            addCriterion("f_createid =", value, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidNotEqualTo(String value) {
            addCriterion("f_createid <>", value, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidGreaterThan(String value) {
            addCriterion("f_createid >", value, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidGreaterThanOrEqualTo(String value) {
            addCriterion("f_createid >=", value, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidLessThan(String value) {
            addCriterion("f_createid <", value, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidLessThanOrEqualTo(String value) {
            addCriterion("f_createid <=", value, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidLike(String value) {
            addCriterion("f_createid like", value, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidNotLike(String value) {
            addCriterion("f_createid not like", value, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidIn(List<String> values) {
            addCriterion("f_createid in", values, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidNotIn(List<String> values) {
            addCriterion("f_createid not in", values, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidBetween(String value1, String value2) {
            addCriterion("f_createid between", value1, value2, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidNotBetween(String value1, String value2) {
            addCriterion("f_createid not between", value1, value2, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_creatorIsNull() {
            addCriterion("f_creator is null");
            return (Criteria) this;
        }

        public Criteria andF_creatorIsNotNull() {
            addCriterion("f_creator is not null");
            return (Criteria) this;
        }

        public Criteria andF_creatorEqualTo(String value) {
            addCriterion("f_creator =", value, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorNotEqualTo(String value) {
            addCriterion("f_creator <>", value, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorGreaterThan(String value) {
            addCriterion("f_creator >", value, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorGreaterThanOrEqualTo(String value) {
            addCriterion("f_creator >=", value, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorLessThan(String value) {
            addCriterion("f_creator <", value, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorLessThanOrEqualTo(String value) {
            addCriterion("f_creator <=", value, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorLike(String value) {
            addCriterion("f_creator like", value, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorNotLike(String value) {
            addCriterion("f_creator not like", value, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorIn(List<String> values) {
            addCriterion("f_creator in", values, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorNotIn(List<String> values) {
            addCriterion("f_creator not in", values, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorBetween(String value1, String value2) {
            addCriterion("f_creator between", value1, value2, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorNotBetween(String value1, String value2) {
            addCriterion("f_creator not between", value1, value2, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_editoridIsNull() {
            addCriterion("f_editorid is null");
            return (Criteria) this;
        }

        public Criteria andF_editoridIsNotNull() {
            addCriterion("f_editorid is not null");
            return (Criteria) this;
        }

        public Criteria andF_editoridEqualTo(String value) {
            addCriterion("f_editorid =", value, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridNotEqualTo(String value) {
            addCriterion("f_editorid <>", value, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridGreaterThan(String value) {
            addCriterion("f_editorid >", value, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridGreaterThanOrEqualTo(String value) {
            addCriterion("f_editorid >=", value, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridLessThan(String value) {
            addCriterion("f_editorid <", value, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridLessThanOrEqualTo(String value) {
            addCriterion("f_editorid <=", value, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridLike(String value) {
            addCriterion("f_editorid like", value, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridNotLike(String value) {
            addCriterion("f_editorid not like", value, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridIn(List<String> values) {
            addCriterion("f_editorid in", values, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridNotIn(List<String> values) {
            addCriterion("f_editorid not in", values, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridBetween(String value1, String value2) {
            addCriterion("f_editorid between", value1, value2, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridNotBetween(String value1, String value2) {
            addCriterion("f_editorid not between", value1, value2, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editorIsNull() {
            addCriterion("f_editor is null");
            return (Criteria) this;
        }

        public Criteria andF_editorIsNotNull() {
            addCriterion("f_editor is not null");
            return (Criteria) this;
        }

        public Criteria andF_editorEqualTo(String value) {
            addCriterion("f_editor =", value, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorNotEqualTo(String value) {
            addCriterion("f_editor <>", value, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorGreaterThan(String value) {
            addCriterion("f_editor >", value, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorGreaterThanOrEqualTo(String value) {
            addCriterion("f_editor >=", value, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorLessThan(String value) {
            addCriterion("f_editor <", value, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorLessThanOrEqualTo(String value) {
            addCriterion("f_editor <=", value, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorLike(String value) {
            addCriterion("f_editor like", value, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorNotLike(String value) {
            addCriterion("f_editor not like", value, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorIn(List<String> values) {
            addCriterion("f_editor in", values, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorNotIn(List<String> values) {
            addCriterion("f_editor not in", values, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorBetween(String value1, String value2) {
            addCriterion("f_editor between", value1, value2, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorNotBetween(String value1, String value2) {
            addCriterion("f_editor not between", value1, value2, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_initdateIsNull() {
            addCriterion("f_initdate is null");
            return (Criteria) this;
        }

        public Criteria andF_initdateIsNotNull() {
            addCriterion("f_initdate is not null");
            return (Criteria) this;
        }

        public Criteria andF_initdateEqualTo(Integer value) {
            addCriterion("f_initdate =", value, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateNotEqualTo(Integer value) {
            addCriterion("f_initdate <>", value, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateGreaterThan(Integer value) {
            addCriterion("f_initdate >", value, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_initdate >=", value, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateLessThan(Integer value) {
            addCriterion("f_initdate <", value, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateLessThanOrEqualTo(Integer value) {
            addCriterion("f_initdate <=", value, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateIn(List<Integer> values) {
            addCriterion("f_initdate in", values, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateNotIn(List<Integer> values) {
            addCriterion("f_initdate not in", values, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateBetween(Integer value1, Integer value2) {
            addCriterion("f_initdate between", value1, value2, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateNotBetween(Integer value1, Integer value2) {
            addCriterion("f_initdate not between", value1, value2, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateIsNull() {
            addCriterion("f_updatedate is null");
            return (Criteria) this;
        }

        public Criteria andF_updatedateIsNotNull() {
            addCriterion("f_updatedate is not null");
            return (Criteria) this;
        }

        public Criteria andF_updatedateEqualTo(Integer value) {
            addCriterion("f_updatedate =", value, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateNotEqualTo(Integer value) {
            addCriterion("f_updatedate <>", value, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateGreaterThan(Integer value) {
            addCriterion("f_updatedate >", value, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_updatedate >=", value, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateLessThan(Integer value) {
            addCriterion("f_updatedate <", value, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateLessThanOrEqualTo(Integer value) {
            addCriterion("f_updatedate <=", value, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateIn(List<Integer> values) {
            addCriterion("f_updatedate in", values, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateNotIn(List<Integer> values) {
            addCriterion("f_updatedate not in", values, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateBetween(Integer value1, Integer value2) {
            addCriterion("f_updatedate between", value1, value2, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateNotBetween(Integer value1, Integer value2) {
            addCriterion("f_updatedate not between", value1, value2, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_sysmidIsNull() {
            addCriterion("f_sysmid is null");
            return (Criteria) this;
        }

        public Criteria andF_sysmidIsNotNull() {
            addCriterion("f_sysmid is not null");
            return (Criteria) this;
        }

        public Criteria andF_sysmidEqualTo(Long value) {
            addCriterion("f_sysmid =", value, "f_sysmid");
            return (Criteria) this;
        }

        public Criteria andF_sysmidNotEqualTo(Long value) {
            addCriterion("f_sysmid <>", value, "f_sysmid");
            return (Criteria) this;
        }

        public Criteria andF_sysmidGreaterThan(Long value) {
            addCriterion("f_sysmid >", value, "f_sysmid");
            return (Criteria) this;
        }

        public Criteria andF_sysmidGreaterThanOrEqualTo(Long value) {
            addCriterion("f_sysmid >=", value, "f_sysmid");
            return (Criteria) this;
        }

        public Criteria andF_sysmidLessThan(Long value) {
            addCriterion("f_sysmid <", value, "f_sysmid");
            return (Criteria) this;
        }

        public Criteria andF_sysmidLessThanOrEqualTo(Long value) {
            addCriterion("f_sysmid <=", value, "f_sysmid");
            return (Criteria) this;
        }

        public Criteria andF_sysmidIn(List<Long> values) {
            addCriterion("f_sysmid in", values, "f_sysmid");
            return (Criteria) this;
        }

        public Criteria andF_sysmidNotIn(List<Long> values) {
            addCriterion("f_sysmid not in", values, "f_sysmid");
            return (Criteria) this;
        }

        public Criteria andF_sysmidBetween(Long value1, Long value2) {
            addCriterion("f_sysmid between", value1, value2, "f_sysmid");
            return (Criteria) this;
        }

        public Criteria andF_sysmidNotBetween(Long value1, Long value2) {
            addCriterion("f_sysmid not between", value1, value2, "f_sysmid");
            return (Criteria) this;
        }

        public Criteria andF_qqIsNull() {
            addCriterion("f_qq is null");
            return (Criteria) this;
        }

        public Criteria andF_qqIsNotNull() {
            addCriterion("f_qq is not null");
            return (Criteria) this;
        }

        public Criteria andF_qqEqualTo(String value) {
            addCriterion("f_qq =", value, "f_qq");
            return (Criteria) this;
        }

        public Criteria andF_qqNotEqualTo(String value) {
            addCriterion("f_qq <>", value, "f_qq");
            return (Criteria) this;
        }

        public Criteria andF_qqGreaterThan(String value) {
            addCriterion("f_qq >", value, "f_qq");
            return (Criteria) this;
        }

        public Criteria andF_qqGreaterThanOrEqualTo(String value) {
            addCriterion("f_qq >=", value, "f_qq");
            return (Criteria) this;
        }

        public Criteria andF_qqLessThan(String value) {
            addCriterion("f_qq <", value, "f_qq");
            return (Criteria) this;
        }

        public Criteria andF_qqLessThanOrEqualTo(String value) {
            addCriterion("f_qq <=", value, "f_qq");
            return (Criteria) this;
        }

        public Criteria andF_qqLike(String value) {
            addCriterion("f_qq like", value, "f_qq");
            return (Criteria) this;
        }

        public Criteria andF_qqNotLike(String value) {
            addCriterion("f_qq not like", value, "f_qq");
            return (Criteria) this;
        }

        public Criteria andF_qqIn(List<String> values) {
            addCriterion("f_qq in", values, "f_qq");
            return (Criteria) this;
        }

        public Criteria andF_qqNotIn(List<String> values) {
            addCriterion("f_qq not in", values, "f_qq");
            return (Criteria) this;
        }

        public Criteria andF_qqBetween(String value1, String value2) {
            addCriterion("f_qq between", value1, value2, "f_qq");
            return (Criteria) this;
        }

        public Criteria andF_qqNotBetween(String value1, String value2) {
            addCriterion("f_qq not between", value1, value2, "f_qq");
            return (Criteria) this;
        }

        public Criteria andF_weixinIsNull() {
            addCriterion("f_weixin is null");
            return (Criteria) this;
        }

        public Criteria andF_weixinIsNotNull() {
            addCriterion("f_weixin is not null");
            return (Criteria) this;
        }

        public Criteria andF_weixinEqualTo(String value) {
            addCriterion("f_weixin =", value, "f_weixin");
            return (Criteria) this;
        }

        public Criteria andF_weixinNotEqualTo(String value) {
            addCriterion("f_weixin <>", value, "f_weixin");
            return (Criteria) this;
        }

        public Criteria andF_weixinGreaterThan(String value) {
            addCriterion("f_weixin >", value, "f_weixin");
            return (Criteria) this;
        }

        public Criteria andF_weixinGreaterThanOrEqualTo(String value) {
            addCriterion("f_weixin >=", value, "f_weixin");
            return (Criteria) this;
        }

        public Criteria andF_weixinLessThan(String value) {
            addCriterion("f_weixin <", value, "f_weixin");
            return (Criteria) this;
        }

        public Criteria andF_weixinLessThanOrEqualTo(String value) {
            addCriterion("f_weixin <=", value, "f_weixin");
            return (Criteria) this;
        }

        public Criteria andF_weixinLike(String value) {
            addCriterion("f_weixin like", value, "f_weixin");
            return (Criteria) this;
        }

        public Criteria andF_weixinNotLike(String value) {
            addCriterion("f_weixin not like", value, "f_weixin");
            return (Criteria) this;
        }

        public Criteria andF_weixinIn(List<String> values) {
            addCriterion("f_weixin in", values, "f_weixin");
            return (Criteria) this;
        }

        public Criteria andF_weixinNotIn(List<String> values) {
            addCriterion("f_weixin not in", values, "f_weixin");
            return (Criteria) this;
        }

        public Criteria andF_weixinBetween(String value1, String value2) {
            addCriterion("f_weixin between", value1, value2, "f_weixin");
            return (Criteria) this;
        }

        public Criteria andF_weixinNotBetween(String value1, String value2) {
            addCriterion("f_weixin not between", value1, value2, "f_weixin");
            return (Criteria) this;
        }

        public Criteria andF_midIsNull() {
            addCriterion("f_mid is null");
            return (Criteria) this;
        }

        public Criteria andF_midIsNotNull() {
            addCriterion("f_mid is not null");
            return (Criteria) this;
        }

        public Criteria andF_midEqualTo(Integer value) {
            addCriterion("f_mid =", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midNotEqualTo(Integer value) {
            addCriterion("f_mid <>", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midGreaterThan(Integer value) {
            addCriterion("f_mid >", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_mid >=", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midLessThan(Integer value) {
            addCriterion("f_mid <", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midLessThanOrEqualTo(Integer value) {
            addCriterion("f_mid <=", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midIn(List<Integer> values) {
            addCriterion("f_mid in", values, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midNotIn(List<Integer> values) {
            addCriterion("f_mid not in", values, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midBetween(Integer value1, Integer value2) {
            addCriterion("f_mid between", value1, value2, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midNotBetween(Integer value1, Integer value2) {
            addCriterion("f_mid not between", value1, value2, "f_mid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated do_not_delete_during_merge Sat May 23 10:55:57 CST 2015
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cm_custinfo
     *
     * @mbggenerated Sat May 23 10:55:57 CST 2015
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}