package com.etong.pt.data.session;

import java.io.Serializable;

public class PtSession implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_um_session.f_msid
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    private Long f_msid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_um_session.f_onlineip
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    private String f_onlineip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_um_session.f_mid
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    private Integer f_mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_um_session.f_errtimes
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    private Integer f_errtimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_um_session.f_verifycode
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    private String f_verifycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_um_session.f_verifytime
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    private Integer f_verifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_um_session.f_jwkjson
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    private String f_jwkjson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_um_session.f_createtime
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    private Integer f_createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_um_session.f_phone
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    private String f_phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_um_session.f_clienttype
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    private Integer f_clienttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_um_session.f_stid
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    private String f_stid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_um_session.f_msid
     *
     * @return the value of t_um_session.f_msid
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public Long getF_msid() {
        return f_msid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_um_session.f_msid
     *
     * @param f_msid the value for t_um_session.f_msid
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public void setF_msid(Long f_msid) {
        this.f_msid = f_msid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_um_session.f_onlineip
     *
     * @return the value of t_um_session.f_onlineip
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public String getF_onlineip() {
        return f_onlineip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_um_session.f_onlineip
     *
     * @param f_onlineip the value for t_um_session.f_onlineip
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public void setF_onlineip(String f_onlineip) {
        this.f_onlineip = f_onlineip == null ? null : f_onlineip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_um_session.f_mid
     *
     * @return the value of t_um_session.f_mid
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public Integer getF_mid() {
        return f_mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_um_session.f_mid
     *
     * @param f_mid the value for t_um_session.f_mid
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public void setF_mid(Integer f_mid) {
        this.f_mid = f_mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_um_session.f_errtimes
     *
     * @return the value of t_um_session.f_errtimes
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public Integer getF_errtimes() {
        return f_errtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_um_session.f_errtimes
     *
     * @param f_errtimes the value for t_um_session.f_errtimes
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public void setF_errtimes(Integer f_errtimes) {
        this.f_errtimes = f_errtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_um_session.f_verifycode
     *
     * @return the value of t_um_session.f_verifycode
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public String getF_verifycode() {
        return f_verifycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_um_session.f_verifycode
     *
     * @param f_verifycode the value for t_um_session.f_verifycode
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public void setF_verifycode(String f_verifycode) {
        this.f_verifycode = f_verifycode == null ? null : f_verifycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_um_session.f_verifytime
     *
     * @return the value of t_um_session.f_verifytime
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public Integer getF_verifytime() {
        return f_verifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_um_session.f_verifytime
     *
     * @param f_verifytime the value for t_um_session.f_verifytime
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public void setF_verifytime(Integer f_verifytime) {
        this.f_verifytime = f_verifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_um_session.f_jwkjson
     *
     * @return the value of t_um_session.f_jwkjson
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public String getF_jwkjson() {
        return f_jwkjson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_um_session.f_jwkjson
     *
     * @param f_jwkjson the value for t_um_session.f_jwkjson
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public void setF_jwkjson(String f_jwkjson) {
        this.f_jwkjson = f_jwkjson == null ? null : f_jwkjson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_um_session.f_createtime
     *
     * @return the value of t_um_session.f_createtime
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public Integer getF_createtime() {
        return f_createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_um_session.f_createtime
     *
     * @param f_createtime the value for t_um_session.f_createtime
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public void setF_createtime(Integer f_createtime) {
        this.f_createtime = f_createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_um_session.f_phone
     *
     * @return the value of t_um_session.f_phone
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public String getF_phone() {
        return f_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_um_session.f_phone
     *
     * @param f_phone the value for t_um_session.f_phone
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public void setF_phone(String f_phone) {
        this.f_phone = f_phone == null ? null : f_phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_um_session.f_clienttype
     *
     * @return the value of t_um_session.f_clienttype
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public Integer getF_clienttype() {
        return f_clienttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_um_session.f_clienttype
     *
     * @param f_clienttype the value for t_um_session.f_clienttype
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public void setF_clienttype(Integer f_clienttype) {
        this.f_clienttype = f_clienttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_um_session.f_stid
     *
     * @return the value of t_um_session.f_stid
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public String getF_stid() {
        return f_stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_um_session.f_stid
     *
     * @param f_stid the value for t_um_session.f_stid
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public void setF_stid(String f_stid) {
        this.f_stid = f_stid == null ? null : f_stid.trim();
    }
}