package com.etong.pt.data.session;

import com.etong.pt.data.session.PtSession;
import com.etong.pt.data.session.PtSessionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PtSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    int countByExample(PtSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    int deleteByExample(PtSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    int deleteByPrimaryKey(Long f_msid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    int insert(PtSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    int insertSelective(PtSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    List<PtSession> selectByExample(PtSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    PtSession selectByPrimaryKey(Long f_msid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    int updateByExampleSelective(@Param("record") PtSession record, @Param("example") PtSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    int updateByExample(@Param("record") PtSession record, @Param("example") PtSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    int updateByPrimaryKeySelective(PtSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    int updateByPrimaryKey(PtSession record);
}