package com.etong.pt.data.session;

import java.util.ArrayList;
import java.util.List;

public class PtSessionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public PtSessionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andF_msidIsNull() {
            addCriterion("f_msid is null");
            return (Criteria) this;
        }

        public Criteria andF_msidIsNotNull() {
            addCriterion("f_msid is not null");
            return (Criteria) this;
        }

        public Criteria andF_msidEqualTo(Long value) {
            addCriterion("f_msid =", value, "f_msid");
            return (Criteria) this;
        }

        public Criteria andF_msidNotEqualTo(Long value) {
            addCriterion("f_msid <>", value, "f_msid");
            return (Criteria) this;
        }

        public Criteria andF_msidGreaterThan(Long value) {
            addCriterion("f_msid >", value, "f_msid");
            return (Criteria) this;
        }

        public Criteria andF_msidGreaterThanOrEqualTo(Long value) {
            addCriterion("f_msid >=", value, "f_msid");
            return (Criteria) this;
        }

        public Criteria andF_msidLessThan(Long value) {
            addCriterion("f_msid <", value, "f_msid");
            return (Criteria) this;
        }

        public Criteria andF_msidLessThanOrEqualTo(Long value) {
            addCriterion("f_msid <=", value, "f_msid");
            return (Criteria) this;
        }

        public Criteria andF_msidIn(List<Long> values) {
            addCriterion("f_msid in", values, "f_msid");
            return (Criteria) this;
        }

        public Criteria andF_msidNotIn(List<Long> values) {
            addCriterion("f_msid not in", values, "f_msid");
            return (Criteria) this;
        }

        public Criteria andF_msidBetween(Long value1, Long value2) {
            addCriterion("f_msid between", value1, value2, "f_msid");
            return (Criteria) this;
        }

        public Criteria andF_msidNotBetween(Long value1, Long value2) {
            addCriterion("f_msid not between", value1, value2, "f_msid");
            return (Criteria) this;
        }

        public Criteria andF_onlineipIsNull() {
            addCriterion("f_onlineip is null");
            return (Criteria) this;
        }

        public Criteria andF_onlineipIsNotNull() {
            addCriterion("f_onlineip is not null");
            return (Criteria) this;
        }

        public Criteria andF_onlineipEqualTo(String value) {
            addCriterion("f_onlineip =", value, "f_onlineip");
            return (Criteria) this;
        }

        public Criteria andF_onlineipNotEqualTo(String value) {
            addCriterion("f_onlineip <>", value, "f_onlineip");
            return (Criteria) this;
        }

        public Criteria andF_onlineipGreaterThan(String value) {
            addCriterion("f_onlineip >", value, "f_onlineip");
            return (Criteria) this;
        }

        public Criteria andF_onlineipGreaterThanOrEqualTo(String value) {
            addCriterion("f_onlineip >=", value, "f_onlineip");
            return (Criteria) this;
        }

        public Criteria andF_onlineipLessThan(String value) {
            addCriterion("f_onlineip <", value, "f_onlineip");
            return (Criteria) this;
        }

        public Criteria andF_onlineipLessThanOrEqualTo(String value) {
            addCriterion("f_onlineip <=", value, "f_onlineip");
            return (Criteria) this;
        }

        public Criteria andF_onlineipLike(String value) {
            addCriterion("f_onlineip like", value, "f_onlineip");
            return (Criteria) this;
        }

        public Criteria andF_onlineipNotLike(String value) {
            addCriterion("f_onlineip not like", value, "f_onlineip");
            return (Criteria) this;
        }

        public Criteria andF_onlineipIn(List<String> values) {
            addCriterion("f_onlineip in", values, "f_onlineip");
            return (Criteria) this;
        }

        public Criteria andF_onlineipNotIn(List<String> values) {
            addCriterion("f_onlineip not in", values, "f_onlineip");
            return (Criteria) this;
        }

        public Criteria andF_onlineipBetween(String value1, String value2) {
            addCriterion("f_onlineip between", value1, value2, "f_onlineip");
            return (Criteria) this;
        }

        public Criteria andF_onlineipNotBetween(String value1, String value2) {
            addCriterion("f_onlineip not between", value1, value2, "f_onlineip");
            return (Criteria) this;
        }

        public Criteria andF_midIsNull() {
            addCriterion("f_mid is null");
            return (Criteria) this;
        }

        public Criteria andF_midIsNotNull() {
            addCriterion("f_mid is not null");
            return (Criteria) this;
        }

        public Criteria andF_midEqualTo(Integer value) {
            addCriterion("f_mid =", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midNotEqualTo(Integer value) {
            addCriterion("f_mid <>", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midGreaterThan(Integer value) {
            addCriterion("f_mid >", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_mid >=", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midLessThan(Integer value) {
            addCriterion("f_mid <", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midLessThanOrEqualTo(Integer value) {
            addCriterion("f_mid <=", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midIn(List<Integer> values) {
            addCriterion("f_mid in", values, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midNotIn(List<Integer> values) {
            addCriterion("f_mid not in", values, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midBetween(Integer value1, Integer value2) {
            addCriterion("f_mid between", value1, value2, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midNotBetween(Integer value1, Integer value2) {
            addCriterion("f_mid not between", value1, value2, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_errtimesIsNull() {
            addCriterion("f_errtimes is null");
            return (Criteria) this;
        }

        public Criteria andF_errtimesIsNotNull() {
            addCriterion("f_errtimes is not null");
            return (Criteria) this;
        }

        public Criteria andF_errtimesEqualTo(Integer value) {
            addCriterion("f_errtimes =", value, "f_errtimes");
            return (Criteria) this;
        }

        public Criteria andF_errtimesNotEqualTo(Integer value) {
            addCriterion("f_errtimes <>", value, "f_errtimes");
            return (Criteria) this;
        }

        public Criteria andF_errtimesGreaterThan(Integer value) {
            addCriterion("f_errtimes >", value, "f_errtimes");
            return (Criteria) this;
        }

        public Criteria andF_errtimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_errtimes >=", value, "f_errtimes");
            return (Criteria) this;
        }

        public Criteria andF_errtimesLessThan(Integer value) {
            addCriterion("f_errtimes <", value, "f_errtimes");
            return (Criteria) this;
        }

        public Criteria andF_errtimesLessThanOrEqualTo(Integer value) {
            addCriterion("f_errtimes <=", value, "f_errtimes");
            return (Criteria) this;
        }

        public Criteria andF_errtimesIn(List<Integer> values) {
            addCriterion("f_errtimes in", values, "f_errtimes");
            return (Criteria) this;
        }

        public Criteria andF_errtimesNotIn(List<Integer> values) {
            addCriterion("f_errtimes not in", values, "f_errtimes");
            return (Criteria) this;
        }

        public Criteria andF_errtimesBetween(Integer value1, Integer value2) {
            addCriterion("f_errtimes between", value1, value2, "f_errtimes");
            return (Criteria) this;
        }

        public Criteria andF_errtimesNotBetween(Integer value1, Integer value2) {
            addCriterion("f_errtimes not between", value1, value2, "f_errtimes");
            return (Criteria) this;
        }

        public Criteria andF_verifycodeIsNull() {
            addCriterion("f_verifycode is null");
            return (Criteria) this;
        }

        public Criteria andF_verifycodeIsNotNull() {
            addCriterion("f_verifycode is not null");
            return (Criteria) this;
        }

        public Criteria andF_verifycodeEqualTo(String value) {
            addCriterion("f_verifycode =", value, "f_verifycode");
            return (Criteria) this;
        }

        public Criteria andF_verifycodeNotEqualTo(String value) {
            addCriterion("f_verifycode <>", value, "f_verifycode");
            return (Criteria) this;
        }

        public Criteria andF_verifycodeGreaterThan(String value) {
            addCriterion("f_verifycode >", value, "f_verifycode");
            return (Criteria) this;
        }

        public Criteria andF_verifycodeGreaterThanOrEqualTo(String value) {
            addCriterion("f_verifycode >=", value, "f_verifycode");
            return (Criteria) this;
        }

        public Criteria andF_verifycodeLessThan(String value) {
            addCriterion("f_verifycode <", value, "f_verifycode");
            return (Criteria) this;
        }

        public Criteria andF_verifycodeLessThanOrEqualTo(String value) {
            addCriterion("f_verifycode <=", value, "f_verifycode");
            return (Criteria) this;
        }

        public Criteria andF_verifycodeLike(String value) {
            addCriterion("f_verifycode like", value, "f_verifycode");
            return (Criteria) this;
        }

        public Criteria andF_verifycodeNotLike(String value) {
            addCriterion("f_verifycode not like", value, "f_verifycode");
            return (Criteria) this;
        }

        public Criteria andF_verifycodeIn(List<String> values) {
            addCriterion("f_verifycode in", values, "f_verifycode");
            return (Criteria) this;
        }

        public Criteria andF_verifycodeNotIn(List<String> values) {
            addCriterion("f_verifycode not in", values, "f_verifycode");
            return (Criteria) this;
        }

        public Criteria andF_verifycodeBetween(String value1, String value2) {
            addCriterion("f_verifycode between", value1, value2, "f_verifycode");
            return (Criteria) this;
        }

        public Criteria andF_verifycodeNotBetween(String value1, String value2) {
            addCriterion("f_verifycode not between", value1, value2, "f_verifycode");
            return (Criteria) this;
        }

        public Criteria andF_verifytimeIsNull() {
            addCriterion("f_verifytime is null");
            return (Criteria) this;
        }

        public Criteria andF_verifytimeIsNotNull() {
            addCriterion("f_verifytime is not null");
            return (Criteria) this;
        }

        public Criteria andF_verifytimeEqualTo(Integer value) {
            addCriterion("f_verifytime =", value, "f_verifytime");
            return (Criteria) this;
        }

        public Criteria andF_verifytimeNotEqualTo(Integer value) {
            addCriterion("f_verifytime <>", value, "f_verifytime");
            return (Criteria) this;
        }

        public Criteria andF_verifytimeGreaterThan(Integer value) {
            addCriterion("f_verifytime >", value, "f_verifytime");
            return (Criteria) this;
        }

        public Criteria andF_verifytimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_verifytime >=", value, "f_verifytime");
            return (Criteria) this;
        }

        public Criteria andF_verifytimeLessThan(Integer value) {
            addCriterion("f_verifytime <", value, "f_verifytime");
            return (Criteria) this;
        }

        public Criteria andF_verifytimeLessThanOrEqualTo(Integer value) {
            addCriterion("f_verifytime <=", value, "f_verifytime");
            return (Criteria) this;
        }

        public Criteria andF_verifytimeIn(List<Integer> values) {
            addCriterion("f_verifytime in", values, "f_verifytime");
            return (Criteria) this;
        }

        public Criteria andF_verifytimeNotIn(List<Integer> values) {
            addCriterion("f_verifytime not in", values, "f_verifytime");
            return (Criteria) this;
        }

        public Criteria andF_verifytimeBetween(Integer value1, Integer value2) {
            addCriterion("f_verifytime between", value1, value2, "f_verifytime");
            return (Criteria) this;
        }

        public Criteria andF_verifytimeNotBetween(Integer value1, Integer value2) {
            addCriterion("f_verifytime not between", value1, value2, "f_verifytime");
            return (Criteria) this;
        }

        public Criteria andF_jwkjsonIsNull() {
            addCriterion("f_jwkjson is null");
            return (Criteria) this;
        }

        public Criteria andF_jwkjsonIsNotNull() {
            addCriterion("f_jwkjson is not null");
            return (Criteria) this;
        }

        public Criteria andF_jwkjsonEqualTo(String value) {
            addCriterion("f_jwkjson =", value, "f_jwkjson");
            return (Criteria) this;
        }

        public Criteria andF_jwkjsonNotEqualTo(String value) {
            addCriterion("f_jwkjson <>", value, "f_jwkjson");
            return (Criteria) this;
        }

        public Criteria andF_jwkjsonGreaterThan(String value) {
            addCriterion("f_jwkjson >", value, "f_jwkjson");
            return (Criteria) this;
        }

        public Criteria andF_jwkjsonGreaterThanOrEqualTo(String value) {
            addCriterion("f_jwkjson >=", value, "f_jwkjson");
            return (Criteria) this;
        }

        public Criteria andF_jwkjsonLessThan(String value) {
            addCriterion("f_jwkjson <", value, "f_jwkjson");
            return (Criteria) this;
        }

        public Criteria andF_jwkjsonLessThanOrEqualTo(String value) {
            addCriterion("f_jwkjson <=", value, "f_jwkjson");
            return (Criteria) this;
        }

        public Criteria andF_jwkjsonLike(String value) {
            addCriterion("f_jwkjson like", value, "f_jwkjson");
            return (Criteria) this;
        }

        public Criteria andF_jwkjsonNotLike(String value) {
            addCriterion("f_jwkjson not like", value, "f_jwkjson");
            return (Criteria) this;
        }

        public Criteria andF_jwkjsonIn(List<String> values) {
            addCriterion("f_jwkjson in", values, "f_jwkjson");
            return (Criteria) this;
        }

        public Criteria andF_jwkjsonNotIn(List<String> values) {
            addCriterion("f_jwkjson not in", values, "f_jwkjson");
            return (Criteria) this;
        }

        public Criteria andF_jwkjsonBetween(String value1, String value2) {
            addCriterion("f_jwkjson between", value1, value2, "f_jwkjson");
            return (Criteria) this;
        }

        public Criteria andF_jwkjsonNotBetween(String value1, String value2) {
            addCriterion("f_jwkjson not between", value1, value2, "f_jwkjson");
            return (Criteria) this;
        }

        public Criteria andF_createtimeIsNull() {
            addCriterion("f_createtime is null");
            return (Criteria) this;
        }

        public Criteria andF_createtimeIsNotNull() {
            addCriterion("f_createtime is not null");
            return (Criteria) this;
        }

        public Criteria andF_createtimeEqualTo(Integer value) {
            addCriterion("f_createtime =", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeNotEqualTo(Integer value) {
            addCriterion("f_createtime <>", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeGreaterThan(Integer value) {
            addCriterion("f_createtime >", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_createtime >=", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeLessThan(Integer value) {
            addCriterion("f_createtime <", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeLessThanOrEqualTo(Integer value) {
            addCriterion("f_createtime <=", value, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeIn(List<Integer> values) {
            addCriterion("f_createtime in", values, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeNotIn(List<Integer> values) {
            addCriterion("f_createtime not in", values, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeBetween(Integer value1, Integer value2) {
            addCriterion("f_createtime between", value1, value2, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_createtimeNotBetween(Integer value1, Integer value2) {
            addCriterion("f_createtime not between", value1, value2, "f_createtime");
            return (Criteria) this;
        }

        public Criteria andF_phoneIsNull() {
            addCriterion("f_phone is null");
            return (Criteria) this;
        }

        public Criteria andF_phoneIsNotNull() {
            addCriterion("f_phone is not null");
            return (Criteria) this;
        }

        public Criteria andF_phoneEqualTo(String value) {
            addCriterion("f_phone =", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotEqualTo(String value) {
            addCriterion("f_phone <>", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneGreaterThan(String value) {
            addCriterion("f_phone >", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneGreaterThanOrEqualTo(String value) {
            addCriterion("f_phone >=", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneLessThan(String value) {
            addCriterion("f_phone <", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneLessThanOrEqualTo(String value) {
            addCriterion("f_phone <=", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneLike(String value) {
            addCriterion("f_phone like", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotLike(String value) {
            addCriterion("f_phone not like", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneIn(List<String> values) {
            addCriterion("f_phone in", values, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotIn(List<String> values) {
            addCriterion("f_phone not in", values, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneBetween(String value1, String value2) {
            addCriterion("f_phone between", value1, value2, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotBetween(String value1, String value2) {
            addCriterion("f_phone not between", value1, value2, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_clienttypeIsNull() {
            addCriterion("f_clienttype is null");
            return (Criteria) this;
        }

        public Criteria andF_clienttypeIsNotNull() {
            addCriterion("f_clienttype is not null");
            return (Criteria) this;
        }

        public Criteria andF_clienttypeEqualTo(Integer value) {
            addCriterion("f_clienttype =", value, "f_clienttype");
            return (Criteria) this;
        }

        public Criteria andF_clienttypeNotEqualTo(Integer value) {
            addCriterion("f_clienttype <>", value, "f_clienttype");
            return (Criteria) this;
        }

        public Criteria andF_clienttypeGreaterThan(Integer value) {
            addCriterion("f_clienttype >", value, "f_clienttype");
            return (Criteria) this;
        }

        public Criteria andF_clienttypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_clienttype >=", value, "f_clienttype");
            return (Criteria) this;
        }

        public Criteria andF_clienttypeLessThan(Integer value) {
            addCriterion("f_clienttype <", value, "f_clienttype");
            return (Criteria) this;
        }

        public Criteria andF_clienttypeLessThanOrEqualTo(Integer value) {
            addCriterion("f_clienttype <=", value, "f_clienttype");
            return (Criteria) this;
        }

        public Criteria andF_clienttypeIn(List<Integer> values) {
            addCriterion("f_clienttype in", values, "f_clienttype");
            return (Criteria) this;
        }

        public Criteria andF_clienttypeNotIn(List<Integer> values) {
            addCriterion("f_clienttype not in", values, "f_clienttype");
            return (Criteria) this;
        }

        public Criteria andF_clienttypeBetween(Integer value1, Integer value2) {
            addCriterion("f_clienttype between", value1, value2, "f_clienttype");
            return (Criteria) this;
        }

        public Criteria andF_clienttypeNotBetween(Integer value1, Integer value2) {
            addCriterion("f_clienttype not between", value1, value2, "f_clienttype");
            return (Criteria) this;
        }

        public Criteria andF_stidIsNull() {
            addCriterion("f_stid is null");
            return (Criteria) this;
        }

        public Criteria andF_stidIsNotNull() {
            addCriterion("f_stid is not null");
            return (Criteria) this;
        }

        public Criteria andF_stidEqualTo(String value) {
            addCriterion("f_stid =", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidNotEqualTo(String value) {
            addCriterion("f_stid <>", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidGreaterThan(String value) {
            addCriterion("f_stid >", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidGreaterThanOrEqualTo(String value) {
            addCriterion("f_stid >=", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidLessThan(String value) {
            addCriterion("f_stid <", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidLessThanOrEqualTo(String value) {
            addCriterion("f_stid <=", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidLike(String value) {
            addCriterion("f_stid like", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidNotLike(String value) {
            addCriterion("f_stid not like", value, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidIn(List<String> values) {
            addCriterion("f_stid in", values, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidNotIn(List<String> values) {
            addCriterion("f_stid not in", values, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidBetween(String value1, String value2) {
            addCriterion("f_stid between", value1, value2, "f_stid");
            return (Criteria) this;
        }

        public Criteria andF_stidNotBetween(String value1, String value2) {
            addCriterion("f_stid not between", value1, value2, "f_stid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_um_session
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 03 16:52:14 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_um_session
     *
     * @mbggenerated Tue Nov 03 16:52:14 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}