package com.etong.data.auto.carphoto;

import java.io.Serializable;

public class CarPhoto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_vm_image.f_vid
     *
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    private Integer vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_vm_image.f_subject
     *
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_vm_image.f_image
     *
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_vm_image.f_imagetypeid
     *
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    private Short imagetypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_vm_image.f_imagetype
     *
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    private String imagetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_vm_image.f_vid
     *
     * @return the value of v_vm_image.f_vid
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_vm_image.f_vid
     *
     * @param vid the value for v_vm_image.f_vid
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_vm_image.f_subject
     *
     * @return the value of v_vm_image.f_subject
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_vm_image.f_subject
     *
     * @param subject the value for v_vm_image.f_subject
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_vm_image.f_image
     *
     * @return the value of v_vm_image.f_image
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_vm_image.f_image
     *
     * @param image the value for v_vm_image.f_image
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_vm_image.f_imagetypeid
     *
     * @return the value of v_vm_image.f_imagetypeid
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    public Short getImagetypeid() {
        return imagetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_vm_image.f_imagetypeid
     *
     * @param imagetypeid the value for v_vm_image.f_imagetypeid
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    public void setImagetypeid(Short imagetypeid) {
        this.imagetypeid = imagetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_vm_image.f_imagetype
     *
     * @return the value of v_vm_image.f_imagetype
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    public String getImagetype() {
        return imagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_vm_image.f_imagetype
     *
     * @param imagetype the value for v_vm_image.f_imagetype
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    public void setImagetype(String imagetype) {
        this.imagetype = imagetype;
    }
}