package com.etong.data.auto.carphoto;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CarPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_vm_image
     *
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    int countByExample(CarPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_vm_image
     *
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    int deleteByExample(CarPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_vm_image
     *
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    int insert(CarPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_vm_image
     *
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    int insertSelective(CarPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_vm_image
     *
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    List<CarPhoto> selectByExample(CarPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_vm_image
     *
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    int updateByExampleSelective(@Param("record") CarPhoto record, @Param("example") CarPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_vm_image
     *
     * @mbggenerated Fri Nov 13 14:25:43 CST 2015
     */
    int updateByExample(@Param("record") CarPhoto record, @Param("example") CarPhotoExample example);
}