package com.etong.data.auto.expand.vehicle;

public class ExpandVehicleWithBLOBs extends ExpandVehicle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle_app.f_impression
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    private String impression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle_app.f_merit
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    private String merit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle_app.f_weakness
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    private String weakness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle_app.f_appearance
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    private String appearance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle_app.f_interior
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    private String interior;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle_app.f_space
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    private String space;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle_app.f_Handling
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    private String handling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle_app.f_power
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    private String power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle_app.f_fuel
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    private String fuel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle_app.f_assembly
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    private String assembly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle_app.f_cust_serv
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    private String custServ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle_app.f_safe
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    private String safe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle_app.f_other
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    private String other;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle_app.f_summary
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle_app.f_brand_desc
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    private String brandDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cm_vehicle_app.f_description
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle_app.f_impression
     *
     * @return the value of t_cm_vehicle_app.f_impression
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getImpression() {
        return impression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle_app.f_impression
     *
     * @param impression the value for t_cm_vehicle_app.f_impression
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setImpression(String impression) {
        this.impression = impression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle_app.f_merit
     *
     * @return the value of t_cm_vehicle_app.f_merit
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getMerit() {
        return merit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle_app.f_merit
     *
     * @param merit the value for t_cm_vehicle_app.f_merit
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setMerit(String merit) {
        this.merit = merit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle_app.f_weakness
     *
     * @return the value of t_cm_vehicle_app.f_weakness
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getWeakness() {
        return weakness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle_app.f_weakness
     *
     * @param weakness the value for t_cm_vehicle_app.f_weakness
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setWeakness(String weakness) {
        this.weakness = weakness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle_app.f_appearance
     *
     * @return the value of t_cm_vehicle_app.f_appearance
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getAppearance() {
        return appearance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle_app.f_appearance
     *
     * @param appearance the value for t_cm_vehicle_app.f_appearance
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setAppearance(String appearance) {
        this.appearance = appearance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle_app.f_interior
     *
     * @return the value of t_cm_vehicle_app.f_interior
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getInterior() {
        return interior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle_app.f_interior
     *
     * @param interior the value for t_cm_vehicle_app.f_interior
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setInterior(String interior) {
        this.interior = interior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle_app.f_space
     *
     * @return the value of t_cm_vehicle_app.f_space
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getSpace() {
        return space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle_app.f_space
     *
     * @param space the value for t_cm_vehicle_app.f_space
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setSpace(String space) {
        this.space = space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle_app.f_Handling
     *
     * @return the value of t_cm_vehicle_app.f_Handling
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getHandling() {
        return handling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle_app.f_Handling
     *
     * @param handling the value for t_cm_vehicle_app.f_Handling
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setHandling(String handling) {
        this.handling = handling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle_app.f_power
     *
     * @return the value of t_cm_vehicle_app.f_power
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle_app.f_power
     *
     * @param power the value for t_cm_vehicle_app.f_power
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setPower(String power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle_app.f_fuel
     *
     * @return the value of t_cm_vehicle_app.f_fuel
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getFuel() {
        return fuel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle_app.f_fuel
     *
     * @param fuel the value for t_cm_vehicle_app.f_fuel
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setFuel(String fuel) {
        this.fuel = fuel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle_app.f_assembly
     *
     * @return the value of t_cm_vehicle_app.f_assembly
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getAssembly() {
        return assembly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle_app.f_assembly
     *
     * @param assembly the value for t_cm_vehicle_app.f_assembly
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setAssembly(String assembly) {
        this.assembly = assembly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle_app.f_cust_serv
     *
     * @return the value of t_cm_vehicle_app.f_cust_serv
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getCustServ() {
        return custServ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle_app.f_cust_serv
     *
     * @param custServ the value for t_cm_vehicle_app.f_cust_serv
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setCustServ(String custServ) {
        this.custServ = custServ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle_app.f_safe
     *
     * @return the value of t_cm_vehicle_app.f_safe
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getSafe() {
        return safe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle_app.f_safe
     *
     * @param safe the value for t_cm_vehicle_app.f_safe
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setSafe(String safe) {
        this.safe = safe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle_app.f_other
     *
     * @return the value of t_cm_vehicle_app.f_other
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle_app.f_other
     *
     * @param other the value for t_cm_vehicle_app.f_other
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setOther(String other) {
        this.other = other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle_app.f_summary
     *
     * @return the value of t_cm_vehicle_app.f_summary
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle_app.f_summary
     *
     * @param summary the value for t_cm_vehicle_app.f_summary
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle_app.f_brand_desc
     *
     * @return the value of t_cm_vehicle_app.f_brand_desc
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getBrandDesc() {
        return brandDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle_app.f_brand_desc
     *
     * @param brandDesc the value for t_cm_vehicle_app.f_brand_desc
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setBrandDesc(String brandDesc) {
        this.brandDesc = brandDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cm_vehicle_app.f_description
     *
     * @return the value of t_cm_vehicle_app.f_description
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cm_vehicle_app.f_description
     *
     * @param description the value for t_cm_vehicle_app.f_description
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }
}