package com.etong.data.auto.expand.vehicle;

import com.etong.pt.utility.PageLimit;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class ExpandVehicleExample extends PageLimit implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public ExpandVehicleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    protected abstract static class GeneratedCriteria implements Serializable {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("f_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("f_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Short value) {
            addCriterion("f_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Short value) {
            addCriterion("f_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Short value) {
            addCriterion("f_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Short value) {
            addCriterion("f_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Short value) {
            addCriterion("f_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Short value) {
            addCriterion("f_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Short> values) {
            addCriterion("f_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Short> values) {
            addCriterion("f_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Short value1, Short value2) {
            addCriterion("f_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Short value1, Short value2) {
            addCriterion("f_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPidIsNull() {
            addCriterion("f_pid is null");
            return (Criteria) this;
        }

        public Criteria andPidIsNotNull() {
            addCriterion("f_pid is not null");
            return (Criteria) this;
        }

        public Criteria andPidEqualTo(Short value) {
            addCriterion("f_pid =", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotEqualTo(Short value) {
            addCriterion("f_pid <>", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThan(Short value) {
            addCriterion("f_pid >", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidGreaterThanOrEqualTo(Short value) {
            addCriterion("f_pid >=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThan(Short value) {
            addCriterion("f_pid <", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidLessThanOrEqualTo(Short value) {
            addCriterion("f_pid <=", value, "pid");
            return (Criteria) this;
        }

        public Criteria andPidIn(List<Short> values) {
            addCriterion("f_pid in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotIn(List<Short> values) {
            addCriterion("f_pid not in", values, "pid");
            return (Criteria) this;
        }

        public Criteria andPidBetween(Short value1, Short value2) {
            addCriterion("f_pid between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andPidNotBetween(Short value1, Short value2) {
            addCriterion("f_pid not between", value1, value2, "pid");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("f_level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("f_level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Byte value) {
            addCriterion("f_level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Byte value) {
            addCriterion("f_level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Byte value) {
            addCriterion("f_level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Byte value) {
            addCriterion("f_level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Byte value) {
            addCriterion("f_level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Byte value) {
            addCriterion("f_level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Byte> values) {
            addCriterion("f_level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Byte> values) {
            addCriterion("f_level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Byte value1, Byte value2) {
            addCriterion("f_level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Byte value1, Byte value2) {
            addCriterion("f_level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("f_title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("f_title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("f_title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("f_title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("f_title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("f_title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("f_title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("f_title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("f_title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("f_title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("f_title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("f_title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("f_title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("f_title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andLetterIsNull() {
            addCriterion("f_letter is null");
            return (Criteria) this;
        }

        public Criteria andLetterIsNotNull() {
            addCriterion("f_letter is not null");
            return (Criteria) this;
        }

        public Criteria andLetterEqualTo(String value) {
            addCriterion("f_letter =", value, "letter");
            return (Criteria) this;
        }

        public Criteria andLetterNotEqualTo(String value) {
            addCriterion("f_letter <>", value, "letter");
            return (Criteria) this;
        }

        public Criteria andLetterGreaterThan(String value) {
            addCriterion("f_letter >", value, "letter");
            return (Criteria) this;
        }

        public Criteria andLetterGreaterThanOrEqualTo(String value) {
            addCriterion("f_letter >=", value, "letter");
            return (Criteria) this;
        }

        public Criteria andLetterLessThan(String value) {
            addCriterion("f_letter <", value, "letter");
            return (Criteria) this;
        }

        public Criteria andLetterLessThanOrEqualTo(String value) {
            addCriterion("f_letter <=", value, "letter");
            return (Criteria) this;
        }

        public Criteria andLetterLike(String value) {
            addCriterion("f_letter like", value, "letter");
            return (Criteria) this;
        }

        public Criteria andLetterNotLike(String value) {
            addCriterion("f_letter not like", value, "letter");
            return (Criteria) this;
        }

        public Criteria andLetterIn(List<String> values) {
            addCriterion("f_letter in", values, "letter");
            return (Criteria) this;
        }

        public Criteria andLetterNotIn(List<String> values) {
            addCriterion("f_letter not in", values, "letter");
            return (Criteria) this;
        }

        public Criteria andLetterBetween(String value1, String value2) {
            addCriterion("f_letter between", value1, value2, "letter");
            return (Criteria) this;
        }

        public Criteria andLetterNotBetween(String value1, String value2) {
            addCriterion("f_letter not between", value1, value2, "letter");
            return (Criteria) this;
        }

        public Criteria andVieworderIsNull() {
            addCriterion("f_vieworder is null");
            return (Criteria) this;
        }

        public Criteria andVieworderIsNotNull() {
            addCriterion("f_vieworder is not null");
            return (Criteria) this;
        }

        public Criteria andVieworderEqualTo(Short value) {
            addCriterion("f_vieworder =", value, "vieworder");
            return (Criteria) this;
        }

        public Criteria andVieworderNotEqualTo(Short value) {
            addCriterion("f_vieworder <>", value, "vieworder");
            return (Criteria) this;
        }

        public Criteria andVieworderGreaterThan(Short value) {
            addCriterion("f_vieworder >", value, "vieworder");
            return (Criteria) this;
        }

        public Criteria andVieworderGreaterThanOrEqualTo(Short value) {
            addCriterion("f_vieworder >=", value, "vieworder");
            return (Criteria) this;
        }

        public Criteria andVieworderLessThan(Short value) {
            addCriterion("f_vieworder <", value, "vieworder");
            return (Criteria) this;
        }

        public Criteria andVieworderLessThanOrEqualTo(Short value) {
            addCriterion("f_vieworder <=", value, "vieworder");
            return (Criteria) this;
        }

        public Criteria andVieworderIn(List<Short> values) {
            addCriterion("f_vieworder in", values, "vieworder");
            return (Criteria) this;
        }

        public Criteria andVieworderNotIn(List<Short> values) {
            addCriterion("f_vieworder not in", values, "vieworder");
            return (Criteria) this;
        }

        public Criteria andVieworderBetween(Short value1, Short value2) {
            addCriterion("f_vieworder between", value1, value2, "vieworder");
            return (Criteria) this;
        }

        public Criteria andVieworderNotBetween(Short value1, Short value2) {
            addCriterion("f_vieworder not between", value1, value2, "vieworder");
            return (Criteria) this;
        }

        public Criteria andTrueorderIsNull() {
            addCriterion("f_trueorder is null");
            return (Criteria) this;
        }

        public Criteria andTrueorderIsNotNull() {
            addCriterion("f_trueorder is not null");
            return (Criteria) this;
        }

        public Criteria andTrueorderEqualTo(Short value) {
            addCriterion("f_trueorder =", value, "trueorder");
            return (Criteria) this;
        }

        public Criteria andTrueorderNotEqualTo(Short value) {
            addCriterion("f_trueorder <>", value, "trueorder");
            return (Criteria) this;
        }

        public Criteria andTrueorderGreaterThan(Short value) {
            addCriterion("f_trueorder >", value, "trueorder");
            return (Criteria) this;
        }

        public Criteria andTrueorderGreaterThanOrEqualTo(Short value) {
            addCriterion("f_trueorder >=", value, "trueorder");
            return (Criteria) this;
        }

        public Criteria andTrueorderLessThan(Short value) {
            addCriterion("f_trueorder <", value, "trueorder");
            return (Criteria) this;
        }

        public Criteria andTrueorderLessThanOrEqualTo(Short value) {
            addCriterion("f_trueorder <=", value, "trueorder");
            return (Criteria) this;
        }

        public Criteria andTrueorderIn(List<Short> values) {
            addCriterion("f_trueorder in", values, "trueorder");
            return (Criteria) this;
        }

        public Criteria andTrueorderNotIn(List<Short> values) {
            addCriterion("f_trueorder not in", values, "trueorder");
            return (Criteria) this;
        }

        public Criteria andTrueorderBetween(Short value1, Short value2) {
            addCriterion("f_trueorder between", value1, value2, "trueorder");
            return (Criteria) this;
        }

        public Criteria andTrueorderNotBetween(Short value1, Short value2) {
            addCriterion("f_trueorder not between", value1, value2, "trueorder");
            return (Criteria) this;
        }

        public Criteria andClosedIsNull() {
            addCriterion("f_closed is null");
            return (Criteria) this;
        }

        public Criteria andClosedIsNotNull() {
            addCriterion("f_closed is not null");
            return (Criteria) this;
        }

        public Criteria andClosedEqualTo(Boolean value) {
            addCriterion("f_closed =", value, "closed");
            return (Criteria) this;
        }

        public Criteria andClosedNotEqualTo(Boolean value) {
            addCriterion("f_closed <>", value, "closed");
            return (Criteria) this;
        }

        public Criteria andClosedGreaterThan(Boolean value) {
            addCriterion("f_closed >", value, "closed");
            return (Criteria) this;
        }

        public Criteria andClosedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("f_closed >=", value, "closed");
            return (Criteria) this;
        }

        public Criteria andClosedLessThan(Boolean value) {
            addCriterion("f_closed <", value, "closed");
            return (Criteria) this;
        }

        public Criteria andClosedLessThanOrEqualTo(Boolean value) {
            addCriterion("f_closed <=", value, "closed");
            return (Criteria) this;
        }

        public Criteria andClosedIn(List<Boolean> values) {
            addCriterion("f_closed in", values, "closed");
            return (Criteria) this;
        }

        public Criteria andClosedNotIn(List<Boolean> values) {
            addCriterion("f_closed not in", values, "closed");
            return (Criteria) this;
        }

        public Criteria andClosedBetween(Boolean value1, Boolean value2) {
            addCriterion("f_closed between", value1, value2, "closed");
            return (Criteria) this;
        }

        public Criteria andClosedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("f_closed not between", value1, value2, "closed");
            return (Criteria) this;
        }

        public Criteria andClicksIsNull() {
            addCriterion("f_clicks is null");
            return (Criteria) this;
        }

        public Criteria andClicksIsNotNull() {
            addCriterion("f_clicks is not null");
            return (Criteria) this;
        }

        public Criteria andClicksEqualTo(Integer value) {
            addCriterion("f_clicks =", value, "clicks");
            return (Criteria) this;
        }

        public Criteria andClicksNotEqualTo(Integer value) {
            addCriterion("f_clicks <>", value, "clicks");
            return (Criteria) this;
        }

        public Criteria andClicksGreaterThan(Integer value) {
            addCriterion("f_clicks >", value, "clicks");
            return (Criteria) this;
        }

        public Criteria andClicksGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_clicks >=", value, "clicks");
            return (Criteria) this;
        }

        public Criteria andClicksLessThan(Integer value) {
            addCriterion("f_clicks <", value, "clicks");
            return (Criteria) this;
        }

        public Criteria andClicksLessThanOrEqualTo(Integer value) {
            addCriterion("f_clicks <=", value, "clicks");
            return (Criteria) this;
        }

        public Criteria andClicksIn(List<Integer> values) {
            addCriterion("f_clicks in", values, "clicks");
            return (Criteria) this;
        }

        public Criteria andClicksNotIn(List<Integer> values) {
            addCriterion("f_clicks not in", values, "clicks");
            return (Criteria) this;
        }

        public Criteria andClicksBetween(Integer value1, Integer value2) {
            addCriterion("f_clicks between", value1, value2, "clicks");
            return (Criteria) this;
        }

        public Criteria andClicksNotBetween(Integer value1, Integer value2) {
            addCriterion("f_clicks not between", value1, value2, "clicks");
            return (Criteria) this;
        }

        public Criteria andArchivesIsNull() {
            addCriterion("f_archives is null");
            return (Criteria) this;
        }

        public Criteria andArchivesIsNotNull() {
            addCriterion("f_archives is not null");
            return (Criteria) this;
        }

        public Criteria andArchivesEqualTo(Integer value) {
            addCriterion("f_archives =", value, "archives");
            return (Criteria) this;
        }

        public Criteria andArchivesNotEqualTo(Integer value) {
            addCriterion("f_archives <>", value, "archives");
            return (Criteria) this;
        }

        public Criteria andArchivesGreaterThan(Integer value) {
            addCriterion("f_archives >", value, "archives");
            return (Criteria) this;
        }

        public Criteria andArchivesGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_archives >=", value, "archives");
            return (Criteria) this;
        }

        public Criteria andArchivesLessThan(Integer value) {
            addCriterion("f_archives <", value, "archives");
            return (Criteria) this;
        }

        public Criteria andArchivesLessThanOrEqualTo(Integer value) {
            addCriterion("f_archives <=", value, "archives");
            return (Criteria) this;
        }

        public Criteria andArchivesIn(List<Integer> values) {
            addCriterion("f_archives in", values, "archives");
            return (Criteria) this;
        }

        public Criteria andArchivesNotIn(List<Integer> values) {
            addCriterion("f_archives not in", values, "archives");
            return (Criteria) this;
        }

        public Criteria andArchivesBetween(Integer value1, Integer value2) {
            addCriterion("f_archives between", value1, value2, "archives");
            return (Criteria) this;
        }

        public Criteria andArchivesNotBetween(Integer value1, Integer value2) {
            addCriterion("f_archives not between", value1, value2, "archives");
            return (Criteria) this;
        }

        public Criteria andLogoIsNull() {
            addCriterion("f_logo is null");
            return (Criteria) this;
        }

        public Criteria andLogoIsNotNull() {
            addCriterion("f_logo is not null");
            return (Criteria) this;
        }

        public Criteria andLogoEqualTo(String value) {
            addCriterion("f_logo =", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotEqualTo(String value) {
            addCriterion("f_logo <>", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThan(String value) {
            addCriterion("f_logo >", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThanOrEqualTo(String value) {
            addCriterion("f_logo >=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThan(String value) {
            addCriterion("f_logo <", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThanOrEqualTo(String value) {
            addCriterion("f_logo <=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLike(String value) {
            addCriterion("f_logo like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotLike(String value) {
            addCriterion("f_logo not like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoIn(List<String> values) {
            addCriterion("f_logo in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotIn(List<String> values) {
            addCriterion("f_logo not in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoBetween(String value1, String value2) {
            addCriterion("f_logo between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotBetween(String value1, String value2) {
            addCriterion("f_logo not between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andMinpriceIsNull() {
            addCriterion("f_minprice is null");
            return (Criteria) this;
        }

        public Criteria andMinpriceIsNotNull() {
            addCriterion("f_minprice is not null");
            return (Criteria) this;
        }

        public Criteria andMinpriceEqualTo(Float value) {
            addCriterion("f_minprice =", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceNotEqualTo(Float value) {
            addCriterion("f_minprice <>", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceGreaterThan(Float value) {
            addCriterion("f_minprice >", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceGreaterThanOrEqualTo(Float value) {
            addCriterion("f_minprice >=", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceLessThan(Float value) {
            addCriterion("f_minprice <", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceLessThanOrEqualTo(Float value) {
            addCriterion("f_minprice <=", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceIn(List<Float> values) {
            addCriterion("f_minprice in", values, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceNotIn(List<Float> values) {
            addCriterion("f_minprice not in", values, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceBetween(Float value1, Float value2) {
            addCriterion("f_minprice between", value1, value2, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceNotBetween(Float value1, Float value2) {
            addCriterion("f_minprice not between", value1, value2, "minprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceIsNull() {
            addCriterion("f_maxprice is null");
            return (Criteria) this;
        }

        public Criteria andMaxpriceIsNotNull() {
            addCriterion("f_maxprice is not null");
            return (Criteria) this;
        }

        public Criteria andMaxpriceEqualTo(Float value) {
            addCriterion("f_maxprice =", value, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceNotEqualTo(Float value) {
            addCriterion("f_maxprice <>", value, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceGreaterThan(Float value) {
            addCriterion("f_maxprice >", value, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceGreaterThanOrEqualTo(Float value) {
            addCriterion("f_maxprice >=", value, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceLessThan(Float value) {
            addCriterion("f_maxprice <", value, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceLessThanOrEqualTo(Float value) {
            addCriterion("f_maxprice <=", value, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceIn(List<Float> values) {
            addCriterion("f_maxprice in", values, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceNotIn(List<Float> values) {
            addCriterion("f_maxprice not in", values, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceBetween(Float value1, Float value2) {
            addCriterion("f_maxprice between", value1, value2, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMaxpriceNotBetween(Float value1, Float value2) {
            addCriterion("f_maxprice not between", value1, value2, "maxprice");
            return (Criteria) this;
        }

        public Criteria andMinguideIsNull() {
            addCriterion("f_minguide is null");
            return (Criteria) this;
        }

        public Criteria andMinguideIsNotNull() {
            addCriterion("f_minguide is not null");
            return (Criteria) this;
        }

        public Criteria andMinguideEqualTo(Float value) {
            addCriterion("f_minguide =", value, "minguide");
            return (Criteria) this;
        }

        public Criteria andMinguideNotEqualTo(Float value) {
            addCriterion("f_minguide <>", value, "minguide");
            return (Criteria) this;
        }

        public Criteria andMinguideGreaterThan(Float value) {
            addCriterion("f_minguide >", value, "minguide");
            return (Criteria) this;
        }

        public Criteria andMinguideGreaterThanOrEqualTo(Float value) {
            addCriterion("f_minguide >=", value, "minguide");
            return (Criteria) this;
        }

        public Criteria andMinguideLessThan(Float value) {
            addCriterion("f_minguide <", value, "minguide");
            return (Criteria) this;
        }

        public Criteria andMinguideLessThanOrEqualTo(Float value) {
            addCriterion("f_minguide <=", value, "minguide");
            return (Criteria) this;
        }

        public Criteria andMinguideIn(List<Float> values) {
            addCriterion("f_minguide in", values, "minguide");
            return (Criteria) this;
        }

        public Criteria andMinguideNotIn(List<Float> values) {
            addCriterion("f_minguide not in", values, "minguide");
            return (Criteria) this;
        }

        public Criteria andMinguideBetween(Float value1, Float value2) {
            addCriterion("f_minguide between", value1, value2, "minguide");
            return (Criteria) this;
        }

        public Criteria andMinguideNotBetween(Float value1, Float value2) {
            addCriterion("f_minguide not between", value1, value2, "minguide");
            return (Criteria) this;
        }

        public Criteria andMaxguideIsNull() {
            addCriterion("f_maxguide is null");
            return (Criteria) this;
        }

        public Criteria andMaxguideIsNotNull() {
            addCriterion("f_maxguide is not null");
            return (Criteria) this;
        }

        public Criteria andMaxguideEqualTo(Float value) {
            addCriterion("f_maxguide =", value, "maxguide");
            return (Criteria) this;
        }

        public Criteria andMaxguideNotEqualTo(Float value) {
            addCriterion("f_maxguide <>", value, "maxguide");
            return (Criteria) this;
        }

        public Criteria andMaxguideGreaterThan(Float value) {
            addCriterion("f_maxguide >", value, "maxguide");
            return (Criteria) this;
        }

        public Criteria andMaxguideGreaterThanOrEqualTo(Float value) {
            addCriterion("f_maxguide >=", value, "maxguide");
            return (Criteria) this;
        }

        public Criteria andMaxguideLessThan(Float value) {
            addCriterion("f_maxguide <", value, "maxguide");
            return (Criteria) this;
        }

        public Criteria andMaxguideLessThanOrEqualTo(Float value) {
            addCriterion("f_maxguide <=", value, "maxguide");
            return (Criteria) this;
        }

        public Criteria andMaxguideIn(List<Float> values) {
            addCriterion("f_maxguide in", values, "maxguide");
            return (Criteria) this;
        }

        public Criteria andMaxguideNotIn(List<Float> values) {
            addCriterion("f_maxguide not in", values, "maxguide");
            return (Criteria) this;
        }

        public Criteria andMaxguideBetween(Float value1, Float value2) {
            addCriterion("f_maxguide between", value1, value2, "maxguide");
            return (Criteria) this;
        }

        public Criteria andMaxguideNotBetween(Float value1, Float value2) {
            addCriterion("f_maxguide not between", value1, value2, "maxguide");
            return (Criteria) this;
        }

        public Criteria andOutVolIsNull() {
            addCriterion("f_out_vol is null");
            return (Criteria) this;
        }

        public Criteria andOutVolIsNotNull() {
            addCriterion("f_out_vol is not null");
            return (Criteria) this;
        }

        public Criteria andOutVolEqualTo(String value) {
            addCriterion("f_out_vol =", value, "outVol");
            return (Criteria) this;
        }

        public Criteria andOutVolNotEqualTo(String value) {
            addCriterion("f_out_vol <>", value, "outVol");
            return (Criteria) this;
        }

        public Criteria andOutVolGreaterThan(String value) {
            addCriterion("f_out_vol >", value, "outVol");
            return (Criteria) this;
        }

        public Criteria andOutVolGreaterThanOrEqualTo(String value) {
            addCriterion("f_out_vol >=", value, "outVol");
            return (Criteria) this;
        }

        public Criteria andOutVolLessThan(String value) {
            addCriterion("f_out_vol <", value, "outVol");
            return (Criteria) this;
        }

        public Criteria andOutVolLessThanOrEqualTo(String value) {
            addCriterion("f_out_vol <=", value, "outVol");
            return (Criteria) this;
        }

        public Criteria andOutVolLike(String value) {
            addCriterion("f_out_vol like", value, "outVol");
            return (Criteria) this;
        }

        public Criteria andOutVolNotLike(String value) {
            addCriterion("f_out_vol not like", value, "outVol");
            return (Criteria) this;
        }

        public Criteria andOutVolIn(List<String> values) {
            addCriterion("f_out_vol in", values, "outVol");
            return (Criteria) this;
        }

        public Criteria andOutVolNotIn(List<String> values) {
            addCriterion("f_out_vol not in", values, "outVol");
            return (Criteria) this;
        }

        public Criteria andOutVolBetween(String value1, String value2) {
            addCriterion("f_out_vol between", value1, value2, "outVol");
            return (Criteria) this;
        }

        public Criteria andOutVolNotBetween(String value1, String value2) {
            addCriterion("f_out_vol not between", value1, value2, "outVol");
            return (Criteria) this;
        }

        public Criteria andVariatorIsNull() {
            addCriterion("f_variator is null");
            return (Criteria) this;
        }

        public Criteria andVariatorIsNotNull() {
            addCriterion("f_variator is not null");
            return (Criteria) this;
        }

        public Criteria andVariatorEqualTo(String value) {
            addCriterion("f_variator =", value, "variator");
            return (Criteria) this;
        }

        public Criteria andVariatorNotEqualTo(String value) {
            addCriterion("f_variator <>", value, "variator");
            return (Criteria) this;
        }

        public Criteria andVariatorGreaterThan(String value) {
            addCriterion("f_variator >", value, "variator");
            return (Criteria) this;
        }

        public Criteria andVariatorGreaterThanOrEqualTo(String value) {
            addCriterion("f_variator >=", value, "variator");
            return (Criteria) this;
        }

        public Criteria andVariatorLessThan(String value) {
            addCriterion("f_variator <", value, "variator");
            return (Criteria) this;
        }

        public Criteria andVariatorLessThanOrEqualTo(String value) {
            addCriterion("f_variator <=", value, "variator");
            return (Criteria) this;
        }

        public Criteria andVariatorLike(String value) {
            addCriterion("f_variator like", value, "variator");
            return (Criteria) this;
        }

        public Criteria andVariatorNotLike(String value) {
            addCriterion("f_variator not like", value, "variator");
            return (Criteria) this;
        }

        public Criteria andVariatorIn(List<String> values) {
            addCriterion("f_variator in", values, "variator");
            return (Criteria) this;
        }

        public Criteria andVariatorNotIn(List<String> values) {
            addCriterion("f_variator not in", values, "variator");
            return (Criteria) this;
        }

        public Criteria andVariatorBetween(String value1, String value2) {
            addCriterion("f_variator between", value1, value2, "variator");
            return (Criteria) this;
        }

        public Criteria andVariatorNotBetween(String value1, String value2) {
            addCriterion("f_variator not between", value1, value2, "variator");
            return (Criteria) this;
        }

        public Criteria andModelsImageIsNull() {
            addCriterion("f_models_image is null");
            return (Criteria) this;
        }

        public Criteria andModelsImageIsNotNull() {
            addCriterion("f_models_image is not null");
            return (Criteria) this;
        }

        public Criteria andModelsImageEqualTo(String value) {
            addCriterion("f_models_image =", value, "modelsImage");
            return (Criteria) this;
        }

        public Criteria andModelsImageNotEqualTo(String value) {
            addCriterion("f_models_image <>", value, "modelsImage");
            return (Criteria) this;
        }

        public Criteria andModelsImageGreaterThan(String value) {
            addCriterion("f_models_image >", value, "modelsImage");
            return (Criteria) this;
        }

        public Criteria andModelsImageGreaterThanOrEqualTo(String value) {
            addCriterion("f_models_image >=", value, "modelsImage");
            return (Criteria) this;
        }

        public Criteria andModelsImageLessThan(String value) {
            addCriterion("f_models_image <", value, "modelsImage");
            return (Criteria) this;
        }

        public Criteria andModelsImageLessThanOrEqualTo(String value) {
            addCriterion("f_models_image <=", value, "modelsImage");
            return (Criteria) this;
        }

        public Criteria andModelsImageLike(String value) {
            addCriterion("f_models_image like", value, "modelsImage");
            return (Criteria) this;
        }

        public Criteria andModelsImageNotLike(String value) {
            addCriterion("f_models_image not like", value, "modelsImage");
            return (Criteria) this;
        }

        public Criteria andModelsImageIn(List<String> values) {
            addCriterion("f_models_image in", values, "modelsImage");
            return (Criteria) this;
        }

        public Criteria andModelsImageNotIn(List<String> values) {
            addCriterion("f_models_image not in", values, "modelsImage");
            return (Criteria) this;
        }

        public Criteria andModelsImageBetween(String value1, String value2) {
            addCriterion("f_models_image between", value1, value2, "modelsImage");
            return (Criteria) this;
        }

        public Criteria andModelsImageNotBetween(String value1, String value2) {
            addCriterion("f_models_image not between", value1, value2, "modelsImage");
            return (Criteria) this;
        }

        public Criteria andModelsLevelIsNull() {
            addCriterion("f_models_level is null");
            return (Criteria) this;
        }

        public Criteria andModelsLevelIsNotNull() {
            addCriterion("f_models_level is not null");
            return (Criteria) this;
        }

        public Criteria andModelsLevelEqualTo(Short value) {
            addCriterion("f_models_level =", value, "modelsLevel");
            return (Criteria) this;
        }

        public Criteria andModelsLevelNotEqualTo(Short value) {
            addCriterion("f_models_level <>", value, "modelsLevel");
            return (Criteria) this;
        }

        public Criteria andModelsLevelGreaterThan(Short value) {
            addCriterion("f_models_level >", value, "modelsLevel");
            return (Criteria) this;
        }

        public Criteria andModelsLevelGreaterThanOrEqualTo(Short value) {
            addCriterion("f_models_level >=", value, "modelsLevel");
            return (Criteria) this;
        }

        public Criteria andModelsLevelLessThan(Short value) {
            addCriterion("f_models_level <", value, "modelsLevel");
            return (Criteria) this;
        }

        public Criteria andModelsLevelLessThanOrEqualTo(Short value) {
            addCriterion("f_models_level <=", value, "modelsLevel");
            return (Criteria) this;
        }

        public Criteria andModelsLevelIn(List<Short> values) {
            addCriterion("f_models_level in", values, "modelsLevel");
            return (Criteria) this;
        }

        public Criteria andModelsLevelNotIn(List<Short> values) {
            addCriterion("f_models_level not in", values, "modelsLevel");
            return (Criteria) this;
        }

        public Criteria andModelsLevelBetween(Short value1, Short value2) {
            addCriterion("f_models_level between", value1, value2, "modelsLevel");
            return (Criteria) this;
        }

        public Criteria andModelsLevelNotBetween(Short value1, Short value2) {
            addCriterion("f_models_level not between", value1, value2, "modelsLevel");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("f_country is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("f_country is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(Short value) {
            addCriterion("f_country =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(Short value) {
            addCriterion("f_country <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(Short value) {
            addCriterion("f_country >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(Short value) {
            addCriterion("f_country >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(Short value) {
            addCriterion("f_country <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(Short value) {
            addCriterion("f_country <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<Short> values) {
            addCriterion("f_country in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<Short> values) {
            addCriterion("f_country not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(Short value1, Short value2) {
            addCriterion("f_country between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(Short value1, Short value2) {
            addCriterion("f_country not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andLengthIsNull() {
            addCriterion("f_length is null");
            return (Criteria) this;
        }

        public Criteria andLengthIsNotNull() {
            addCriterion("f_length is not null");
            return (Criteria) this;
        }

        public Criteria andLengthEqualTo(String value) {
            addCriterion("f_length =", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotEqualTo(String value) {
            addCriterion("f_length <>", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThan(String value) {
            addCriterion("f_length >", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthGreaterThanOrEqualTo(String value) {
            addCriterion("f_length >=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThan(String value) {
            addCriterion("f_length <", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLessThanOrEqualTo(String value) {
            addCriterion("f_length <=", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthLike(String value) {
            addCriterion("f_length like", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotLike(String value) {
            addCriterion("f_length not like", value, "length");
            return (Criteria) this;
        }

        public Criteria andLengthIn(List<String> values) {
            addCriterion("f_length in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotIn(List<String> values) {
            addCriterion("f_length not in", values, "length");
            return (Criteria) this;
        }

        public Criteria andLengthBetween(String value1, String value2) {
            addCriterion("f_length between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andLengthNotBetween(String value1, String value2) {
            addCriterion("f_length not between", value1, value2, "length");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("f_width is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("f_width is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(String value) {
            addCriterion("f_width =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(String value) {
            addCriterion("f_width <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(String value) {
            addCriterion("f_width >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(String value) {
            addCriterion("f_width >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(String value) {
            addCriterion("f_width <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(String value) {
            addCriterion("f_width <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLike(String value) {
            addCriterion("f_width like", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotLike(String value) {
            addCriterion("f_width not like", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<String> values) {
            addCriterion("f_width in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<String> values) {
            addCriterion("f_width not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(String value1, String value2) {
            addCriterion("f_width between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(String value1, String value2) {
            addCriterion("f_width not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("f_height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("f_height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(String value) {
            addCriterion("f_height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(String value) {
            addCriterion("f_height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(String value) {
            addCriterion("f_height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(String value) {
            addCriterion("f_height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(String value) {
            addCriterion("f_height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(String value) {
            addCriterion("f_height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLike(String value) {
            addCriterion("f_height like", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotLike(String value) {
            addCriterion("f_height not like", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<String> values) {
            addCriterion("f_height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<String> values) {
            addCriterion("f_height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(String value1, String value2) {
            addCriterion("f_height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(String value1, String value2) {
            addCriterion("f_height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("f_status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("f_status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("f_status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("f_status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("f_status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("f_status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("f_status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("f_status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("f_status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("f_status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("f_status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andWebsiteIsNull() {
            addCriterion("f_website is null");
            return (Criteria) this;
        }

        public Criteria andWebsiteIsNotNull() {
            addCriterion("f_website is not null");
            return (Criteria) this;
        }

        public Criteria andWebsiteEqualTo(String value) {
            addCriterion("f_website =", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteNotEqualTo(String value) {
            addCriterion("f_website <>", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteGreaterThan(String value) {
            addCriterion("f_website >", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteGreaterThanOrEqualTo(String value) {
            addCriterion("f_website >=", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteLessThan(String value) {
            addCriterion("f_website <", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteLessThanOrEqualTo(String value) {
            addCriterion("f_website <=", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteLike(String value) {
            addCriterion("f_website like", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteNotLike(String value) {
            addCriterion("f_website not like", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteIn(List<String> values) {
            addCriterion("f_website in", values, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteNotIn(List<String> values) {
            addCriterion("f_website not in", values, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteBetween(String value1, String value2) {
            addCriterion("f_website between", value1, value2, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteNotBetween(String value1, String value2) {
            addCriterion("f_website not between", value1, value2, "website");
            return (Criteria) this;
        }

        public Criteria andMinOutIsNull() {
            addCriterion("f_min_out is null");
            return (Criteria) this;
        }

        public Criteria andMinOutIsNotNull() {
            addCriterion("f_min_out is not null");
            return (Criteria) this;
        }

        public Criteria andMinOutEqualTo(Integer value) {
            addCriterion("f_min_out =", value, "minOut");
            return (Criteria) this;
        }

        public Criteria andMinOutNotEqualTo(Integer value) {
            addCriterion("f_min_out <>", value, "minOut");
            return (Criteria) this;
        }

        public Criteria andMinOutGreaterThan(Integer value) {
            addCriterion("f_min_out >", value, "minOut");
            return (Criteria) this;
        }

        public Criteria andMinOutGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_min_out >=", value, "minOut");
            return (Criteria) this;
        }

        public Criteria andMinOutLessThan(Integer value) {
            addCriterion("f_min_out <", value, "minOut");
            return (Criteria) this;
        }

        public Criteria andMinOutLessThanOrEqualTo(Integer value) {
            addCriterion("f_min_out <=", value, "minOut");
            return (Criteria) this;
        }

        public Criteria andMinOutIn(List<Integer> values) {
            addCriterion("f_min_out in", values, "minOut");
            return (Criteria) this;
        }

        public Criteria andMinOutNotIn(List<Integer> values) {
            addCriterion("f_min_out not in", values, "minOut");
            return (Criteria) this;
        }

        public Criteria andMinOutBetween(Integer value1, Integer value2) {
            addCriterion("f_min_out between", value1, value2, "minOut");
            return (Criteria) this;
        }

        public Criteria andMinOutNotBetween(Integer value1, Integer value2) {
            addCriterion("f_min_out not between", value1, value2, "minOut");
            return (Criteria) this;
        }

        public Criteria andMaxOutIsNull() {
            addCriterion("f_max_out is null");
            return (Criteria) this;
        }

        public Criteria andMaxOutIsNotNull() {
            addCriterion("f_max_out is not null");
            return (Criteria) this;
        }

        public Criteria andMaxOutEqualTo(Integer value) {
            addCriterion("f_max_out =", value, "maxOut");
            return (Criteria) this;
        }

        public Criteria andMaxOutNotEqualTo(Integer value) {
            addCriterion("f_max_out <>", value, "maxOut");
            return (Criteria) this;
        }

        public Criteria andMaxOutGreaterThan(Integer value) {
            addCriterion("f_max_out >", value, "maxOut");
            return (Criteria) this;
        }

        public Criteria andMaxOutGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_max_out >=", value, "maxOut");
            return (Criteria) this;
        }

        public Criteria andMaxOutLessThan(Integer value) {
            addCriterion("f_max_out <", value, "maxOut");
            return (Criteria) this;
        }

        public Criteria andMaxOutLessThanOrEqualTo(Integer value) {
            addCriterion("f_max_out <=", value, "maxOut");
            return (Criteria) this;
        }

        public Criteria andMaxOutIn(List<Integer> values) {
            addCriterion("f_max_out in", values, "maxOut");
            return (Criteria) this;
        }

        public Criteria andMaxOutNotIn(List<Integer> values) {
            addCriterion("f_max_out not in", values, "maxOut");
            return (Criteria) this;
        }

        public Criteria andMaxOutBetween(Integer value1, Integer value2) {
            addCriterion("f_max_out between", value1, value2, "maxOut");
            return (Criteria) this;
        }

        public Criteria andMaxOutNotBetween(Integer value1, Integer value2) {
            addCriterion("f_max_out not between", value1, value2, "maxOut");
            return (Criteria) this;
        }

        public Criteria andStidIsNull() {
            addCriterion("f_stid is null");
            return (Criteria) this;
        }

        public Criteria andStidIsNotNull() {
            addCriterion("f_stid is not null");
            return (Criteria) this;
        }

        public Criteria andStidEqualTo(String value) {
            addCriterion("f_stid =", value, "stid");
            return (Criteria) this;
        }

        public Criteria andStidNotEqualTo(String value) {
            addCriterion("f_stid <>", value, "stid");
            return (Criteria) this;
        }

        public Criteria andStidGreaterThan(String value) {
            addCriterion("f_stid >", value, "stid");
            return (Criteria) this;
        }

        public Criteria andStidGreaterThanOrEqualTo(String value) {
            addCriterion("f_stid >=", value, "stid");
            return (Criteria) this;
        }

        public Criteria andStidLessThan(String value) {
            addCriterion("f_stid <", value, "stid");
            return (Criteria) this;
        }

        public Criteria andStidLessThanOrEqualTo(String value) {
            addCriterion("f_stid <=", value, "stid");
            return (Criteria) this;
        }

        public Criteria andStidLike(String value) {
            addCriterion("f_stid like", value, "stid");
            return (Criteria) this;
        }

        public Criteria andStidNotLike(String value) {
            addCriterion("f_stid not like", value, "stid");
            return (Criteria) this;
        }

        public Criteria andStidIn(List<String> values) {
            addCriterion("f_stid in", values, "stid");
            return (Criteria) this;
        }

        public Criteria andStidNotIn(List<String> values) {
            addCriterion("f_stid not in", values, "stid");
            return (Criteria) this;
        }

        public Criteria andStidBetween(String value1, String value2) {
            addCriterion("f_stid between", value1, value2, "stid");
            return (Criteria) this;
        }

        public Criteria andStidNotBetween(String value1, String value2) {
            addCriterion("f_stid not between", value1, value2, "stid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 19 10:48:22 CST 2015
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cm_vehicle_app
     *
     * @mbggenerated Thu Nov 19 10:48:22 CST 2015
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}