package com.etong.pt.data.vehicle;

import com.etong.pt.utility.PageLimit;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class PtVehicleExample extends PageLimit implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated Thu Apr 23 09:57:15 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated Thu Apr 23 09:57:15 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated Thu Apr 23 09:57:15 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated Thu Apr 23 09:57:15 CST 2015
     */
    public PtVehicleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated Thu Apr 23 09:57:15 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated Thu Apr 23 09:57:15 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated Thu Apr 23 09:57:15 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated Thu Apr 23 09:57:15 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated Thu Apr 23 09:57:15 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated Thu Apr 23 09:57:15 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated Thu Apr 23 09:57:15 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated Thu Apr 23 09:57:15 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated Thu Apr 23 09:57:15 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated Thu Apr 23 09:57:15 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated Thu Apr 23 09:57:15 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andF_dvidIsNull() {
            addCriterion("f_dvid is null");
            return (Criteria) this;
        }

        public Criteria andF_dvidIsNotNull() {
            addCriterion("f_dvid is not null");
            return (Criteria) this;
        }

        public Criteria andF_dvidEqualTo(Long value) {
            addCriterion("f_dvid =", value, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidNotEqualTo(Long value) {
            addCriterion("f_dvid <>", value, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidGreaterThan(Long value) {
            addCriterion("f_dvid >", value, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidGreaterThanOrEqualTo(Long value) {
            addCriterion("f_dvid >=", value, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidLessThan(Long value) {
            addCriterion("f_dvid <", value, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidLessThanOrEqualTo(Long value) {
            addCriterion("f_dvid <=", value, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidIn(List<Long> values) {
            addCriterion("f_dvid in", values, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidNotIn(List<Long> values) {
            addCriterion("f_dvid not in", values, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidBetween(Long value1, Long value2) {
            addCriterion("f_dvid between", value1, value2, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_dvidNotBetween(Long value1, Long value2) {
            addCriterion("f_dvid not between", value1, value2, "f_dvid");
            return (Criteria) this;
        }

        public Criteria andF_vidIsNull() {
            addCriterion("f_vid is null");
            return (Criteria) this;
        }

        public Criteria andF_vidIsNotNull() {
            addCriterion("f_vid is not null");
            return (Criteria) this;
        }

        public Criteria andF_vidEqualTo(Integer value) {
            addCriterion("f_vid =", value, "f_vid");
            return (Criteria) this;
        }

        public Criteria andF_vidNotEqualTo(Integer value) {
            addCriterion("f_vid <>", value, "f_vid");
            return (Criteria) this;
        }

        public Criteria andF_vidGreaterThan(Integer value) {
            addCriterion("f_vid >", value, "f_vid");
            return (Criteria) this;
        }

        public Criteria andF_vidGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_vid >=", value, "f_vid");
            return (Criteria) this;
        }

        public Criteria andF_vidLessThan(Integer value) {
            addCriterion("f_vid <", value, "f_vid");
            return (Criteria) this;
        }

        public Criteria andF_vidLessThanOrEqualTo(Integer value) {
            addCriterion("f_vid <=", value, "f_vid");
            return (Criteria) this;
        }

        public Criteria andF_vidIn(List<Integer> values) {
            addCriterion("f_vid in", values, "f_vid");
            return (Criteria) this;
        }

        public Criteria andF_vidNotIn(List<Integer> values) {
            addCriterion("f_vid not in", values, "f_vid");
            return (Criteria) this;
        }

        public Criteria andF_vidBetween(Integer value1, Integer value2) {
            addCriterion("f_vid between", value1, value2, "f_vid");
            return (Criteria) this;
        }

        public Criteria andF_vidNotBetween(Integer value1, Integer value2) {
            addCriterion("f_vid not between", value1, value2, "f_vid");
            return (Criteria) this;
        }

        public Criteria andF_ciidIsNull() {
            addCriterion("f_ciid is null");
            return (Criteria) this;
        }

        public Criteria andF_ciidIsNotNull() {
            addCriterion("f_ciid is not null");
            return (Criteria) this;
        }

        public Criteria andF_ciidEqualTo(Long value) {
            addCriterion("f_ciid =", value, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidNotEqualTo(Long value) {
            addCriterion("f_ciid <>", value, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidGreaterThan(Long value) {
            addCriterion("f_ciid >", value, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidGreaterThanOrEqualTo(Long value) {
            addCriterion("f_ciid >=", value, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidLessThan(Long value) {
            addCriterion("f_ciid <", value, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidLessThanOrEqualTo(Long value) {
            addCriterion("f_ciid <=", value, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidIn(List<Long> values) {
            addCriterion("f_ciid in", values, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidNotIn(List<Long> values) {
            addCriterion("f_ciid not in", values, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidBetween(Long value1, Long value2) {
            addCriterion("f_ciid between", value1, value2, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_ciidNotBetween(Long value1, Long value2) {
            addCriterion("f_ciid not between", value1, value2, "f_ciid");
            return (Criteria) this;
        }

        public Criteria andF_plate_numberIsNull() {
            addCriterion("f_plate_number is null");
            return (Criteria) this;
        }

        public Criteria andF_plate_numberIsNotNull() {
            addCriterion("f_plate_number is not null");
            return (Criteria) this;
        }

        public Criteria andF_plate_numberEqualTo(String value) {
            addCriterion("f_plate_number =", value, "f_plate_number");
            return (Criteria) this;
        }

        public Criteria andF_plate_numberNotEqualTo(String value) {
            addCriterion("f_plate_number <>", value, "f_plate_number");
            return (Criteria) this;
        }

        public Criteria andF_plate_numberGreaterThan(String value) {
            addCriterion("f_plate_number >", value, "f_plate_number");
            return (Criteria) this;
        }

        public Criteria andF_plate_numberGreaterThanOrEqualTo(String value) {
            addCriterion("f_plate_number >=", value, "f_plate_number");
            return (Criteria) this;
        }

        public Criteria andF_plate_numberLessThan(String value) {
            addCriterion("f_plate_number <", value, "f_plate_number");
            return (Criteria) this;
        }

        public Criteria andF_plate_numberLessThanOrEqualTo(String value) {
            addCriterion("f_plate_number <=", value, "f_plate_number");
            return (Criteria) this;
        }

        public Criteria andF_plate_numberLike(String value) {
            addCriterion("f_plate_number like", value, "f_plate_number");
            return (Criteria) this;
        }

        public Criteria andF_plate_numberNotLike(String value) {
            addCriterion("f_plate_number not like", value, "f_plate_number");
            return (Criteria) this;
        }

        public Criteria andF_plate_numberIn(List<String> values) {
            addCriterion("f_plate_number in", values, "f_plate_number");
            return (Criteria) this;
        }

        public Criteria andF_plate_numberNotIn(List<String> values) {
            addCriterion("f_plate_number not in", values, "f_plate_number");
            return (Criteria) this;
        }

        public Criteria andF_plate_numberBetween(String value1, String value2) {
            addCriterion("f_plate_number between", value1, value2, "f_plate_number");
            return (Criteria) this;
        }

        public Criteria andF_plate_numberNotBetween(String value1, String value2) {
            addCriterion("f_plate_number not between", value1, value2, "f_plate_number");
            return (Criteria) this;
        }

        public Criteria andF_engine_numberIsNull() {
            addCriterion("f_engine_number is null");
            return (Criteria) this;
        }

        public Criteria andF_engine_numberIsNotNull() {
            addCriterion("f_engine_number is not null");
            return (Criteria) this;
        }

        public Criteria andF_engine_numberEqualTo(String value) {
            addCriterion("f_engine_number =", value, "f_engine_number");
            return (Criteria) this;
        }

        public Criteria andF_engine_numberNotEqualTo(String value) {
            addCriterion("f_engine_number <>", value, "f_engine_number");
            return (Criteria) this;
        }

        public Criteria andF_engine_numberGreaterThan(String value) {
            addCriterion("f_engine_number >", value, "f_engine_number");
            return (Criteria) this;
        }

        public Criteria andF_engine_numberGreaterThanOrEqualTo(String value) {
            addCriterion("f_engine_number >=", value, "f_engine_number");
            return (Criteria) this;
        }

        public Criteria andF_engine_numberLessThan(String value) {
            addCriterion("f_engine_number <", value, "f_engine_number");
            return (Criteria) this;
        }

        public Criteria andF_engine_numberLessThanOrEqualTo(String value) {
            addCriterion("f_engine_number <=", value, "f_engine_number");
            return (Criteria) this;
        }

        public Criteria andF_engine_numberLike(String value) {
            addCriterion("f_engine_number like", value, "f_engine_number");
            return (Criteria) this;
        }

        public Criteria andF_engine_numberNotLike(String value) {
            addCriterion("f_engine_number not like", value, "f_engine_number");
            return (Criteria) this;
        }

        public Criteria andF_engine_numberIn(List<String> values) {
            addCriterion("f_engine_number in", values, "f_engine_number");
            return (Criteria) this;
        }

        public Criteria andF_engine_numberNotIn(List<String> values) {
            addCriterion("f_engine_number not in", values, "f_engine_number");
            return (Criteria) this;
        }

        public Criteria andF_engine_numberBetween(String value1, String value2) {
            addCriterion("f_engine_number between", value1, value2, "f_engine_number");
            return (Criteria) this;
        }

        public Criteria andF_engine_numberNotBetween(String value1, String value2) {
            addCriterion("f_engine_number not between", value1, value2, "f_engine_number");
            return (Criteria) this;
        }

        public Criteria andF_identify_numberIsNull() {
            addCriterion("f_identify_number is null");
            return (Criteria) this;
        }

        public Criteria andF_identify_numberIsNotNull() {
            addCriterion("f_identify_number is not null");
            return (Criteria) this;
        }

        public Criteria andF_identify_numberEqualTo(String value) {
            addCriterion("f_identify_number =", value, "f_identify_number");
            return (Criteria) this;
        }

        public Criteria andF_identify_numberNotEqualTo(String value) {
            addCriterion("f_identify_number <>", value, "f_identify_number");
            return (Criteria) this;
        }

        public Criteria andF_identify_numberGreaterThan(String value) {
            addCriterion("f_identify_number >", value, "f_identify_number");
            return (Criteria) this;
        }

        public Criteria andF_identify_numberGreaterThanOrEqualTo(String value) {
            addCriterion("f_identify_number >=", value, "f_identify_number");
            return (Criteria) this;
        }

        public Criteria andF_identify_numberLessThan(String value) {
            addCriterion("f_identify_number <", value, "f_identify_number");
            return (Criteria) this;
        }

        public Criteria andF_identify_numberLessThanOrEqualTo(String value) {
            addCriterion("f_identify_number <=", value, "f_identify_number");
            return (Criteria) this;
        }

        public Criteria andF_identify_numberLike(String value) {
            addCriterion("f_identify_number like", value, "f_identify_number");
            return (Criteria) this;
        }

        public Criteria andF_identify_numberNotLike(String value) {
            addCriterion("f_identify_number not like", value, "f_identify_number");
            return (Criteria) this;
        }

        public Criteria andF_identify_numberIn(List<String> values) {
            addCriterion("f_identify_number in", values, "f_identify_number");
            return (Criteria) this;
        }

        public Criteria andF_identify_numberNotIn(List<String> values) {
            addCriterion("f_identify_number not in", values, "f_identify_number");
            return (Criteria) this;
        }

        public Criteria andF_identify_numberBetween(String value1, String value2) {
            addCriterion("f_identify_number between", value1, value2, "f_identify_number");
            return (Criteria) this;
        }

        public Criteria andF_identify_numberNotBetween(String value1, String value2) {
            addCriterion("f_identify_number not between", value1, value2, "f_identify_number");
            return (Criteria) this;
        }

        public Criteria andF_limit_numberIsNull() {
            addCriterion("f_limit_number is null");
            return (Criteria) this;
        }

        public Criteria andF_limit_numberIsNotNull() {
            addCriterion("f_limit_number is not null");
            return (Criteria) this;
        }

        public Criteria andF_limit_numberEqualTo(Integer value) {
            addCriterion("f_limit_number =", value, "f_limit_number");
            return (Criteria) this;
        }

        public Criteria andF_limit_numberNotEqualTo(Integer value) {
            addCriterion("f_limit_number <>", value, "f_limit_number");
            return (Criteria) this;
        }

        public Criteria andF_limit_numberGreaterThan(Integer value) {
            addCriterion("f_limit_number >", value, "f_limit_number");
            return (Criteria) this;
        }

        public Criteria andF_limit_numberGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_limit_number >=", value, "f_limit_number");
            return (Criteria) this;
        }

        public Criteria andF_limit_numberLessThan(Integer value) {
            addCriterion("f_limit_number <", value, "f_limit_number");
            return (Criteria) this;
        }

        public Criteria andF_limit_numberLessThanOrEqualTo(Integer value) {
            addCriterion("f_limit_number <=", value, "f_limit_number");
            return (Criteria) this;
        }

        public Criteria andF_limit_numberIn(List<Integer> values) {
            addCriterion("f_limit_number in", values, "f_limit_number");
            return (Criteria) this;
        }

        public Criteria andF_limit_numberNotIn(List<Integer> values) {
            addCriterion("f_limit_number not in", values, "f_limit_number");
            return (Criteria) this;
        }

        public Criteria andF_limit_numberBetween(Integer value1, Integer value2) {
            addCriterion("f_limit_number between", value1, value2, "f_limit_number");
            return (Criteria) this;
        }

        public Criteria andF_limit_numberNotBetween(Integer value1, Integer value2) {
            addCriterion("f_limit_number not between", value1, value2, "f_limit_number");
            return (Criteria) this;
        }

        public Criteria andF_brand_modelIsNull() {
            addCriterion("f_brand_model is null");
            return (Criteria) this;
        }

        public Criteria andF_brand_modelIsNotNull() {
            addCriterion("f_brand_model is not null");
            return (Criteria) this;
        }

        public Criteria andF_brand_modelEqualTo(String value) {
            addCriterion("f_brand_model =", value, "f_brand_model");
            return (Criteria) this;
        }

        public Criteria andF_brand_modelNotEqualTo(String value) {
            addCriterion("f_brand_model <>", value, "f_brand_model");
            return (Criteria) this;
        }

        public Criteria andF_brand_modelGreaterThan(String value) {
            addCriterion("f_brand_model >", value, "f_brand_model");
            return (Criteria) this;
        }

        public Criteria andF_brand_modelGreaterThanOrEqualTo(String value) {
            addCriterion("f_brand_model >=", value, "f_brand_model");
            return (Criteria) this;
        }

        public Criteria andF_brand_modelLessThan(String value) {
            addCriterion("f_brand_model <", value, "f_brand_model");
            return (Criteria) this;
        }

        public Criteria andF_brand_modelLessThanOrEqualTo(String value) {
            addCriterion("f_brand_model <=", value, "f_brand_model");
            return (Criteria) this;
        }

        public Criteria andF_brand_modelLike(String value) {
            addCriterion("f_brand_model like", value, "f_brand_model");
            return (Criteria) this;
        }

        public Criteria andF_brand_modelNotLike(String value) {
            addCriterion("f_brand_model not like", value, "f_brand_model");
            return (Criteria) this;
        }

        public Criteria andF_brand_modelIn(List<String> values) {
            addCriterion("f_brand_model in", values, "f_brand_model");
            return (Criteria) this;
        }

        public Criteria andF_brand_modelNotIn(List<String> values) {
            addCriterion("f_brand_model not in", values, "f_brand_model");
            return (Criteria) this;
        }

        public Criteria andF_brand_modelBetween(String value1, String value2) {
            addCriterion("f_brand_model between", value1, value2, "f_brand_model");
            return (Criteria) this;
        }

        public Criteria andF_brand_modelNotBetween(String value1, String value2) {
            addCriterion("f_brand_model not between", value1, value2, "f_brand_model");
            return (Criteria) this;
        }

        public Criteria andF_insuerIsNull() {
            addCriterion("f_insuer is null");
            return (Criteria) this;
        }

        public Criteria andF_insuerIsNotNull() {
            addCriterion("f_insuer is not null");
            return (Criteria) this;
        }

        public Criteria andF_insuerEqualTo(String value) {
            addCriterion("f_insuer =", value, "f_insuer");
            return (Criteria) this;
        }

        public Criteria andF_insuerNotEqualTo(String value) {
            addCriterion("f_insuer <>", value, "f_insuer");
            return (Criteria) this;
        }

        public Criteria andF_insuerGreaterThan(String value) {
            addCriterion("f_insuer >", value, "f_insuer");
            return (Criteria) this;
        }

        public Criteria andF_insuerGreaterThanOrEqualTo(String value) {
            addCriterion("f_insuer >=", value, "f_insuer");
            return (Criteria) this;
        }

        public Criteria andF_insuerLessThan(String value) {
            addCriterion("f_insuer <", value, "f_insuer");
            return (Criteria) this;
        }

        public Criteria andF_insuerLessThanOrEqualTo(String value) {
            addCriterion("f_insuer <=", value, "f_insuer");
            return (Criteria) this;
        }

        public Criteria andF_insuerLike(String value) {
            addCriterion("f_insuer like", value, "f_insuer");
            return (Criteria) this;
        }

        public Criteria andF_insuerNotLike(String value) {
            addCriterion("f_insuer not like", value, "f_insuer");
            return (Criteria) this;
        }

        public Criteria andF_insuerIn(List<String> values) {
            addCriterion("f_insuer in", values, "f_insuer");
            return (Criteria) this;
        }

        public Criteria andF_insuerNotIn(List<String> values) {
            addCriterion("f_insuer not in", values, "f_insuer");
            return (Criteria) this;
        }

        public Criteria andF_insuerBetween(String value1, String value2) {
            addCriterion("f_insuer between", value1, value2, "f_insuer");
            return (Criteria) this;
        }

        public Criteria andF_insuerNotBetween(String value1, String value2) {
            addCriterion("f_insuer not between", value1, value2, "f_insuer");
            return (Criteria) this;
        }

        public Criteria andF_insuerdateIsNull() {
            addCriterion("f_insuerdate is null");
            return (Criteria) this;
        }

        public Criteria andF_insuerdateIsNotNull() {
            addCriterion("f_insuerdate is not null");
            return (Criteria) this;
        }

        public Criteria andF_insuerdateEqualTo(Integer value) {
            addCriterion("f_insuerdate =", value, "f_insuerdate");
            return (Criteria) this;
        }

        public Criteria andF_insuerdateNotEqualTo(Integer value) {
            addCriterion("f_insuerdate <>", value, "f_insuerdate");
            return (Criteria) this;
        }

        public Criteria andF_insuerdateGreaterThan(Integer value) {
            addCriterion("f_insuerdate >", value, "f_insuerdate");
            return (Criteria) this;
        }

        public Criteria andF_insuerdateGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_insuerdate >=", value, "f_insuerdate");
            return (Criteria) this;
        }

        public Criteria andF_insuerdateLessThan(Integer value) {
            addCriterion("f_insuerdate <", value, "f_insuerdate");
            return (Criteria) this;
        }

        public Criteria andF_insuerdateLessThanOrEqualTo(Integer value) {
            addCriterion("f_insuerdate <=", value, "f_insuerdate");
            return (Criteria) this;
        }

        public Criteria andF_insuerdateIn(List<Integer> values) {
            addCriterion("f_insuerdate in", values, "f_insuerdate");
            return (Criteria) this;
        }

        public Criteria andF_insuerdateNotIn(List<Integer> values) {
            addCriterion("f_insuerdate not in", values, "f_insuerdate");
            return (Criteria) this;
        }

        public Criteria andF_insuerdateBetween(Integer value1, Integer value2) {
            addCriterion("f_insuerdate between", value1, value2, "f_insuerdate");
            return (Criteria) this;
        }

        public Criteria andF_insuerdateNotBetween(Integer value1, Integer value2) {
            addCriterion("f_insuerdate not between", value1, value2, "f_insuerdate");
            return (Criteria) this;
        }

        public Criteria andF_createidIsNull() {
            addCriterion("f_createid is null");
            return (Criteria) this;
        }

        public Criteria andF_createidIsNotNull() {
            addCriterion("f_createid is not null");
            return (Criteria) this;
        }

        public Criteria andF_createidEqualTo(String value) {
            addCriterion("f_createid =", value, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidNotEqualTo(String value) {
            addCriterion("f_createid <>", value, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidGreaterThan(String value) {
            addCriterion("f_createid >", value, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidGreaterThanOrEqualTo(String value) {
            addCriterion("f_createid >=", value, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidLessThan(String value) {
            addCriterion("f_createid <", value, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidLessThanOrEqualTo(String value) {
            addCriterion("f_createid <=", value, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidLike(String value) {
            addCriterion("f_createid like", value, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidNotLike(String value) {
            addCriterion("f_createid not like", value, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidIn(List<String> values) {
            addCriterion("f_createid in", values, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidNotIn(List<String> values) {
            addCriterion("f_createid not in", values, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidBetween(String value1, String value2) {
            addCriterion("f_createid between", value1, value2, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_createidNotBetween(String value1, String value2) {
            addCriterion("f_createid not between", value1, value2, "f_createid");
            return (Criteria) this;
        }

        public Criteria andF_creatorIsNull() {
            addCriterion("f_creator is null");
            return (Criteria) this;
        }

        public Criteria andF_creatorIsNotNull() {
            addCriterion("f_creator is not null");
            return (Criteria) this;
        }

        public Criteria andF_creatorEqualTo(String value) {
            addCriterion("f_creator =", value, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorNotEqualTo(String value) {
            addCriterion("f_creator <>", value, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorGreaterThan(String value) {
            addCriterion("f_creator >", value, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorGreaterThanOrEqualTo(String value) {
            addCriterion("f_creator >=", value, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorLessThan(String value) {
            addCriterion("f_creator <", value, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorLessThanOrEqualTo(String value) {
            addCriterion("f_creator <=", value, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorLike(String value) {
            addCriterion("f_creator like", value, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorNotLike(String value) {
            addCriterion("f_creator not like", value, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorIn(List<String> values) {
            addCriterion("f_creator in", values, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorNotIn(List<String> values) {
            addCriterion("f_creator not in", values, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorBetween(String value1, String value2) {
            addCriterion("f_creator between", value1, value2, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_creatorNotBetween(String value1, String value2) {
            addCriterion("f_creator not between", value1, value2, "f_creator");
            return (Criteria) this;
        }

        public Criteria andF_editoridIsNull() {
            addCriterion("f_editorid is null");
            return (Criteria) this;
        }

        public Criteria andF_editoridIsNotNull() {
            addCriterion("f_editorid is not null");
            return (Criteria) this;
        }

        public Criteria andF_editoridEqualTo(String value) {
            addCriterion("f_editorid =", value, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridNotEqualTo(String value) {
            addCriterion("f_editorid <>", value, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridGreaterThan(String value) {
            addCriterion("f_editorid >", value, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridGreaterThanOrEqualTo(String value) {
            addCriterion("f_editorid >=", value, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridLessThan(String value) {
            addCriterion("f_editorid <", value, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridLessThanOrEqualTo(String value) {
            addCriterion("f_editorid <=", value, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridLike(String value) {
            addCriterion("f_editorid like", value, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridNotLike(String value) {
            addCriterion("f_editorid not like", value, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridIn(List<String> values) {
            addCriterion("f_editorid in", values, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridNotIn(List<String> values) {
            addCriterion("f_editorid not in", values, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridBetween(String value1, String value2) {
            addCriterion("f_editorid between", value1, value2, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editoridNotBetween(String value1, String value2) {
            addCriterion("f_editorid not between", value1, value2, "f_editorid");
            return (Criteria) this;
        }

        public Criteria andF_editorIsNull() {
            addCriterion("f_editor is null");
            return (Criteria) this;
        }

        public Criteria andF_editorIsNotNull() {
            addCriterion("f_editor is not null");
            return (Criteria) this;
        }

        public Criteria andF_editorEqualTo(String value) {
            addCriterion("f_editor =", value, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorNotEqualTo(String value) {
            addCriterion("f_editor <>", value, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorGreaterThan(String value) {
            addCriterion("f_editor >", value, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorGreaterThanOrEqualTo(String value) {
            addCriterion("f_editor >=", value, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorLessThan(String value) {
            addCriterion("f_editor <", value, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorLessThanOrEqualTo(String value) {
            addCriterion("f_editor <=", value, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorLike(String value) {
            addCriterion("f_editor like", value, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorNotLike(String value) {
            addCriterion("f_editor not like", value, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorIn(List<String> values) {
            addCriterion("f_editor in", values, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorNotIn(List<String> values) {
            addCriterion("f_editor not in", values, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorBetween(String value1, String value2) {
            addCriterion("f_editor between", value1, value2, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_editorNotBetween(String value1, String value2) {
            addCriterion("f_editor not between", value1, value2, "f_editor");
            return (Criteria) this;
        }

        public Criteria andF_initdateIsNull() {
            addCriterion("f_initdate is null");
            return (Criteria) this;
        }

        public Criteria andF_initdateIsNotNull() {
            addCriterion("f_initdate is not null");
            return (Criteria) this;
        }

        public Criteria andF_initdateEqualTo(Integer value) {
            addCriterion("f_initdate =", value, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateNotEqualTo(Integer value) {
            addCriterion("f_initdate <>", value, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateGreaterThan(Integer value) {
            addCriterion("f_initdate >", value, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_initdate >=", value, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateLessThan(Integer value) {
            addCriterion("f_initdate <", value, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateLessThanOrEqualTo(Integer value) {
            addCriterion("f_initdate <=", value, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateIn(List<Integer> values) {
            addCriterion("f_initdate in", values, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateNotIn(List<Integer> values) {
            addCriterion("f_initdate not in", values, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateBetween(Integer value1, Integer value2) {
            addCriterion("f_initdate between", value1, value2, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_initdateNotBetween(Integer value1, Integer value2) {
            addCriterion("f_initdate not between", value1, value2, "f_initdate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateIsNull() {
            addCriterion("f_updatedate is null");
            return (Criteria) this;
        }

        public Criteria andF_updatedateIsNotNull() {
            addCriterion("f_updatedate is not null");
            return (Criteria) this;
        }

        public Criteria andF_updatedateEqualTo(Integer value) {
            addCriterion("f_updatedate =", value, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateNotEqualTo(Integer value) {
            addCriterion("f_updatedate <>", value, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateGreaterThan(Integer value) {
            addCriterion("f_updatedate >", value, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_updatedate >=", value, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateLessThan(Integer value) {
            addCriterion("f_updatedate <", value, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateLessThanOrEqualTo(Integer value) {
            addCriterion("f_updatedate <=", value, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateIn(List<Integer> values) {
            addCriterion("f_updatedate in", values, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateNotIn(List<Integer> values) {
            addCriterion("f_updatedate not in", values, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateBetween(Integer value1, Integer value2) {
            addCriterion("f_updatedate between", value1, value2, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_updatedateNotBetween(Integer value1, Integer value2) {
            addCriterion("f_updatedate not between", value1, value2, "f_updatedate");
            return (Criteria) this;
        }

        public Criteria andF_inspection_dateIsNull() {
            addCriterion("f_inspection_date is null");
            return (Criteria) this;
        }

        public Criteria andF_inspection_dateIsNotNull() {
            addCriterion("f_inspection_date is not null");
            return (Criteria) this;
        }

        public Criteria andF_inspection_dateEqualTo(Integer value) {
            addCriterion("f_inspection_date =", value, "f_inspection_date");
            return (Criteria) this;
        }

        public Criteria andF_inspection_dateNotEqualTo(Integer value) {
            addCriterion("f_inspection_date <>", value, "f_inspection_date");
            return (Criteria) this;
        }

        public Criteria andF_inspection_dateGreaterThan(Integer value) {
            addCriterion("f_inspection_date >", value, "f_inspection_date");
            return (Criteria) this;
        }

        public Criteria andF_inspection_dateGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_inspection_date >=", value, "f_inspection_date");
            return (Criteria) this;
        }

        public Criteria andF_inspection_dateLessThan(Integer value) {
            addCriterion("f_inspection_date <", value, "f_inspection_date");
            return (Criteria) this;
        }

        public Criteria andF_inspection_dateLessThanOrEqualTo(Integer value) {
            addCriterion("f_inspection_date <=", value, "f_inspection_date");
            return (Criteria) this;
        }

        public Criteria andF_inspection_dateIn(List<Integer> values) {
            addCriterion("f_inspection_date in", values, "f_inspection_date");
            return (Criteria) this;
        }

        public Criteria andF_inspection_dateNotIn(List<Integer> values) {
            addCriterion("f_inspection_date not in", values, "f_inspection_date");
            return (Criteria) this;
        }

        public Criteria andF_inspection_dateBetween(Integer value1, Integer value2) {
            addCriterion("f_inspection_date between", value1, value2, "f_inspection_date");
            return (Criteria) this;
        }

        public Criteria andF_inspection_dateNotBetween(Integer value1, Integer value2) {
            addCriterion("f_inspection_date not between", value1, value2, "f_inspection_date");
            return (Criteria) this;
        }

        public Criteria andF_checkedIsNull() {
            addCriterion("f_checked is null");
            return (Criteria) this;
        }

        public Criteria andF_checkedIsNotNull() {
            addCriterion("f_checked is not null");
            return (Criteria) this;
        }

        public Criteria andF_checkedEqualTo(Boolean value) {
            addCriterion("f_checked =", value, "f_checked");
            return (Criteria) this;
        }

        public Criteria andF_checkedNotEqualTo(Boolean value) {
            addCriterion("f_checked <>", value, "f_checked");
            return (Criteria) this;
        }

        public Criteria andF_checkedGreaterThan(Boolean value) {
            addCriterion("f_checked >", value, "f_checked");
            return (Criteria) this;
        }

        public Criteria andF_checkedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("f_checked >=", value, "f_checked");
            return (Criteria) this;
        }

        public Criteria andF_checkedLessThan(Boolean value) {
            addCriterion("f_checked <", value, "f_checked");
            return (Criteria) this;
        }

        public Criteria andF_checkedLessThanOrEqualTo(Boolean value) {
            addCriterion("f_checked <=", value, "f_checked");
            return (Criteria) this;
        }

        public Criteria andF_checkedIn(List<Boolean> values) {
            addCriterion("f_checked in", values, "f_checked");
            return (Criteria) this;
        }

        public Criteria andF_checkedNotIn(List<Boolean> values) {
            addCriterion("f_checked not in", values, "f_checked");
            return (Criteria) this;
        }

        public Criteria andF_checkedBetween(Boolean value1, Boolean value2) {
            addCriterion("f_checked between", value1, value2, "f_checked");
            return (Criteria) this;
        }

        public Criteria andF_checkedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("f_checked not between", value1, value2, "f_checked");
            return (Criteria) this;
        }

        public Criteria andF_ccid1IsNull() {
            addCriterion("f_ccid1 is null");
            return (Criteria) this;
        }

        public Criteria andF_ccid1IsNotNull() {
            addCriterion("f_ccid1 is not null");
            return (Criteria) this;
        }

        public Criteria andF_ccid1EqualTo(Short value) {
            addCriterion("f_ccid1 =", value, "f_ccid1");
            return (Criteria) this;
        }

        public Criteria andF_ccid1NotEqualTo(Short value) {
            addCriterion("f_ccid1 <>", value, "f_ccid1");
            return (Criteria) this;
        }

        public Criteria andF_ccid1GreaterThan(Short value) {
            addCriterion("f_ccid1 >", value, "f_ccid1");
            return (Criteria) this;
        }

        public Criteria andF_ccid1GreaterThanOrEqualTo(Short value) {
            addCriterion("f_ccid1 >=", value, "f_ccid1");
            return (Criteria) this;
        }

        public Criteria andF_ccid1LessThan(Short value) {
            addCriterion("f_ccid1 <", value, "f_ccid1");
            return (Criteria) this;
        }

        public Criteria andF_ccid1LessThanOrEqualTo(Short value) {
            addCriterion("f_ccid1 <=", value, "f_ccid1");
            return (Criteria) this;
        }

        public Criteria andF_ccid1In(List<Short> values) {
            addCriterion("f_ccid1 in", values, "f_ccid1");
            return (Criteria) this;
        }

        public Criteria andF_ccid1NotIn(List<Short> values) {
            addCriterion("f_ccid1 not in", values, "f_ccid1");
            return (Criteria) this;
        }

        public Criteria andF_ccid1Between(Short value1, Short value2) {
            addCriterion("f_ccid1 between", value1, value2, "f_ccid1");
            return (Criteria) this;
        }

        public Criteria andF_ccid1NotBetween(Short value1, Short value2) {
            addCriterion("f_ccid1 not between", value1, value2, "f_ccid1");
            return (Criteria) this;
        }

        public Criteria andF_closedIsNull() {
            addCriterion("f_closed is null");
            return (Criteria) this;
        }

        public Criteria andF_closedIsNotNull() {
            addCriterion("f_closed is not null");
            return (Criteria) this;
        }

        public Criteria andF_closedEqualTo(Boolean value) {
            addCriterion("f_closed =", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedNotEqualTo(Boolean value) {
            addCriterion("f_closed <>", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedGreaterThan(Boolean value) {
            addCriterion("f_closed >", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("f_closed >=", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedLessThan(Boolean value) {
            addCriterion("f_closed <", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedLessThanOrEqualTo(Boolean value) {
            addCriterion("f_closed <=", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedIn(List<Boolean> values) {
            addCriterion("f_closed in", values, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedNotIn(List<Boolean> values) {
            addCriterion("f_closed not in", values, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedBetween(Boolean value1, Boolean value2) {
            addCriterion("f_closed between", value1, value2, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("f_closed not between", value1, value2, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_purchasedateIsNull() {
            addCriterion("f_purchasedate is null");
            return (Criteria) this;
        }

        public Criteria andF_purchasedateIsNotNull() {
            addCriterion("f_purchasedate is not null");
            return (Criteria) this;
        }

        public Criteria andF_purchasedateEqualTo(Integer value) {
            addCriterion("f_purchasedate =", value, "f_purchasedate");
            return (Criteria) this;
        }

        public Criteria andF_purchasedateNotEqualTo(Integer value) {
            addCriterion("f_purchasedate <>", value, "f_purchasedate");
            return (Criteria) this;
        }

        public Criteria andF_purchasedateGreaterThan(Integer value) {
            addCriterion("f_purchasedate >", value, "f_purchasedate");
            return (Criteria) this;
        }

        public Criteria andF_purchasedateGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_purchasedate >=", value, "f_purchasedate");
            return (Criteria) this;
        }

        public Criteria andF_purchasedateLessThan(Integer value) {
            addCriterion("f_purchasedate <", value, "f_purchasedate");
            return (Criteria) this;
        }

        public Criteria andF_purchasedateLessThanOrEqualTo(Integer value) {
            addCriterion("f_purchasedate <=", value, "f_purchasedate");
            return (Criteria) this;
        }

        public Criteria andF_purchasedateIn(List<Integer> values) {
            addCriterion("f_purchasedate in", values, "f_purchasedate");
            return (Criteria) this;
        }

        public Criteria andF_purchasedateNotIn(List<Integer> values) {
            addCriterion("f_purchasedate not in", values, "f_purchasedate");
            return (Criteria) this;
        }

        public Criteria andF_purchasedateBetween(Integer value1, Integer value2) {
            addCriterion("f_purchasedate between", value1, value2, "f_purchasedate");
            return (Criteria) this;
        }

        public Criteria andF_purchasedateNotBetween(Integer value1, Integer value2) {
            addCriterion("f_purchasedate not between", value1, value2, "f_purchasedate");
            return (Criteria) this;
        }

        public Criteria andF_mileageIsNull() {
            addCriterion("f_mileage is null");
            return (Criteria) this;
        }

        public Criteria andF_mileageIsNotNull() {
            addCriterion("f_mileage is not null");
            return (Criteria) this;
        }

        public Criteria andF_mileageEqualTo(Float value) {
            addCriterion("f_mileage =", value, "f_mileage");
            return (Criteria) this;
        }

        public Criteria andF_mileageNotEqualTo(Float value) {
            addCriterion("f_mileage <>", value, "f_mileage");
            return (Criteria) this;
        }

        public Criteria andF_mileageGreaterThan(Float value) {
            addCriterion("f_mileage >", value, "f_mileage");
            return (Criteria) this;
        }

        public Criteria andF_mileageGreaterThanOrEqualTo(Float value) {
            addCriterion("f_mileage >=", value, "f_mileage");
            return (Criteria) this;
        }

        public Criteria andF_mileageLessThan(Float value) {
            addCriterion("f_mileage <", value, "f_mileage");
            return (Criteria) this;
        }

        public Criteria andF_mileageLessThanOrEqualTo(Float value) {
            addCriterion("f_mileage <=", value, "f_mileage");
            return (Criteria) this;
        }

        public Criteria andF_mileageIn(List<Float> values) {
            addCriterion("f_mileage in", values, "f_mileage");
            return (Criteria) this;
        }

        public Criteria andF_mileageNotIn(List<Float> values) {
            addCriterion("f_mileage not in", values, "f_mileage");
            return (Criteria) this;
        }

        public Criteria andF_mileageBetween(Float value1, Float value2) {
            addCriterion("f_mileage between", value1, value2, "f_mileage");
            return (Criteria) this;
        }

        public Criteria andF_mileageNotBetween(Float value1, Float value2) {
            addCriterion("f_mileage not between", value1, value2, "f_mileage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 23 09:57:15 CST 2015
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_dm_vehicle
     *
     * @mbggenerated Thu Apr 23 09:57:15 CST 2015
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}