package com.etong.pt.data.user;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PtUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    int countByExample(PtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    int deleteByExample(PtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    int deleteByPrimaryKey(Integer f_mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    int insert(PtUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    int insertSelective(PtUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    List<PtUser> selectByExample(PtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    PtUser selectByPrimaryKey(Integer f_mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    int updateByExampleSelective(@Param("record") PtUser record, @Param("example") PtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    int updateByExample(@Param("record") PtUser record, @Param("example") PtUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    int updateByPrimaryKeySelective(PtUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    int updateByPrimaryKey(PtUser record);
}