package com.etong.pt.data.user;

import com.etong.pt.utility.PageLimit;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class PtUserExample extends PageLimit implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    public PtUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andF_midIsNull() {
            addCriterion("f_mid is null");
            return (Criteria) this;
        }

        public Criteria andF_midIsNotNull() {
            addCriterion("f_mid is not null");
            return (Criteria) this;
        }

        public Criteria andF_midEqualTo(Integer value) {
            addCriterion("f_mid =", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midNotEqualTo(Integer value) {
            addCriterion("f_mid <>", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midGreaterThan(Integer value) {
            addCriterion("f_mid >", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_mid >=", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midLessThan(Integer value) {
            addCriterion("f_mid <", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midLessThanOrEqualTo(Integer value) {
            addCriterion("f_mid <=", value, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midIn(List<Integer> values) {
            addCriterion("f_mid in", values, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midNotIn(List<Integer> values) {
            addCriterion("f_mid not in", values, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midBetween(Integer value1, Integer value2) {
            addCriterion("f_mid between", value1, value2, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_midNotBetween(Integer value1, Integer value2) {
            addCriterion("f_mid not between", value1, value2, "f_mid");
            return (Criteria) this;
        }

        public Criteria andF_nameIsNull() {
            addCriterion("f_name is null");
            return (Criteria) this;
        }

        public Criteria andF_nameIsNotNull() {
            addCriterion("f_name is not null");
            return (Criteria) this;
        }

        public Criteria andF_nameEqualTo(String value) {
            addCriterion("f_name =", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameNotEqualTo(String value) {
            addCriterion("f_name <>", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameGreaterThan(String value) {
            addCriterion("f_name >", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameGreaterThanOrEqualTo(String value) {
            addCriterion("f_name >=", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameLessThan(String value) {
            addCriterion("f_name <", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameLessThanOrEqualTo(String value) {
            addCriterion("f_name <=", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameLike(String value) {
            addCriterion("f_name like", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameNotLike(String value) {
            addCriterion("f_name not like", value, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameIn(List<String> values) {
            addCriterion("f_name in", values, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameNotIn(List<String> values) {
            addCriterion("f_name not in", values, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameBetween(String value1, String value2) {
            addCriterion("f_name between", value1, value2, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_nameNotBetween(String value1, String value2) {
            addCriterion("f_name not between", value1, value2, "f_name");
            return (Criteria) this;
        }

        public Criteria andF_passwordIsNull() {
            addCriterion("f_password is null");
            return (Criteria) this;
        }

        public Criteria andF_passwordIsNotNull() {
            addCriterion("f_password is not null");
            return (Criteria) this;
        }

        public Criteria andF_passwordEqualTo(String value) {
            addCriterion("f_password =", value, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordNotEqualTo(String value) {
            addCriterion("f_password <>", value, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordGreaterThan(String value) {
            addCriterion("f_password >", value, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordGreaterThanOrEqualTo(String value) {
            addCriterion("f_password >=", value, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordLessThan(String value) {
            addCriterion("f_password <", value, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordLessThanOrEqualTo(String value) {
            addCriterion("f_password <=", value, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordLike(String value) {
            addCriterion("f_password like", value, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordNotLike(String value) {
            addCriterion("f_password not like", value, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordIn(List<String> values) {
            addCriterion("f_password in", values, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordNotIn(List<String> values) {
            addCriterion("f_password not in", values, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordBetween(String value1, String value2) {
            addCriterion("f_password between", value1, value2, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_passwordNotBetween(String value1, String value2) {
            addCriterion("f_password not between", value1, value2, "f_password");
            return (Criteria) this;
        }

        public Criteria andF_saltIsNull() {
            addCriterion("f_salt is null");
            return (Criteria) this;
        }

        public Criteria andF_saltIsNotNull() {
            addCriterion("f_salt is not null");
            return (Criteria) this;
        }

        public Criteria andF_saltEqualTo(String value) {
            addCriterion("f_salt =", value, "f_salt");
            return (Criteria) this;
        }

        public Criteria andF_saltNotEqualTo(String value) {
            addCriterion("f_salt <>", value, "f_salt");
            return (Criteria) this;
        }

        public Criteria andF_saltGreaterThan(String value) {
            addCriterion("f_salt >", value, "f_salt");
            return (Criteria) this;
        }

        public Criteria andF_saltGreaterThanOrEqualTo(String value) {
            addCriterion("f_salt >=", value, "f_salt");
            return (Criteria) this;
        }

        public Criteria andF_saltLessThan(String value) {
            addCriterion("f_salt <", value, "f_salt");
            return (Criteria) this;
        }

        public Criteria andF_saltLessThanOrEqualTo(String value) {
            addCriterion("f_salt <=", value, "f_salt");
            return (Criteria) this;
        }

        public Criteria andF_saltLike(String value) {
            addCriterion("f_salt like", value, "f_salt");
            return (Criteria) this;
        }

        public Criteria andF_saltNotLike(String value) {
            addCriterion("f_salt not like", value, "f_salt");
            return (Criteria) this;
        }

        public Criteria andF_saltIn(List<String> values) {
            addCriterion("f_salt in", values, "f_salt");
            return (Criteria) this;
        }

        public Criteria andF_saltNotIn(List<String> values) {
            addCriterion("f_salt not in", values, "f_salt");
            return (Criteria) this;
        }

        public Criteria andF_saltBetween(String value1, String value2) {
            addCriterion("f_salt between", value1, value2, "f_salt");
            return (Criteria) this;
        }

        public Criteria andF_saltNotBetween(String value1, String value2) {
            addCriterion("f_salt not between", value1, value2, "f_salt");
            return (Criteria) this;
        }

        public Criteria andF_emailIsNull() {
            addCriterion("f_email is null");
            return (Criteria) this;
        }

        public Criteria andF_emailIsNotNull() {
            addCriterion("f_email is not null");
            return (Criteria) this;
        }

        public Criteria andF_emailEqualTo(String value) {
            addCriterion("f_email =", value, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailNotEqualTo(String value) {
            addCriterion("f_email <>", value, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailGreaterThan(String value) {
            addCriterion("f_email >", value, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailGreaterThanOrEqualTo(String value) {
            addCriterion("f_email >=", value, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailLessThan(String value) {
            addCriterion("f_email <", value, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailLessThanOrEqualTo(String value) {
            addCriterion("f_email <=", value, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailLike(String value) {
            addCriterion("f_email like", value, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailNotLike(String value) {
            addCriterion("f_email not like", value, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailIn(List<String> values) {
            addCriterion("f_email in", values, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailNotIn(List<String> values) {
            addCriterion("f_email not in", values, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailBetween(String value1, String value2) {
            addCriterion("f_email between", value1, value2, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_emailNotBetween(String value1, String value2) {
            addCriterion("f_email not between", value1, value2, "f_email");
            return (Criteria) this;
        }

        public Criteria andF_phoneIsNull() {
            addCriterion("f_phone is null");
            return (Criteria) this;
        }

        public Criteria andF_phoneIsNotNull() {
            addCriterion("f_phone is not null");
            return (Criteria) this;
        }

        public Criteria andF_phoneEqualTo(String value) {
            addCriterion("f_phone =", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotEqualTo(String value) {
            addCriterion("f_phone <>", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneGreaterThan(String value) {
            addCriterion("f_phone >", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneGreaterThanOrEqualTo(String value) {
            addCriterion("f_phone >=", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneLessThan(String value) {
            addCriterion("f_phone <", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneLessThanOrEqualTo(String value) {
            addCriterion("f_phone <=", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneLike(String value) {
            addCriterion("f_phone like", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotLike(String value) {
            addCriterion("f_phone not like", value, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneIn(List<String> values) {
            addCriterion("f_phone in", values, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotIn(List<String> values) {
            addCriterion("f_phone not in", values, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneBetween(String value1, String value2) {
            addCriterion("f_phone between", value1, value2, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_phoneNotBetween(String value1, String value2) {
            addCriterion("f_phone not between", value1, value2, "f_phone");
            return (Criteria) this;
        }

        public Criteria andF_verifyIsNull() {
            addCriterion("f_verify is null");
            return (Criteria) this;
        }

        public Criteria andF_verifyIsNotNull() {
            addCriterion("f_verify is not null");
            return (Criteria) this;
        }

        public Criteria andF_verifyEqualTo(Boolean value) {
            addCriterion("f_verify =", value, "f_verify");
            return (Criteria) this;
        }

        public Criteria andF_verifyNotEqualTo(Boolean value) {
            addCriterion("f_verify <>", value, "f_verify");
            return (Criteria) this;
        }

        public Criteria andF_verifyGreaterThan(Boolean value) {
            addCriterion("f_verify >", value, "f_verify");
            return (Criteria) this;
        }

        public Criteria andF_verifyGreaterThanOrEqualTo(Boolean value) {
            addCriterion("f_verify >=", value, "f_verify");
            return (Criteria) this;
        }

        public Criteria andF_verifyLessThan(Boolean value) {
            addCriterion("f_verify <", value, "f_verify");
            return (Criteria) this;
        }

        public Criteria andF_verifyLessThanOrEqualTo(Boolean value) {
            addCriterion("f_verify <=", value, "f_verify");
            return (Criteria) this;
        }

        public Criteria andF_verifyIn(List<Boolean> values) {
            addCriterion("f_verify in", values, "f_verify");
            return (Criteria) this;
        }

        public Criteria andF_verifyNotIn(List<Boolean> values) {
            addCriterion("f_verify not in", values, "f_verify");
            return (Criteria) this;
        }

        public Criteria andF_verifyBetween(Boolean value1, Boolean value2) {
            addCriterion("f_verify between", value1, value2, "f_verify");
            return (Criteria) this;
        }

        public Criteria andF_verifyNotBetween(Boolean value1, Boolean value2) {
            addCriterion("f_verify not between", value1, value2, "f_verify");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_um_users
     *
     * @mbggenerated do_not_delete_during_merge Mon May 18 15:24:58 CST 2015
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_um_users
     *
     * @mbggenerated Mon May 18 15:24:58 CST 2015
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}