package com.etong.data.auto.car;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_vm_list
     *
     * @mbggenerated Fri Nov 13 15:59:31 CST 2015
     */
    int countByExample(CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_vm_list
     *
     * @mbggenerated Fri Nov 13 15:59:31 CST 2015
     */
    int deleteByExample(CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_vm_list
     *
     * @mbggenerated Fri Nov 13 15:59:31 CST 2015
     */
    int insert(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_vm_list
     *
     * @mbggenerated Fri Nov 13 15:59:31 CST 2015
     */
    int insertSelective(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_vm_list
     *
     * @mbggenerated Fri Nov 13 15:59:31 CST 2015
     */
    List<Car> selectByExample(CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_vm_list
     *
     * @mbggenerated Fri Nov 13 15:59:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") Car record, @Param("example") CarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_vm_list
     *
     * @mbggenerated Fri Nov 13 15:59:31 CST 2015
     */
    int updateByExample(@Param("record") Car record, @Param("example") CarExample example);
}