package com.etong.data.auth.userresource;

import java.io.Serializable;

public class UserResource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm_useresource.f_id
     *
     * @mbggenerated Mon Nov 23 10:25:11 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm_useresource.f_mid
     *
     * @mbggenerated Mon Nov 23 10:25:11 CST 2015
     */
    private Long mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm_useresource.f_rsid
     *
     * @mbggenerated Mon Nov 23 10:25:11 CST 2015
     */
    private Long rsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm_useresource.f_available
     *
     * @mbggenerated Mon Nov 23 10:25:11 CST 2015
     */
    private Boolean available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm_useresource.f_stid
     *
     * @mbggenerated Mon Nov 23 10:25:11 CST 2015
     */
    private String stid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm_useresource.f_id
     *
     * @return the value of t_pm_useresource.f_id
     * @mbggenerated Mon Nov 23 10:25:11 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm_useresource.f_id
     *
     * @param id the value for t_pm_useresource.f_id
     * @mbggenerated Mon Nov 23 10:25:11 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm_useresource.f_mid
     *
     * @return the value of t_pm_useresource.f_mid
     * @mbggenerated Mon Nov 23 10:25:11 CST 2015
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm_useresource.f_mid
     *
     * @param mid the value for t_pm_useresource.f_mid
     * @mbggenerated Mon Nov 23 10:25:11 CST 2015
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm_useresource.f_rsid
     *
     * @return the value of t_pm_useresource.f_rsid
     * @mbggenerated Mon Nov 23 10:25:11 CST 2015
     */
    public Long getRsid() {
        return rsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm_useresource.f_rsid
     *
     * @param rsid the value for t_pm_useresource.f_rsid
     * @mbggenerated Mon Nov 23 10:25:11 CST 2015
     */
    public void setRsid(Long rsid) {
        this.rsid = rsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm_useresource.f_available
     *
     * @return the value of t_pm_useresource.f_available
     * @mbggenerated Mon Nov 23 10:25:11 CST 2015
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm_useresource.f_available
     *
     * @param available the value for t_pm_useresource.f_available
     * @mbggenerated Mon Nov 23 10:25:11 CST 2015
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm_useresource.f_stid
     *
     * @return the value of t_pm_useresource.f_stid
     * @mbggenerated Mon Nov 23 10:25:11 CST 2015
     */
    public String getStid() {
        return stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm_useresource.f_stid
     *
     * @param stid the value for t_pm_useresource.f_stid
     * @mbggenerated Mon Nov 23 10:25:11 CST 2015
     */
    public void setStid(String stid) {
        this.stid = stid;
    }

    @Override
    public String toString() {
        return "UserResource{" +
                "id=" + id +
                ", mid=" + mid +
                ", rsid=" + rsid +
                ", available=" + available +
                ", stid='" + stid + '\'' +
                '}';
    }
}