package com.etong.data.auth.userrole;

import java.io.Serializable;

public class UserRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm_userrole.f_id
     *
     * @mbggenerated Mon Nov 23 10:27:17 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm_userrole.f_mid
     *
     * @mbggenerated Mon Nov 23 10:27:17 CST 2015
     */
    private Long mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm_userrole.f_rlid
     *
     * @mbggenerated Mon Nov 23 10:27:17 CST 2015
     */
    private Long rlid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm_userrole.f_available
     *
     * @mbggenerated Mon Nov 23 10:27:17 CST 2015
     */
    private Boolean available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pm_userrole.f_stid
     *
     * @mbggenerated Mon Nov 23 10:27:17 CST 2015
     */
    private String stid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm_userrole.f_id
     *
     * @return the value of t_pm_userrole.f_id
     * @mbggenerated Mon Nov 23 10:27:17 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm_userrole.f_id
     *
     * @param id the value for t_pm_userrole.f_id
     * @mbggenerated Mon Nov 23 10:27:17 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm_userrole.f_mid
     *
     * @return the value of t_pm_userrole.f_mid
     * @mbggenerated Mon Nov 23 10:27:17 CST 2015
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm_userrole.f_mid
     *
     * @param mid the value for t_pm_userrole.f_mid
     * @mbggenerated Mon Nov 23 10:27:17 CST 2015
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm_userrole.f_rlid
     *
     * @return the value of t_pm_userrole.f_rlid
     * @mbggenerated Mon Nov 23 10:27:17 CST 2015
     */
    public Long getRlid() {
        return rlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm_userrole.f_rlid
     *
     * @param rlid the value for t_pm_userrole.f_rlid
     * @mbggenerated Mon Nov 23 10:27:17 CST 2015
     */
    public void setRlid(Long rlid) {
        this.rlid = rlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm_userrole.f_available
     *
     * @return the value of t_pm_userrole.f_available
     * @mbggenerated Mon Nov 23 10:27:17 CST 2015
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm_userrole.f_available
     *
     * @param available the value for t_pm_userrole.f_available
     * @mbggenerated Mon Nov 23 10:27:17 CST 2015
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pm_userrole.f_stid
     *
     * @return the value of t_pm_userrole.f_stid
     * @mbggenerated Mon Nov 23 10:27:17 CST 2015
     */
    public String getStid() {
        return stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pm_userrole.f_stid
     *
     * @param stid the value for t_pm_userrole.f_stid
     * @mbggenerated Mon Nov 23 10:27:17 CST 2015
     */
    public void setStid(String stid) {
        this.stid = stid;
    }
}