package com.etong.pt.data.dc;

import java.util.ArrayList;
import java.util.List;

public class DictionaryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cm_type
     *
     * @mbggenerated Mon Jun 08 15:32:53 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cm_type
     *
     * @mbggenerated Mon Jun 08 15:32:53 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cm_type
     *
     * @mbggenerated Mon Jun 08 15:32:53 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_type
     *
     * @mbggenerated Mon Jun 08 15:32:53 CST 2015
     */
    public DictionaryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_type
     *
     * @mbggenerated Mon Jun 08 15:32:53 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_type
     *
     * @mbggenerated Mon Jun 08 15:32:53 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_type
     *
     * @mbggenerated Mon Jun 08 15:32:53 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_type
     *
     * @mbggenerated Mon Jun 08 15:32:53 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_type
     *
     * @mbggenerated Mon Jun 08 15:32:53 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_type
     *
     * @mbggenerated Mon Jun 08 15:32:53 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_type
     *
     * @mbggenerated Mon Jun 08 15:32:53 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_type
     *
     * @mbggenerated Mon Jun 08 15:32:53 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_type
     *
     * @mbggenerated Mon Jun 08 15:32:53 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cm_type
     *
     * @mbggenerated Mon Jun 08 15:32:53 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cm_type
     *
     * @mbggenerated Mon Jun 08 15:32:53 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andF_idIsNull() {
            addCriterion("f_id is null");
            return (Criteria) this;
        }

        public Criteria andF_idIsNotNull() {
            addCriterion("f_id is not null");
            return (Criteria) this;
        }

        public Criteria andF_idEqualTo(Short value) {
            addCriterion("f_id =", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotEqualTo(Short value) {
            addCriterion("f_id <>", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idGreaterThan(Short value) {
            addCriterion("f_id >", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idGreaterThanOrEqualTo(Short value) {
            addCriterion("f_id >=", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idLessThan(Short value) {
            addCriterion("f_id <", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idLessThanOrEqualTo(Short value) {
            addCriterion("f_id <=", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idIn(List<Short> values) {
            addCriterion("f_id in", values, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotIn(List<Short> values) {
            addCriterion("f_id not in", values, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idBetween(Short value1, Short value2) {
            addCriterion("f_id between", value1, value2, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotBetween(Short value1, Short value2) {
            addCriterion("f_id not between", value1, value2, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_pidIsNull() {
            addCriterion("f_pid is null");
            return (Criteria) this;
        }

        public Criteria andF_pidIsNotNull() {
            addCriterion("f_pid is not null");
            return (Criteria) this;
        }

        public Criteria andF_pidEqualTo(Short value) {
            addCriterion("f_pid =", value, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidNotEqualTo(Short value) {
            addCriterion("f_pid <>", value, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidGreaterThan(Short value) {
            addCriterion("f_pid >", value, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidGreaterThanOrEqualTo(Short value) {
            addCriterion("f_pid >=", value, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidLessThan(Short value) {
            addCriterion("f_pid <", value, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidLessThanOrEqualTo(Short value) {
            addCriterion("f_pid <=", value, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidIn(List<Short> values) {
            addCriterion("f_pid in", values, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidNotIn(List<Short> values) {
            addCriterion("f_pid not in", values, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidBetween(Short value1, Short value2) {
            addCriterion("f_pid between", value1, value2, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_pidNotBetween(Short value1, Short value2) {
            addCriterion("f_pid not between", value1, value2, "f_pid");
            return (Criteria) this;
        }

        public Criteria andF_levelIsNull() {
            addCriterion("f_level is null");
            return (Criteria) this;
        }

        public Criteria andF_levelIsNotNull() {
            addCriterion("f_level is not null");
            return (Criteria) this;
        }

        public Criteria andF_levelEqualTo(Byte value) {
            addCriterion("f_level =", value, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelNotEqualTo(Byte value) {
            addCriterion("f_level <>", value, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelGreaterThan(Byte value) {
            addCriterion("f_level >", value, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelGreaterThanOrEqualTo(Byte value) {
            addCriterion("f_level >=", value, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelLessThan(Byte value) {
            addCriterion("f_level <", value, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelLessThanOrEqualTo(Byte value) {
            addCriterion("f_level <=", value, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelIn(List<Byte> values) {
            addCriterion("f_level in", values, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelNotIn(List<Byte> values) {
            addCriterion("f_level not in", values, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelBetween(Byte value1, Byte value2) {
            addCriterion("f_level between", value1, value2, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_levelNotBetween(Byte value1, Byte value2) {
            addCriterion("f_level not between", value1, value2, "f_level");
            return (Criteria) this;
        }

        public Criteria andF_titleIsNull() {
            addCriterion("f_title is null");
            return (Criteria) this;
        }

        public Criteria andF_titleIsNotNull() {
            addCriterion("f_title is not null");
            return (Criteria) this;
        }

        public Criteria andF_titleEqualTo(String value) {
            addCriterion("f_title =", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleNotEqualTo(String value) {
            addCriterion("f_title <>", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleGreaterThan(String value) {
            addCriterion("f_title >", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleGreaterThanOrEqualTo(String value) {
            addCriterion("f_title >=", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleLessThan(String value) {
            addCriterion("f_title <", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleLessThanOrEqualTo(String value) {
            addCriterion("f_title <=", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleLike(String value) {
            addCriterion("f_title like", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleNotLike(String value) {
            addCriterion("f_title not like", value, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleIn(List<String> values) {
            addCriterion("f_title in", values, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleNotIn(List<String> values) {
            addCriterion("f_title not in", values, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleBetween(String value1, String value2) {
            addCriterion("f_title between", value1, value2, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_titleNotBetween(String value1, String value2) {
            addCriterion("f_title not between", value1, value2, "f_title");
            return (Criteria) this;
        }

        public Criteria andF_valueIsNull() {
            addCriterion("f_value is null");
            return (Criteria) this;
        }

        public Criteria andF_valueIsNotNull() {
            addCriterion("f_value is not null");
            return (Criteria) this;
        }

        public Criteria andF_valueEqualTo(Integer value) {
            addCriterion("f_value =", value, "f_value");
            return (Criteria) this;
        }

        public Criteria andF_valueNotEqualTo(Integer value) {
            addCriterion("f_value <>", value, "f_value");
            return (Criteria) this;
        }

        public Criteria andF_valueGreaterThan(Integer value) {
            addCriterion("f_value >", value, "f_value");
            return (Criteria) this;
        }

        public Criteria andF_valueGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_value >=", value, "f_value");
            return (Criteria) this;
        }

        public Criteria andF_valueLessThan(Integer value) {
            addCriterion("f_value <", value, "f_value");
            return (Criteria) this;
        }

        public Criteria andF_valueLessThanOrEqualTo(Integer value) {
            addCriterion("f_value <=", value, "f_value");
            return (Criteria) this;
        }

        public Criteria andF_valueIn(List<Integer> values) {
            addCriterion("f_value in", values, "f_value");
            return (Criteria) this;
        }

        public Criteria andF_valueNotIn(List<Integer> values) {
            addCriterion("f_value not in", values, "f_value");
            return (Criteria) this;
        }

        public Criteria andF_valueBetween(Integer value1, Integer value2) {
            addCriterion("f_value between", value1, value2, "f_value");
            return (Criteria) this;
        }

        public Criteria andF_valueNotBetween(Integer value1, Integer value2) {
            addCriterion("f_value not between", value1, value2, "f_value");
            return (Criteria) this;
        }

        public Criteria andF_letterIsNull() {
            addCriterion("f_letter is null");
            return (Criteria) this;
        }

        public Criteria andF_letterIsNotNull() {
            addCriterion("f_letter is not null");
            return (Criteria) this;
        }

        public Criteria andF_letterEqualTo(String value) {
            addCriterion("f_letter =", value, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterNotEqualTo(String value) {
            addCriterion("f_letter <>", value, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterGreaterThan(String value) {
            addCriterion("f_letter >", value, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterGreaterThanOrEqualTo(String value) {
            addCriterion("f_letter >=", value, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterLessThan(String value) {
            addCriterion("f_letter <", value, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterLessThanOrEqualTo(String value) {
            addCriterion("f_letter <=", value, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterLike(String value) {
            addCriterion("f_letter like", value, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterNotLike(String value) {
            addCriterion("f_letter not like", value, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterIn(List<String> values) {
            addCriterion("f_letter in", values, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterNotIn(List<String> values) {
            addCriterion("f_letter not in", values, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterBetween(String value1, String value2) {
            addCriterion("f_letter between", value1, value2, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_letterNotBetween(String value1, String value2) {
            addCriterion("f_letter not between", value1, value2, "f_letter");
            return (Criteria) this;
        }

        public Criteria andF_ctidIsNull() {
            addCriterion("f_ctid is null");
            return (Criteria) this;
        }

        public Criteria andF_ctidIsNotNull() {
            addCriterion("f_ctid is not null");
            return (Criteria) this;
        }

        public Criteria andF_ctidEqualTo(Short value) {
            addCriterion("f_ctid =", value, "f_ctid");
            return (Criteria) this;
        }

        public Criteria andF_ctidNotEqualTo(Short value) {
            addCriterion("f_ctid <>", value, "f_ctid");
            return (Criteria) this;
        }

        public Criteria andF_ctidGreaterThan(Short value) {
            addCriterion("f_ctid >", value, "f_ctid");
            return (Criteria) this;
        }

        public Criteria andF_ctidGreaterThanOrEqualTo(Short value) {
            addCriterion("f_ctid >=", value, "f_ctid");
            return (Criteria) this;
        }

        public Criteria andF_ctidLessThan(Short value) {
            addCriterion("f_ctid <", value, "f_ctid");
            return (Criteria) this;
        }

        public Criteria andF_ctidLessThanOrEqualTo(Short value) {
            addCriterion("f_ctid <=", value, "f_ctid");
            return (Criteria) this;
        }

        public Criteria andF_ctidIn(List<Short> values) {
            addCriterion("f_ctid in", values, "f_ctid");
            return (Criteria) this;
        }

        public Criteria andF_ctidNotIn(List<Short> values) {
            addCriterion("f_ctid not in", values, "f_ctid");
            return (Criteria) this;
        }

        public Criteria andF_ctidBetween(Short value1, Short value2) {
            addCriterion("f_ctid between", value1, value2, "f_ctid");
            return (Criteria) this;
        }

        public Criteria andF_ctidNotBetween(Short value1, Short value2) {
            addCriterion("f_ctid not between", value1, value2, "f_ctid");
            return (Criteria) this;
        }

        public Criteria andF_typeIsNull() {
            addCriterion("f_type is null");
            return (Criteria) this;
        }

        public Criteria andF_typeIsNotNull() {
            addCriterion("f_type is not null");
            return (Criteria) this;
        }

        public Criteria andF_typeEqualTo(String value) {
            addCriterion("f_type =", value, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeNotEqualTo(String value) {
            addCriterion("f_type <>", value, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeGreaterThan(String value) {
            addCriterion("f_type >", value, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeGreaterThanOrEqualTo(String value) {
            addCriterion("f_type >=", value, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeLessThan(String value) {
            addCriterion("f_type <", value, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeLessThanOrEqualTo(String value) {
            addCriterion("f_type <=", value, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeLike(String value) {
            addCriterion("f_type like", value, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeNotLike(String value) {
            addCriterion("f_type not like", value, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeIn(List<String> values) {
            addCriterion("f_type in", values, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeNotIn(List<String> values) {
            addCriterion("f_type not in", values, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeBetween(String value1, String value2) {
            addCriterion("f_type between", value1, value2, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_typeNotBetween(String value1, String value2) {
            addCriterion("f_type not between", value1, value2, "f_type");
            return (Criteria) this;
        }

        public Criteria andF_vieworderIsNull() {
            addCriterion("f_vieworder is null");
            return (Criteria) this;
        }

        public Criteria andF_vieworderIsNotNull() {
            addCriterion("f_vieworder is not null");
            return (Criteria) this;
        }

        public Criteria andF_vieworderEqualTo(Short value) {
            addCriterion("f_vieworder =", value, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderNotEqualTo(Short value) {
            addCriterion("f_vieworder <>", value, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderGreaterThan(Short value) {
            addCriterion("f_vieworder >", value, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderGreaterThanOrEqualTo(Short value) {
            addCriterion("f_vieworder >=", value, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderLessThan(Short value) {
            addCriterion("f_vieworder <", value, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderLessThanOrEqualTo(Short value) {
            addCriterion("f_vieworder <=", value, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderIn(List<Short> values) {
            addCriterion("f_vieworder in", values, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderNotIn(List<Short> values) {
            addCriterion("f_vieworder not in", values, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderBetween(Short value1, Short value2) {
            addCriterion("f_vieworder between", value1, value2, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_vieworderNotBetween(Short value1, Short value2) {
            addCriterion("f_vieworder not between", value1, value2, "f_vieworder");
            return (Criteria) this;
        }

        public Criteria andF_requiredIsNull() {
            addCriterion("f_required is null");
            return (Criteria) this;
        }

        public Criteria andF_requiredIsNotNull() {
            addCriterion("f_required is not null");
            return (Criteria) this;
        }

        public Criteria andF_requiredEqualTo(Byte value) {
            addCriterion("f_required =", value, "f_required");
            return (Criteria) this;
        }

        public Criteria andF_requiredNotEqualTo(Byte value) {
            addCriterion("f_required <>", value, "f_required");
            return (Criteria) this;
        }

        public Criteria andF_requiredGreaterThan(Byte value) {
            addCriterion("f_required >", value, "f_required");
            return (Criteria) this;
        }

        public Criteria andF_requiredGreaterThanOrEqualTo(Byte value) {
            addCriterion("f_required >=", value, "f_required");
            return (Criteria) this;
        }

        public Criteria andF_requiredLessThan(Byte value) {
            addCriterion("f_required <", value, "f_required");
            return (Criteria) this;
        }

        public Criteria andF_requiredLessThanOrEqualTo(Byte value) {
            addCriterion("f_required <=", value, "f_required");
            return (Criteria) this;
        }

        public Criteria andF_requiredIn(List<Byte> values) {
            addCriterion("f_required in", values, "f_required");
            return (Criteria) this;
        }

        public Criteria andF_requiredNotIn(List<Byte> values) {
            addCriterion("f_required not in", values, "f_required");
            return (Criteria) this;
        }

        public Criteria andF_requiredBetween(Byte value1, Byte value2) {
            addCriterion("f_required between", value1, value2, "f_required");
            return (Criteria) this;
        }

        public Criteria andF_requiredNotBetween(Byte value1, Byte value2) {
            addCriterion("f_required not between", value1, value2, "f_required");
            return (Criteria) this;
        }

        public Criteria andF_closedIsNull() {
            addCriterion("f_closed is null");
            return (Criteria) this;
        }

        public Criteria andF_closedIsNotNull() {
            addCriterion("f_closed is not null");
            return (Criteria) this;
        }

        public Criteria andF_closedEqualTo(Boolean value) {
            addCriterion("f_closed =", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedNotEqualTo(Boolean value) {
            addCriterion("f_closed <>", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedGreaterThan(Boolean value) {
            addCriterion("f_closed >", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("f_closed >=", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedLessThan(Boolean value) {
            addCriterion("f_closed <", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedLessThanOrEqualTo(Boolean value) {
            addCriterion("f_closed <=", value, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedIn(List<Boolean> values) {
            addCriterion("f_closed in", values, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedNotIn(List<Boolean> values) {
            addCriterion("f_closed not in", values, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedBetween(Boolean value1, Boolean value2) {
            addCriterion("f_closed between", value1, value2, "f_closed");
            return (Criteria) this;
        }

        public Criteria andF_closedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("f_closed not between", value1, value2, "f_closed");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cm_type
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 08 15:32:53 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_cm_type
     *
     * @mbggenerated Mon Jun 08 15:32:53 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}