package com.etong.pt.data.dc;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PtIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bm_indexnum
     *
     * @mbggenerated Wed Apr 22 08:48:41 CST 2015
     */
    int countByExample(PtIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bm_indexnum
     *
     * @mbggenerated Wed Apr 22 08:48:41 CST 2015
     */
    int deleteByExample(PtIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bm_indexnum
     *
     * @mbggenerated Wed Apr 22 08:48:41 CST 2015
     */
    int insert(PtIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bm_indexnum
     *
     * @mbggenerated Wed Apr 22 08:48:41 CST 2015
     */
    int insertSelective(PtIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bm_indexnum
     *
     * @mbggenerated Wed Apr 22 08:48:41 CST 2015
     */
    List<PtIndex> selectByExample(PtIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bm_indexnum
     *
     * @mbggenerated Wed Apr 22 08:48:41 CST 2015
     */
    int updateByExampleSelective(@Param("record") PtIndex record, @Param("example") PtIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bm_indexnum
     *
     * @mbggenerated Wed Apr 22 08:48:41 CST 2015
     */
    int updateByExample(@Param("record") PtIndex record, @Param("example") PtIndexExample example);
}