package com.etong.data.auth.session;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class SessionExample implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pm_session
     *
     * @mbggenerated Mon Nov 30 12:03:44 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pm_session
     *
     * @mbggenerated Mon Nov 30 12:03:44 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pm_session
     *
     * @mbggenerated Mon Nov 30 12:03:44 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_session
     *
     * @mbggenerated Mon Nov 30 12:03:44 CST 2015
     */
    public SessionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_session
     *
     * @mbggenerated Mon Nov 30 12:03:44 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_session
     *
     * @mbggenerated Mon Nov 30 12:03:44 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_session
     *
     * @mbggenerated Mon Nov 30 12:03:44 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_session
     *
     * @mbggenerated Mon Nov 30 12:03:44 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_session
     *
     * @mbggenerated Mon Nov 30 12:03:44 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_session
     *
     * @mbggenerated Mon Nov 30 12:03:44 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_session
     *
     * @mbggenerated Mon Nov 30 12:03:44 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_session
     *
     * @mbggenerated Mon Nov 30 12:03:44 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_session
     *
     * @mbggenerated Mon Nov 30 12:03:44 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm_session
     *
     * @mbggenerated Mon Nov 30 12:03:44 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pm_session
     *
     * @mbggenerated Mon Nov 30 12:03:44 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPmsidIsNull() {
            addCriterion("f_pmsid is null");
            return (Criteria) this;
        }

        public Criteria andPmsidIsNotNull() {
            addCriterion("f_pmsid is not null");
            return (Criteria) this;
        }

        public Criteria andPmsidEqualTo(Long value) {
            addCriterion("f_pmsid =", value, "pmsid");
            return (Criteria) this;
        }

        public Criteria andPmsidNotEqualTo(Long value) {
            addCriterion("f_pmsid <>", value, "pmsid");
            return (Criteria) this;
        }

        public Criteria andPmsidGreaterThan(Long value) {
            addCriterion("f_pmsid >", value, "pmsid");
            return (Criteria) this;
        }

        public Criteria andPmsidGreaterThanOrEqualTo(Long value) {
            addCriterion("f_pmsid >=", value, "pmsid");
            return (Criteria) this;
        }

        public Criteria andPmsidLessThan(Long value) {
            addCriterion("f_pmsid <", value, "pmsid");
            return (Criteria) this;
        }

        public Criteria andPmsidLessThanOrEqualTo(Long value) {
            addCriterion("f_pmsid <=", value, "pmsid");
            return (Criteria) this;
        }

        public Criteria andPmsidIn(List<Long> values) {
            addCriterion("f_pmsid in", values, "pmsid");
            return (Criteria) this;
        }

        public Criteria andPmsidNotIn(List<Long> values) {
            addCriterion("f_pmsid not in", values, "pmsid");
            return (Criteria) this;
        }

        public Criteria andPmsidBetween(Long value1, Long value2) {
            addCriterion("f_pmsid between", value1, value2, "pmsid");
            return (Criteria) this;
        }

        public Criteria andPmsidNotBetween(Long value1, Long value2) {
            addCriterion("f_pmsid not between", value1, value2, "pmsid");
            return (Criteria) this;
        }

        public Criteria andAdminIsNull() {
            addCriterion("f_admin is null");
            return (Criteria) this;
        }

        public Criteria andAdminIsNotNull() {
            addCriterion("f_admin is not null");
            return (Criteria) this;
        }

        public Criteria andAdminEqualTo(String value) {
            addCriterion("f_admin =", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotEqualTo(String value) {
            addCriterion("f_admin <>", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminGreaterThan(String value) {
            addCriterion("f_admin >", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminGreaterThanOrEqualTo(String value) {
            addCriterion("f_admin >=", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminLessThan(String value) {
            addCriterion("f_admin <", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminLessThanOrEqualTo(String value) {
            addCriterion("f_admin <=", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminLike(String value) {
            addCriterion("f_admin like", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotLike(String value) {
            addCriterion("f_admin not like", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminIn(List<String> values) {
            addCriterion("f_admin in", values, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotIn(List<String> values) {
            addCriterion("f_admin not in", values, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminBetween(String value1, String value2) {
            addCriterion("f_admin between", value1, value2, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotBetween(String value1, String value2) {
            addCriterion("f_admin not between", value1, value2, "admin");
            return (Criteria) this;
        }

        public Criteria andJwkjsonIsNull() {
            addCriterion("f_jwkjson is null");
            return (Criteria) this;
        }

        public Criteria andJwkjsonIsNotNull() {
            addCriterion("f_jwkjson is not null");
            return (Criteria) this;
        }

        public Criteria andJwkjsonEqualTo(String value) {
            addCriterion("f_jwkjson =", value, "jwkjson");
            return (Criteria) this;
        }

        public Criteria andJwkjsonNotEqualTo(String value) {
            addCriterion("f_jwkjson <>", value, "jwkjson");
            return (Criteria) this;
        }

        public Criteria andJwkjsonGreaterThan(String value) {
            addCriterion("f_jwkjson >", value, "jwkjson");
            return (Criteria) this;
        }

        public Criteria andJwkjsonGreaterThanOrEqualTo(String value) {
            addCriterion("f_jwkjson >=", value, "jwkjson");
            return (Criteria) this;
        }

        public Criteria andJwkjsonLessThan(String value) {
            addCriterion("f_jwkjson <", value, "jwkjson");
            return (Criteria) this;
        }

        public Criteria andJwkjsonLessThanOrEqualTo(String value) {
            addCriterion("f_jwkjson <=", value, "jwkjson");
            return (Criteria) this;
        }

        public Criteria andJwkjsonLike(String value) {
            addCriterion("f_jwkjson like", value, "jwkjson");
            return (Criteria) this;
        }

        public Criteria andJwkjsonNotLike(String value) {
            addCriterion("f_jwkjson not like", value, "jwkjson");
            return (Criteria) this;
        }

        public Criteria andJwkjsonIn(List<String> values) {
            addCriterion("f_jwkjson in", values, "jwkjson");
            return (Criteria) this;
        }

        public Criteria andJwkjsonNotIn(List<String> values) {
            addCriterion("f_jwkjson not in", values, "jwkjson");
            return (Criteria) this;
        }

        public Criteria andJwkjsonBetween(String value1, String value2) {
            addCriterion("f_jwkjson between", value1, value2, "jwkjson");
            return (Criteria) this;
        }

        public Criteria andJwkjsonNotBetween(String value1, String value2) {
            addCriterion("f_jwkjson not between", value1, value2, "jwkjson");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pm_session
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 30 12:03:44 CST 2015
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pm_session
     *
     * @mbggenerated Mon Nov 30 12:03:44 CST 2015
     */
    public static class Criterion implements Serializable {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}