package com.etong.pt.data.user.system;

import java.io.Serializable;

public class UserSystem implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_um_usersystem.f_usid
     *
     * @mbggenerated Wed Dec 16 16:56:37 CST 2015
     */
    private Long usid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_um_usersystem.f_mid
     *
     * @mbggenerated Wed Dec 16 16:56:37 CST 2015
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_um_usersystem.f_stid
     *
     * @mbggenerated Wed Dec 16 16:56:37 CST 2015
     */
    private String stid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_um_usersystem.f_logintime
     *
     * @mbggenerated Wed Dec 16 16:56:37 CST 2015
     */
    private Integer logintime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_um_usersystem.f_usid
     *
     * @return the value of t_um_usersystem.f_usid
     * @mbggenerated Wed Dec 16 16:56:37 CST 2015
     */
    public Long getUsid() {
        return usid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_um_usersystem.f_usid
     *
     * @param usid the value for t_um_usersystem.f_usid
     * @mbggenerated Wed Dec 16 16:56:37 CST 2015
     */
    public void setUsid(Long usid) {
        this.usid = usid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_um_usersystem.f_mid
     *
     * @return the value of t_um_usersystem.f_mid
     * @mbggenerated Wed Dec 16 16:56:37 CST 2015
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_um_usersystem.f_mid
     *
     * @param mid the value for t_um_usersystem.f_mid
     * @mbggenerated Wed Dec 16 16:56:37 CST 2015
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_um_usersystem.f_stid
     *
     * @return the value of t_um_usersystem.f_stid
     * @mbggenerated Wed Dec 16 16:56:37 CST 2015
     */
    public String getStid() {
        return stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_um_usersystem.f_stid
     *
     * @param stid the value for t_um_usersystem.f_stid
     * @mbggenerated Wed Dec 16 16:56:37 CST 2015
     */
    public void setStid(String stid) {
        this.stid = stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_um_usersystem.f_logintime
     *
     * @return the value of t_um_usersystem.f_logintime
     * @mbggenerated Wed Dec 16 16:56:37 CST 2015
     */
    public Integer getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_um_usersystem.f_logintime
     *
     * @param logintime the value for t_um_usersystem.f_logintime
     * @mbggenerated Wed Dec 16 16:56:37 CST 2015
     */
    public void setLogintime(Integer logintime) {
        this.logintime = logintime;
    }
}